# Generated by Django 6.0 on 2025-12-11 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bfagent", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArcType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Arc type code (main, subplot, character)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Display name", max_length=100)),
                ("description", models.TextField(blank=True, help_text="Arc type description")),
                (
                    "color",
                    models.CharField(
                        default="primary", help_text="Bootstrap color class", max_length=20
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-diagram-3", help_text="Bootstrap icon class", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Arc Type",
                "verbose_name_plural": "Arc Types",
                "db_table": "writing_arc_types",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="BeatType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Technical code (e.g., 'action', 'dialogue', 'revelation')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name_en", models.CharField(help_text="English name", max_length=100)),
                ("name_de", models.CharField(help_text="German name", max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this beat type"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon class (e.g., 'fa-running')", max_length=50
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3498db", help_text="Color for visualization (hex)", max_length=7
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Beat Type",
                "verbose_name_plural": "Beat Types",
                "db_table": "beat_types",
                "ordering": ["order", "name_en"],
            },
        ),
        migrations.CreateModel(
            name="ConflictLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Technical code (e.g., 'none', 'low', 'medium', 'high', 'climax')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name_en", models.CharField(help_text="English name", max_length=100)),
                ("name_de", models.CharField(help_text="German name", max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this conflict level"),
                ),
                (
                    "intensity",
                    models.IntegerField(
                        default=0, help_text="Numeric intensity (0-10) for analysis"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#95a5a6", help_text="Color for visualization (hex)", max_length=7
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Conflict Level",
                "verbose_name_plural": "Conflict Levels",
                "db_table": "conflict_levels",
                "ordering": ["order", "intensity"],
            },
        ),
        migrations.CreateModel(
            name="ContentRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code (G, PG, PG-13, R, NC-17)", max_length=10, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'General Audiences')", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Detailed description of rating"),
                ),
                ("min_age", models.IntegerField(default=0, help_text="Minimum recommended age")),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Content Rating",
                "verbose_name_plural": "Content Ratings",
                "db_table": "writing_content_ratings",
                "ordering": ["sort_order", "min_age"],
            },
        ),
        migrations.CreateModel(
            name="EmotionalTone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Technical code (e.g., 'hopeful', 'tense')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name_en", models.CharField(help_text="English name", max_length=100)),
                ("name_de", models.CharField(help_text="German name", max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this emotional tone"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3498db", help_text="Color for visualization (hex)", max_length=7
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Emotional Tone",
                "verbose_name_plural": "Emotional Tones",
                "db_table": "emotional_tones",
                "ordering": ["order", "name_en"],
            },
        ),
        migrations.CreateModel(
            name="ErrorStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Strategy code (stop, skip, retry, fallback)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Display name", max_length=100)),
                ("description", models.TextField(blank=True, help_text="Strategy description")),
                (
                    "stops_execution",
                    models.BooleanField(
                        default=False, help_text="Does this strategy stop the workflow?"
                    ),
                ),
                (
                    "allows_retry",
                    models.BooleanField(
                        default=False, help_text="Does this strategy allow retries?"
                    ),
                ),
                (
                    "max_retries",
                    models.IntegerField(
                        default=0, help_text="Maximum retry attempts (0 = unlimited)"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="warning", help_text="Bootstrap color class", max_length=20
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-exclamation-triangle",
                        help_text="Bootstrap icon class",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Error Strategy",
                "verbose_name_plural": "Error Strategies",
                "db_table": "error_strategies",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="HandlerPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Phase code (input, processing, output)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Display name", max_length=100)),
                ("description", models.TextField(blank=True, help_text="Phase description")),
                (
                    "execution_order",
                    models.IntegerField(
                        default=0, help_text="Order of execution (lower = earlier)"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="info", help_text="Bootstrap color class", max_length=20
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-arrow-right", help_text="Bootstrap icon class", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Handler Phase",
                "verbose_name_plural": "Handler Phases",
                "db_table": "handler_phases",
                "ordering": ["execution_order", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ImportanceLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Level code (critical, major, minor)", max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(help_text="Display name", max_length=100)),
                ("description", models.TextField(blank=True, help_text="Level description")),
                (
                    "color",
                    models.CharField(
                        default="secondary", help_text="Bootstrap color class", max_length=20
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-flag", help_text="Bootstrap icon class", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Importance Level",
                "verbose_name_plural": "Importance Levels",
                "db_table": "writing_importance_levels",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="SceneConnectionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Technical code (e.g., 'foreshadowing', 'callback', 'parallel')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name_en", models.CharField(help_text="English name", max_length=100)),
                ("name_de", models.CharField(help_text="German name", max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this connection type"),
                ),
                ("icon", models.CharField(blank=True, help_text="Icon class", max_length=50)),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Scene Connection Type",
                "verbose_name_plural": "Scene Connection Types",
                "db_table": "scene_connection_types",
                "ordering": ["order", "name_en"],
            },
        ),
        migrations.CreateModel(
            name="WritingStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Stage code (planning, outlining, drafting, etc.)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Display name", max_length=100)),
                ("description", models.TextField(blank=True, help_text="Stage description")),
                (
                    "progress_percentage",
                    models.IntegerField(
                        default=0, help_text="Typical progress % when entering this stage"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="secondary", help_text="Bootstrap color class", max_length=20
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-pencil", help_text="Bootstrap icon class", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Writing Stage",
                "verbose_name_plural": "Writing Stages",
                "db_table": "writing_stages",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Location name", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this location"),
                ),
                (
                    "time_period",
                    models.CharField(
                        blank=True,
                        help_text="Time period (e.g., 'medieval', '2024', 'future')",
                        max_length=200,
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        blank=True,
                        help_text="Overall mood/atmosphere of this location",
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Internal notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        db_column="project_id",
                        help_text="Book project this location belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="bfagent.bookprojects",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "db_table": "story_locations",
                "ordering": ["project", "name"],
            },
        ),
        migrations.CreateModel(
            name="PlotThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Plot thread name", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="What is this thread about?"),
                ),
                (
                    "thread_type",
                    models.CharField(
                        choices=[
                            ("main", "Main Plot"),
                            ("subplot", "Subplot"),
                            ("background", "Background"),
                        ],
                        default="subplot",
                        help_text="Type of plot thread",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#e74c3c", help_text="Color for visualization (hex)", max_length=7
                    ),
                ),
                ("resolution", models.TextField(blank=True, help_text="How this thread resolves")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        db_column="project_id",
                        help_text="Book project this plot thread belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plot_threads",
                        to="bfagent.bookprojects",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current status of this thread",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="writing_hub.writingstage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plot Thread",
                "verbose_name_plural": "Plot Threads",
                "db_table": "plot_threads",
                "ordering": ["project", "thread_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(help_text="Scene title", max_length=200)),
                (
                    "summary",
                    models.TextField(blank=True, help_text="Brief summary of what happens"),
                ),
                ("order", models.IntegerField(default=0, help_text="Order within chapter")),
                (
                    "story_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="When does this happen in the story timeline?",
                        null=True,
                    ),
                ),
                (
                    "story_date_description",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable time (e.g., 'Three days later', 'Winter 1942')",
                        max_length=200,
                    ),
                ),
                (
                    "goal",
                    models.TextField(
                        blank=True, help_text="What should this scene accomplish? (Scene method)"
                    ),
                ),
                (
                    "disaster",
                    models.TextField(
                        blank=True, help_text="What goes wrong? How does it fail? (Scene method)"
                    ),
                ),
                (
                    "word_count_target",
                    models.IntegerField(default=2000, help_text="Target word count for this scene"),
                ),
                (
                    "word_count_actual",
                    models.IntegerField(
                        default=0, help_text="Actual word count (updated when content written)"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, help_text="Actual written content of the scene"),
                ),
                ("notes", models.TextField(blank=True, help_text="Internal notes and ideas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        db_column="chapter_id",
                        help_text="Chapter this scene belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenes",
                        to="bfagent.bookchapters",
                    ),
                ),
                (
                    "characters",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Characters present in this scene",
                        related_name="scenes",
                        to="bfagent.characters",
                    ),
                ),
                (
                    "conflict_level",
                    models.ForeignKey(
                        blank=True,
                        help_text="Conflict intensity for pacing analysis",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="writing_hub.conflictlevel",
                    ),
                ),
                (
                    "emotional_end",
                    models.ForeignKey(
                        blank=True,
                        help_text="Emotional tone at scene end",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scenes_ending",
                        to="writing_hub.emotionaltone",
                    ),
                ),
                (
                    "emotional_start",
                    models.ForeignKey(
                        blank=True,
                        help_text="Emotional tone at scene start",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scenes_starting",
                        to="writing_hub.emotionaltone",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Where does this scene take place?",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scenes",
                        to="writing_hub.location",
                    ),
                ),
                (
                    "plot_threads",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Which plot threads are advanced in this scene?",
                        related_name="scenes",
                        to="writing_hub.plotthread",
                    ),
                ),
                (
                    "pov_character",
                    models.ForeignKey(
                        blank=True,
                        help_text="Whose perspective is this scene from?",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pov_scenes",
                        to="bfagent.characters",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current status (idea, outlined, drafted, revised, final)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="writing_hub.writingstage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scene",
                "verbose_name_plural": "Scenes",
                "db_table": "story_scenes",
                "ordering": ["chapter", "order"],
            },
        ),
        migrations.CreateModel(
            name="Beat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.TextField(help_text="What happens in this beat")),
                ("order", models.IntegerField(default=0, help_text="Order within scene")),
                ("notes", models.TextField(blank=True, help_text="Internal notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beat_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of beat (action, dialogue, etc.)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="writing_hub.beattype",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        help_text="Scene this beat belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beats",
                        to="writing_hub.scene",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beat",
                "verbose_name_plural": "Beats",
                "db_table": "story_beats",
                "ordering": ["scene", "order"],
            },
        ),
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.TextField(help_text="What happens in this event")),
                (
                    "story_datetime",
                    models.DateTimeField(
                        blank=True, help_text="When does this happen in story time?", null=True
                    ),
                ),
                (
                    "story_date_description",
                    models.CharField(
                        blank=True, help_text="Human-readable time description", max_length=200
                    ),
                ),
                (
                    "is_shown",
                    models.BooleanField(
                        default=True,
                        help_text="Is this event shown in the narrative or just background?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "characters",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Characters involved in this event",
                        related_name="timeline_events",
                        to="bfagent.characters",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        db_column="project_id",
                        help_text="Book project this event belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="bfagent.bookprojects",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        help_text="Scene where this event is shown (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timeline_events",
                        to="writing_hub.scene",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timeline Event",
                "verbose_name_plural": "Timeline Events",
                "db_table": "timeline_events",
                "ordering": ["project", "story_datetime"],
            },
        ),
        migrations.CreateModel(
            name="SceneConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Details about this connection"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_scene",
                    models.ForeignKey(
                        help_text="Source scene",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections_from",
                        to="writing_hub.scene",
                    ),
                ),
                (
                    "to_scene",
                    models.ForeignKey(
                        help_text="Target scene",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections_to",
                        to="writing_hub.scene",
                    ),
                ),
                (
                    "connection_type",
                    models.ForeignKey(
                        help_text="Type of connection",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="writing_hub.sceneconnectiontype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scene Connection",
                "verbose_name_plural": "Scene Connections",
                "db_table": "scene_connections",
                "ordering": ["from_scene", "to_scene"],
                "unique_together": {("from_scene", "to_scene", "connection_type")},
            },
        ),
        migrations.AddIndex(
            model_name="scene",
            index=models.Index(fields=["chapter", "order"], name="story_scene_chapter_763492_idx"),
        ),
        migrations.AddIndex(
            model_name="scene",
            index=models.Index(fields=["pov_character"], name="story_scene_pov_cha_f6fce5_idx"),
        ),
        migrations.AddIndex(
            model_name="scene",
            index=models.Index(fields=["status"], name="story_scene_status__4fa6c1_idx"),
        ),
    ]
