# Generated by Django 5.2.6 on 2025-12-19 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0040_handler_actionhandler_handlerexecution_and_more'),
        ('writing_hub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookProject',
            fields=[
            ],
            options={
                'verbose_name': 'Book Project',
                'verbose_name_plural': 'Book Projects',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bfagent.bookprojects',),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bfagent.bookchapters',),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bfagent.characters',),
        ),
        migrations.CreateModel(
            name='OutlineVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('version_name', models.CharField(blank=True, help_text="z.B. 'Erster Entwurf', 'Nach Feedback', 'Final'", max_length=100)),
                ('framework', models.CharField(choices=[('save_the_cat', 'Save the Cat (15 Beats)'), ('heros_journey', "Hero's Journey (12 Stufen)"), ('three_act', 'Three-Act Structure (12 Beats)'), ('custom', 'Eigene Struktur')], default='save_the_cat', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('in_progress', 'In Bearbeitung'), ('review', 'Zur Überprüfung'), ('approved', 'Freigegeben'), ('finalized', 'Finalisiert')], default='draft', max_length=20)),
                ('chapters_snapshot', models.JSONField(default=list, help_text='Complete snapshot of all chapter outlines')),
                ('notes', models.TextField(blank=True, help_text='Notizen zu dieser Version')),
                ('word_count_target', models.PositiveIntegerField(default=50000)),
                ('chapter_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Aktive Version für Bearbeitung')),
                ('is_locked', models.BooleanField(default=False, help_text='Gesperrt für Änderungen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outline_versions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outline_versions', to='bfagent.bookprojects')),
            ],
            options={
                'verbose_name': 'Outline Version',
                'verbose_name_plural': 'Outline Versions',
                'db_table': 'writing_outline_versions',
                'ordering': ['-version_number', '-created_at'],
                'unique_together': {('project', 'version_number')},
            },
        ),
    ]
