# Generated by Django 5.2.6 on 2025-12-21 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0041_idea_generation_system'),
        ('writing_hub', '0004_content_type_frameworks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaGenerationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='Reihenfolge des Schritts')),
                ('name', models.CharField(help_text="Interner Name (z.B. 'core_conflict')", max_length=100)),
                ('name_de', models.CharField(help_text="Anzeigename (z.B. 'Kernkonflikt')", max_length=100)),
                ('question', models.TextField(help_text='Die Hauptfrage an den User')),
                ('question_de', models.TextField(help_text='Deutsche Version der Frage')),
                ('help_text_short', models.TextField(blank=True, help_text='Kurze Inline-Hilfe unter der Frage')),
                ('help_text_detailed', models.TextField(blank=True, help_text='Ausführliche Erklärung für Modal')),
                ('help_examples', models.JSONField(blank=True, default=list, help_text='Beispiele: ["Beispiel 1", "Beispiel 2"]')),
                ('help_tips', models.JSONField(blank=True, default=list, help_text='Tipps: ["Tipp 1", "Tipp 2"]')),
                ('help_common_mistakes', models.TextField(blank=True, help_text='Häufige Fehler die vermieden werden sollten')),
                ('help_video_url', models.URLField(blank=True, help_text='Optional: Link zu Tutorial-Video')),
                ('help_related_articles', models.JSONField(blank=True, default=list, help_text='Links zu Artikeln: [{"title": "...", "url": "..."}]')),
                ('input_type', models.CharField(choices=[('text', 'Kurztext (einzeilig)'), ('textarea', 'Langtext (mehrzeilig)'), ('select', 'Auswahl (Dropdown)'), ('multiselect', 'Mehrfachauswahl'), ('slider', 'Skala/Slider'), ('tags', 'Tags/Schlagwörter')], default='textarea', max_length=20)),
                ('input_options', models.JSONField(blank=True, default=dict, help_text='Optionen für select/multiselect: {"options": ["A", "B", "C"]}')),
                ('input_placeholder', models.CharField(blank=True, help_text='Placeholder-Text im Eingabefeld', max_length=200)),
                ('input_min_length', models.PositiveIntegerField(default=0, help_text='Minimale Zeichenanzahl (0 = keine Begrenzung)')),
                ('input_max_length', models.PositiveIntegerField(default=0, help_text='Maximale Zeichenanzahl (0 = keine Begrenzung)')),
                ('can_generate_with_ai', models.BooleanField(default=True, help_text='Kann AI diesen Schritt generieren?')),
                ('ai_prompt_template', models.TextField(blank=True, help_text='Prompt-Template für AI-Generierung (Jinja2-Syntax)')),
                ('ai_refinement_prompt', models.TextField(blank=True, help_text='Prompt für Verfeinerung basierend auf User-Feedback')),
                ('show_condition', models.JSONField(blank=True, default=dict, help_text='Bedingung wann Schritt angezeigt wird: {"step": "genre", "value": "fantasy"}')),
                ('is_required', models.BooleanField(default=True, help_text='Pflichtfeld?')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_steps', to='writing_hub.contenttype')),
                ('depends_on_steps', models.ManyToManyField(blank=True, help_text='Schritte die vorher abgeschlossen sein müssen', to='writing_hub.ideagenerationstep')),
            ],
            options={
                'verbose_name': 'Idea Generation Step',
                'verbose_name_plural': 'Idea Generation Steps',
                'db_table': 'writing_idea_generation_steps',
                'ordering': ['content_type', 'sort_order', 'step_number'],
                'unique_together': {('content_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='IdeaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Arbeitstitel des Projekts', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('in_progress', 'In Bearbeitung'), ('completed', 'Abgeschlossen'), ('abandoned', 'Abgebrochen')], default='draft', max_length=20)),
                ('current_step', models.PositiveIntegerField(default=1, help_text='Aktueller Schritt in der Ideengenerierung')),
                ('idea_summary', models.TextField(blank=True, help_text='AI-generierte Zusammenfassung aller Ideen')),
                ('idea_summary_version', models.PositiveIntegerField(default=0, help_text='Version der Zusammenfassung')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idea_sessions', to='writing_hub.contenttype')),
                ('project', models.ForeignKey(blank=True, help_text='Verknüpftes Buchprojekt (optional bei neuen Projekten)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idea_sessions', to='bfagent.bookprojects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Idea Session',
                'verbose_name_plural': 'Idea Sessions',
                'db_table': 'writing_idea_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='IdeaResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Die eigentliche Antwort/Idee')),
                ('source', models.CharField(choices=[('user', 'User-Eingabe'), ('ai', 'AI-Generiert'), ('ai_refined', 'AI-Verfeinert'), ('user_edited', 'User-Bearbeitet')], default='user', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('ai_prompt_used', models.TextField(blank=True, help_text='Der verwendete Prompt für AI-Generierung')),
                ('user_feedback', models.TextField(blank=True, help_text="User-Feedback für Verfeinerung (z.B. 'Mehr Spannung')")),
                ('is_accepted', models.BooleanField(default=False, help_text='Hat der User diese Version akzeptiert?')),
                ('is_current', models.BooleanField(default=True, help_text='Ist dies die aktuelle Version?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_response', models.ForeignKey(blank=True, help_text='Vorherige Version dieser Antwort', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='writing_hub.idearesponse')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='writing_hub.ideagenerationstep')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='writing_hub.ideasession')),
            ],
            options={
                'verbose_name': 'Idea Response',
                'verbose_name_plural': 'Idea Responses',
                'db_table': 'writing_idea_responses',
                'ordering': ['session', 'step__sort_order', '-version'],
            },
        ),
    ]
