# Generated by Django 5.2.6 on 2025-12-21 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0041_idea_generation_system'),
        ('writing_hub', '0005_idea_generation_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowPhaseLLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('planning', 'Planung (Premise, Logline, Themes)'), ('characters', 'Charaktere'), ('world', 'Weltenbau'), ('outline', 'Outline/Struktur'), ('chapters', 'Kapitel schreiben'), ('editing', 'Lektorat'), ('illustration', 'Illustration')], help_text='Workflow-Phase', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fallback_llm', models.ForeignKey(blank=True, help_text='Fallback LLM falls primäres nicht verfügbar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_phase_fallbacks', to='bfagent.llms')),
                ('llm', models.ForeignKey(blank=True, help_text='Zugewiesenes LLM für diese Phase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_phase_configs', to='bfagent.llms')),
            ],
            options={
                'verbose_name': 'Workflow Phase LLM Konfiguration',
                'verbose_name_plural': 'Workflow Phase LLM Konfigurationen',
                'db_table': 'workflow_phase_llm_config',
                'ordering': ['phase'],
            },
        ),
    ]
