# Generated by Django 5.2.6 on 2025-12-22 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0042_fix_worlds_technology_level'),
        ('writing_hub', '0006_workflow_phase_llm_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('positive', '👍 Positiv'), ('suggestion', '🔧 Verbesserung'), ('question', '❓ Frage'), ('bug', '🐛 Fehler'), ('plot', '📖 Handlung'), ('character', '👤 Charakter')], default='suggestion', max_length=20)),
                ('content', models.TextField(help_text='Feedback-Inhalt')),
                ('text_selection', models.TextField(blank=True, help_text='Markierter Textbereich')),
                ('position_start', models.IntegerField(default=0)),
                ('position_end', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Offen'), ('in_progress', 'In Bearbeitung'), ('resolved', 'Erledigt'), ('wont_fix', 'Nicht umsetzen')], default='open', max_length=20)),
                ('reviewer_name', models.CharField(blank=True, default='Autor', max_length=100)),
                ('resolution_note', models.TextField(blank=True, help_text='Notiz zur Lösung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='bfagent.bookchapters')),
            ],
            options={
                'verbose_name': 'Kapitel-Feedback',
                'verbose_name_plural': 'Kapitel-Feedbacks',
                'db_table': 'writing_chapter_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditingSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('grammar', 'Grammatik'), ('style', 'Stil'), ('consistency', 'Konsistenz'), ('repetition', 'Wiederholung'), ('clarity', 'Klarheit'), ('pacing', 'Tempo'), ('dialogue', 'Dialog')], default='style', max_length=50)),
                ('original_text', models.TextField(help_text='Originaltext aus dem Kapitel')),
                ('suggested_text', models.TextField(help_text='Verbesserter Text')),
                ('explanation', models.TextField(blank=True, help_text='Begründung für die Änderung')),
                ('position_start', models.IntegerField(default=0, help_text='Startposition im Text')),
                ('position_end', models.IntegerField(default=0, help_text='Endposition im Text')),
                ('status', models.CharField(choices=[('pending', 'Offen'), ('accepted', 'Angenommen'), ('rejected', 'Abgelehnt'), ('modified', 'Modifiziert')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editing_suggestions', to='bfagent.bookchapters')),
            ],
            options={
                'verbose_name': 'Bearbeitungsvorschlag',
                'verbose_name_plural': 'Bearbeitungsvorschläge',
                'db_table': 'writing_editing_suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(help_text="z.B. 'Erster Entwurf'", max_length=100)),
                ('version_number', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('total_words', models.IntegerField(default=0)),
                ('total_chapters', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='bfagent.bookprojects')),
            ],
            options={
                'verbose_name': 'Projekt-Version',
                'verbose_name_plural': 'Projekt-Versionen',
                'db_table': 'writing_project_versions',
                'ordering': ['-version_number'],
                'unique_together': {('project', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='ChapterSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('outline', models.TextField(blank=True)),
                ('word_count', models.IntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='bfagent.bookchapters')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_snapshots', to='writing_hub.projectversion')),
            ],
            options={
                'verbose_name': 'Kapitel-Snapshot',
                'verbose_name_plural': 'Kapitel-Snapshots',
                'db_table': 'writing_chapter_snapshots',
                'ordering': ['chapter_number'],
            },
        ),
    ]
