# Generated by Django 5.2.6 on 2025-12-22 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0042_fix_worlds_technology_level'),
        ('writing_hub', '0007_editing_review_mvp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('character', '👤 Charakter-Entwicklung'), ('pacing', '⏱️ Pacing/Tempo'), ('plot', '📖 Plot/Handlung'), ('style', '✍️ Stil/Sprache'), ('consistency', '🔗 Konsistenz'), ('structure', '🏗️ Struktur'), ('other', '📝 Sonstiges')], default='other', max_length=20)),
                ('title', models.CharField(help_text='Kurze Zusammenfassung', max_length=200)),
                ('content', models.TextField(help_text='Ausführliche Beschreibung')),
                ('status', models.CharField(choices=[('open', 'Offen'), ('in_progress', 'In Bearbeitung'), ('resolved', 'Erledigt'), ('wont_fix', 'Nicht umsetzen')], default='open', max_length=20)),
                ('reviewer_name', models.CharField(blank=True, default='Autor', max_length=100)),
                ('resolution_note', models.TextField(blank=True, help_text='Notiz zur Lösung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('affected_chapters', models.ManyToManyField(blank=True, help_text='Betroffene Kapitel (optional)', related_name='project_feedbacks', to='bfagent.bookchapters')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_feedbacks', to='bfagent.bookprojects')),
            ],
            options={
                'verbose_name': 'Projekt-Feedback',
                'verbose_name_plural': 'Projekt-Feedbacks',
                'db_table': 'writing_project_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
