# Generated by Django 5.2.6 on 2025-12-22 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0042_fix_worlds_technology_level'),
        ('writing_hub', '0008_add_project_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterIllustration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('header', '📖 Kapitel-Header'), ('scene', '🎬 Szene'), ('character', '👤 Charakter'), ('location', '🏰 Ort'), ('ending', '🔚 Kapitel-Ende')], default='header', max_length=20)),
                ('position_index', models.IntegerField(default=0, help_text='Für mehrere Bilder pro Position')),
                ('scene_description', models.TextField(help_text='Beschreibung der Szene für die Bildgenerierung')),
                ('scene_text_excerpt', models.TextField(blank=True, help_text='Textausschnitt aus dem Kapitel')),
                ('full_prompt', models.TextField(blank=True, help_text='Vollständiger Prompt inkl. Stil')),
                ('seed_used', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chapter_illustrations/')),
                ('image_url', models.URLField(blank=True, help_text='URL zum generierten Bild (DALL-E)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='chapter_illustrations/thumbs/')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('analyzing', 'Wird analysiert'), ('generating', 'Wird generiert'), ('completed', 'Fertig'), ('failed', 'Fehlgeschlagen'), ('rejected', 'Abgelehnt')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('generation_cost', models.DecimalField(decimal_places=4, default=0, help_text='Kosten in USD', max_digits=6)),
                ('generation_time_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_illustrations', to='bfagent.bookchapters')),
            ],
            options={
                'verbose_name': 'Kapitel-Illustration',
                'verbose_name_plural': 'Kapitel-Illustrationen',
                'db_table': 'writing_chapter_illustrations',
                'ordering': ['chapter__chapter_number', 'position', 'position_index'],
            },
        ),
        migrations.CreateModel(
            name='IllustrationStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_type', models.CharField(choices=[('watercolor', '🎨 Aquarell'), ('digital_art', '💻 Digital Art'), ('oil_painting', '🖼️ Ölgemälde'), ('manga', '📚 Manga/Anime'), ('realistic', '📷 Fotorealistisch'), ('cartoon', '🎪 Cartoon'), ('pencil', '✏️ Bleistiftzeichnung'), ('custom', '⚙️ Benutzerdefiniert')], default='watercolor', max_length=20)),
                ('style_name', models.CharField(help_text="z.B. 'Mystischer Aquarell-Stil'", max_length=100)),
                ('base_prompt', models.TextField(default='watercolor painting, fantasy illustration, soft edges, magical atmosphere', help_text='Basis-Stil-Beschreibung für alle Bilder')),
                ('negative_prompt', models.TextField(blank=True, default='photo, realistic, 3d render, blurry, low quality', help_text='Was vermieden werden soll')),
                ('color_palette', models.JSONField(blank=True, default=list, help_text="Hex-Farbcodes z.B. ['#2E5A4C', '#8B4513']")),
                ('reference_seed', models.IntegerField(blank=True, help_text='Seed für Reproduzierbarkeit', null=True)),
                ('provider', models.CharField(choices=[('dalle3', 'DALL-E 3'), ('sdxl', 'Stable Diffusion XL'), ('midjourney', 'Midjourney')], default='dalle3', max_length=20)),
                ('quality', models.CharField(default='hd', help_text='standard oder hd', max_length=20)),
                ('image_size', models.CharField(default='1024x1024', help_text='z.B. 1024x1024, 1792x1024', max_length=20)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='style_references/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='illustration_style', to='bfagent.bookprojects')),
            ],
            options={
                'verbose_name': 'Illustrations-Stil',
                'verbose_name_plural': 'Illustrations-Stile',
                'db_table': 'writing_illustration_styles',
            },
        ),
    ]
