# Generated by Django 5.2.6 on 2025-12-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing_hub', '0009_add_illustration_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlineversion',
            name='chapter_feedback',
            field=models.JSONField(default=dict, help_text="Feedback pro Kapitel: {chapter_number: 'feedback text'}"),
        ),
        migrations.AddField(
            model_name='outlineversion',
            name='project_feedback',
            field=models.TextField(blank=True, help_text='Allgemeines Feedback auf Projektebene (Stil, Ton, Konsistenz)'),
        ),
    ]
