# Generated manually for Agent Architecture and Literature Management

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bfagent', '0001_initial'),
        ('writing_hub', '0011_prompt_system'),
    ]

    operations = [
        # ==========================================================================
        # Agent Architecture Models
        # ==========================================================================
        migrations.CreateModel(
            name='AgentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_de', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('core', 'Core Role'), ('writer_specialized', 'Specialized Writer'), ('domain_specific', 'Domain Specific')], default='core', max_length=30)),
                ('description', models.TextField()),
                ('description_de', models.TextField(blank=True)),
                ('base_system_prompt', models.TextField(help_text='Base system prompt, can be overridden per content type')),
                ('icon', models.CharField(default='bi-robot', max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specializations', to='writing_hub.agentrole')),
            ],
            options={
                'verbose_name': 'Agent Role',
                'verbose_name_plural': 'Agent Roles',
                'db_table': 'writing_hub_agent_roles',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LlmTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('name_de', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cost_factor', models.FloatField(default=1.0, help_text='Relative cost multiplier')),
                ('priority', models.IntegerField(default=0, help_text='Higher = better quality')),
                ('default_temperature', models.FloatField(default=0.7)),
                ('default_max_tokens', models.IntegerField(default=2000)),
                ('icon', models.CharField(default='bi-cpu', max_length=50)),
                ('color', models.CharField(default='#6b7280', max_length=20)),
                ('badge_class', models.CharField(default='bg-secondary', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('default_llm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tier_default', to='bfagent.llms')),
            ],
            options={
                'verbose_name': 'LLM Tier',
                'verbose_name_plural': 'LLM Tiers',
                'db_table': 'writing_hub_llm_tiers',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='AgentRoleContentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(db_index=True, help_text='Content type code: novel, essay, scientific', max_length=50)),
                ('system_prompt_override', models.TextField(blank=True, help_text='If empty, uses base_system_prompt')),
                ('temperature_override', models.FloatField(blank=True, null=True)),
                ('max_tokens_override', models.IntegerField(blank=True, null=True)),
                ('is_applicable', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=False, help_text='Must be used in pipeline')),
                ('agent_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_configs', to='writing_hub.agentrole')),
                ('default_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='writing_hub.llmtier')),
            ],
            options={
                'verbose_name': 'Agent Role Content Config',
                'verbose_name_plural': 'Agent Role Content Configs',
                'db_table': 'writing_hub_agent_role_content_configs',
                'unique_together': {('agent_role', 'content_type')},
            },
        ),
        migrations.CreateModel(
            name='ProjectAgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_instructions', models.TextField(blank=True, help_text='Additional instructions for this project')),
                ('is_enabled', models.BooleanField(default=True)),
                ('total_calls', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('total_cost', models.FloatField(default=0.0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('agent_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writing_hub.agentrole')),
                ('llm_override', models.ForeignKey(blank=True, help_text='Override default LLM for this role', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bfagent.llms')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_configs', to='bfagent.bookprojects')),
                ('tier_override', models.ForeignKey(blank=True, help_text='Override default tier for this role', null=True, on_delete=django.db.models.deletion.SET_NULL, to='writing_hub.llmtier')),
            ],
            options={
                'verbose_name': 'Project Agent Config',
                'verbose_name_plural': 'Project Agent Configs',
                'db_table': 'writing_hub_project_agent_configs',
                'unique_together': {('project', 'agent_role')},
            },
        ),
        migrations.CreateModel(
            name='AgentPipelineTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_de', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('content_types', models.JSONField(blank=True, default=list, help_text="List of content type codes: ['novel', 'essay', 'scientific']")),
                ('pipeline_config', models.JSONField(default=list)),
                ('estimated_duration_seconds', models.IntegerField(default=60)),
                ('estimated_cost_factor', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Agent Pipeline Template',
                'verbose_name_plural': 'Agent Pipeline Templates',
                'db_table': 'writing_hub_agent_pipeline_templates',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgentPipelineExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(max_length=50)),
                ('trigger_context', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('current_step', models.IntegerField(default=0)),
                ('total_steps', models.IntegerField(default=0)),
                ('output', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('total_cost', models.FloatField(default=0.0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='writing_hub.agentpipelinetemplate')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_executions', to='bfagent.bookprojects')),
            ],
            options={
                'verbose_name': 'Pipeline Execution',
                'verbose_name_plural': 'Pipeline Executions',
                'db_table': 'writing_hub_agent_pipeline_executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentPipelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(default=dict)),
                ('system_prompt_used', models.TextField(blank=True)),
                ('user_prompt_used', models.TextField(blank=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0.0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writing_hub.agentrole')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='writing_hub.agentpipelineexecution')),
                ('llm_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bfagent.llms')),
                ('tier_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='writing_hub.llmtier')),
            ],
            options={
                'verbose_name': 'Pipeline Step',
                'verbose_name_plural': 'Pipeline Steps',
                'db_table': 'writing_hub_agent_pipeline_steps',
                'ordering': ['execution', 'step_order'],
            },
        ),
        # ==========================================================================
        # Literature Management Models
        # ==========================================================================
        migrations.CreateModel(
            name='CitationStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('article_template', models.TextField(blank=True)),
                ('book_template', models.TextField(blank=True)),
                ('chapter_template', models.TextField(blank=True)),
                ('website_template', models.TextField(blank=True)),
                ('inline_narrative_template', models.CharField(default='{author} ({year})', max_length=100)),
                ('inline_parenthetical_template', models.CharField(default='({author}, {year})', max_length=100)),
                ('hanging_indent', models.BooleanField(default=True)),
                ('sort_by', models.CharField(default='author', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Citation Style',
                'verbose_name_plural': 'Citation Styles',
                'db_table': 'writing_hub_citation_styles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LiteratureSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('article', 'Journal Article'), ('book', 'Book'), ('chapter', 'Book Chapter'), ('conference', 'Conference Paper'), ('thesis', 'Thesis/Dissertation'), ('website', 'Website'), ('report', 'Report'), ('other', 'Other')], default='article', max_length=20)),
                ('title', models.TextField()),
                ('authors', models.TextField(help_text='Comma-separated: Last, First; Last, First')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('journal', models.CharField(blank=True, max_length=255)),
                ('volume', models.CharField(blank=True, max_length=50)),
                ('issue', models.CharField(blank=True, max_length=50)),
                ('pages', models.CharField(blank=True, max_length=50)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('edition', models.CharField(blank=True, max_length=50)),
                ('conference', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('doi', models.CharField(blank=True, max_length=100, verbose_name='DOI')),
                ('accessed_date', models.DateField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('issn', models.CharField(blank=True, max_length=20, verbose_name='ISSN')),
                ('bibtex_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('bibtex_raw', models.TextField(blank=True, help_text='Raw BibTeX entry')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('citation_count', models.IntegerField(default=0, help_text='Times cited in this project')),
                ('is_read', models.BooleanField(default=False)),
                ('is_key_source', models.BooleanField(default=False, help_text='Mark as key/important source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literature_sources', to='bfagent.bookprojects')),
            ],
            options={
                'verbose_name': 'Literature Source',
                'verbose_name_plural': 'Literature Sources',
                'db_table': 'writing_hub_literature_sources',
                'ordering': ['authors', 'year'],
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_type', models.CharField(choices=[('narrative', 'Narrative (Author, Year)'), ('parenthetical', 'Parenthetical (Author, Year)'), ('direct_quote', 'Direct Quote'), ('paraphrase', 'Paraphrase')], default='parenthetical', max_length=20)),
                ('page_number', models.CharField(blank=True, help_text='Page(s) being cited', max_length=50)),
                ('quoted_text', models.TextField(blank=True)),
                ('position_marker', models.CharField(blank=True, help_text='Marker ID in text', max_length=100)),
                ('citation_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='bfagent.bookchapters')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='bfagent.bookprojects')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='writing_hub.literaturesource')),
            ],
            options={
                'verbose_name': 'Citation',
                'verbose_name_plural': 'Citations',
                'db_table': 'writing_hub_citations',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiteratureCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6366f1', max_length=20)),
                ('icon', models.CharField(default='bi-folder', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literature_collections', to='bfagent.bookprojects')),
                ('sources', models.ManyToManyField(blank=True, related_name='collections', to='writing_hub.literaturesource')),
            ],
            options={
                'verbose_name': 'Literature Collection',
                'verbose_name_plural': 'Literature Collections',
                'db_table': 'writing_hub_literature_collections',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BibTeXImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('raw_content', models.TextField()),
                ('entries_found', models.IntegerField(default=0)),
                ('entries_imported', models.IntegerField(default=0)),
                ('entries_updated', models.IntegerField(default=0)),
                ('entries_skipped', models.IntegerField(default=0)),
                ('import_log', models.JSONField(default=list)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bibtex_imports', to='bfagent.bookprojects')),
            ],
            options={
                'verbose_name': 'BibTeX Import',
                'verbose_name_plural': 'BibTeX Imports',
                'db_table': 'writing_hub_bibtex_imports',
                'ordering': ['-imported_at'],
            },
        ),
    ]
