# Generated by Django 5.2.6 on 2026-01-05 12:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0042_fix_worlds_technology_level'),
        ('writing_hub', '0012_agent_architecture_literature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GateDecisionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name_de', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='secondary', help_text='Bootstrap color class (success, warning, danger, etc.)', max_length=20)),
                ('icon', models.CharField(default='bi-question-circle', help_text='Bootstrap Icon class', max_length=50)),
                ('allows_commit', models.BooleanField(default=False, help_text='Erlaubt Kapitel-Commit/Lock')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gate Decision Type',
                'verbose_name_plural': 'Gate Decision Types',
                'db_table': 'writing_gate_decision_types',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PromiseStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name_de', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_terminal', models.BooleanField(default=False, help_text='True = Promise ist abgeschlossen (paid/retired)')),
                ('color', models.CharField(default='secondary', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promise Status',
                'verbose_name_plural': 'Promise Statuses',
                'db_table': 'writing_promise_statuses',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='QualityDimension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name_de', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Gewichtung für Overall-Score Berechnung', max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quality Dimension',
                'verbose_name_plural': 'Quality Dimensions',
                'db_table': 'writing_quality_dimensions',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ChapterQualityScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('overall_score', models.DecimalField(decimal_places=2, help_text='Gewichteter Durchschnitt aller Dimension-Scores', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('findings', models.JSONField(blank=True, default=dict, help_text='Strukturierte Findings: {deviations: [], suggestions: []}')),
                ('notes', models.TextField(blank=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_scores', to='bfagent.bookchapters')),
                ('pipeline_execution', models.ForeignKey(blank=True, help_text='Verknüpfung zum LLM-Run der die Bewertung erstellt hat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_scores', to='writing_hub.agentpipelineexecution')),
                ('scored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapter_scores', to=settings.AUTH_USER_MODEL)),
                ('gate_decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapter_scores', to='writing_hub.gatedecisiontype')),
            ],
            options={
                'verbose_name': 'Chapter Quality Score',
                'verbose_name_plural': 'Chapter Quality Scores',
                'db_table': 'writing_chapter_quality_scores',
                'ordering': ['-scored_at'],
                'get_latest_by': 'scored_at',
            },
        ),
        migrations.CreateModel(
            name='ProjectQualityConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_overall_score', models.DecimalField(decimal_places=2, default=8.0, help_text="Minimum Overall Score für 'review'", max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('auto_approve_threshold', models.DecimalField(decimal_places=2, default=9.0, help_text='Über diesem Wert: automatische Freigabe', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('auto_reject_threshold', models.DecimalField(decimal_places=2, default=5.0, help_text='Unter diesem Wert: automatische Ablehnung', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('hard_block_severity', models.IntegerField(default=4, help_text='Issues mit dieser Severity blockieren Gate', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('max_open_blockers', models.IntegerField(default=0, help_text='Max erlaubte offene Blocker für Freigabe')),
                ('require_manual_approval', models.BooleanField(default=False, help_text='Immer manuelle Freigabe erforderlich')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_config', to='bfagent.bookprojects')),
            ],
            options={
                'verbose_name': 'Project Quality Config',
                'verbose_name_plural': 'Project Quality Configs',
                'db_table': 'writing_project_quality_configs',
            },
        ),
        migrations.CreateModel(
            name='StoryPromise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('promise_key', models.CharField(db_index=True, help_text="Eindeutiger Key: 'who_destroyed_station'", max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.IntegerField(default=3, help_text='1=Haupt-Plot, 5=Minor Detail', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('introduced_chapter', models.ForeignKey(blank=True, help_text='Kapitel in dem der Hook eingeführt wurde', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introduced_promises', to='bfagent.bookchapters')),
                ('paid_chapter', models.ForeignKey(blank=True, help_text='Kapitel in dem der Hook eingelöst wurde', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_promises', to='bfagent.bookchapters')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_promises', to='bfagent.bookprojects')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promises', to='writing_hub.promisestatus')),
            ],
            options={
                'verbose_name': 'Story Promise',
                'verbose_name_plural': 'Story Promises',
                'db_table': 'writing_story_promises',
                'ordering': ['priority', 'introduced_chapter__chapter_number', 'title'],
                'unique_together': {('project', 'promise_key')},
            },
        ),
        migrations.CreateModel(
            name='PromiseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, help_text='introduce, reinforce, twist, partial_payoff, payoff, close', max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promise_events', to='bfagent.bookchapters')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('promise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='writing_hub.storypromise')),
            ],
            options={
                'verbose_name': 'Promise Event',
                'verbose_name_plural': 'Promise Events',
                'db_table': 'writing_promise_events',
                'ordering': ['chapter__chapter_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CanonFact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fact_key', models.CharField(db_index=True, help_text="Hierarchischer Key: 'character.name.attribute'", max_length=200)),
                ('fact_value', models.JSONField(help_text='Wert als JSON (String, Number, Object, Array)')),
                ('confidence', models.DecimalField(decimal_places=2, default=1.0, help_text='1.0 = sicher, 0.5 = vage/angedeutet', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('tags', models.JSONField(blank=True, default=list, help_text="Kategorisierung: ['worldbuilding', 'character', ...]")),
                ('is_active', models.BooleanField(default=True, help_text='False = Fakt wurde später widerlegt/geändert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('introduced_chapter', models.ForeignKey(blank=True, help_text='Kapitel in dem der Fakt etabliert wurde', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introduced_facts', to='bfagent.bookchapters')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canon_facts', to='bfagent.bookprojects')),
                ('superseded_by', models.ForeignKey(blank=True, help_text='Neuerer Fakt der diesen ersetzt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='writing_hub.canonfact')),
            ],
            options={
                'verbose_name': 'Canon Fact',
                'verbose_name_plural': 'Canon Facts',
                'db_table': 'writing_canon_facts',
                'indexes': [models.Index(fields=['project', 'fact_key'], name='writing_can_project_8e7926_idx'), models.Index(fields=['project', 'is_active'], name='writing_can_project_f429f8_idx')],
                'unique_together': {('project', 'fact_key')},
            },
        ),
        migrations.CreateModel(
            name='ProjectDimensionThreshold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_score', models.DecimalField(decimal_places=2, default=7.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('is_blocking', models.BooleanField(default=True, help_text='Unter min_score blockiert Gate')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_thresholds', to='writing_hub.projectqualityconfig')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_thresholds', to='writing_hub.qualitydimension')),
            ],
            options={
                'verbose_name': 'Project Dimension Threshold',
                'verbose_name_plural': 'Project Dimension Thresholds',
                'db_table': 'writing_project_dimension_thresholds',
                'unique_together': {('config', 'dimension')},
            },
        ),
        migrations.CreateModel(
            name='ChapterDimensionScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True)),
                ('quality_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_scores', to='writing_hub.chapterqualityscore')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapter_scores', to='writing_hub.qualitydimension')),
            ],
            options={
                'verbose_name': 'Chapter Dimension Score',
                'verbose_name_plural': 'Chapter Dimension Scores',
                'db_table': 'writing_chapter_dimension_scores',
                'unique_together': {('quality_score', 'dimension')},
            },
        ),
    ]
