# Generated by Django 5.2.6 on 2026-01-05 12:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing_hub', '0013_quality_scoring_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scene_type', models.CharField(choices=[('arrival', 'Ankunft/Einführung'), ('dialogue', 'Dialog-Szene'), ('action', 'Action/Spannung'), ('introspection', 'Innenschau'), ('description', 'Beschreibung/Setting'), ('conflict', 'Konflikt'), ('resolution', 'Auflösung')], max_length=50)),
                ('scene_prompt', models.TextField(help_text='Szenen-Vorgabe für die Synthese')),
                ('generated_text', models.TextField(help_text='Vom LLM generierter Text')),
                ('used_features', models.JSONField(default=list, help_text="Genutzte Stil-Features, z.B. ['reduced_metaphor', 'cool_observer']")),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('llm_used', models.CharField(blank=True, max_length=100)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Style Candidate',
                'verbose_name_plural': 'Style Candidates',
                'db_table': 'writing_style_candidates',
                'ordering': ['session', 'scene_type'],
            },
        ),
        migrations.CreateModel(
            name='AuthorStyleDNA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name des Stils, z.B. 'Mein Hauptstil', 'Thriller-Stil'", max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_primary', models.BooleanField(default=False, help_text='Hauptstil des Autors')),
                ('signature_moves', models.JSONField(default=list, help_text="Was macht diesen Stil einzigartig? z.B. ['entlarvende Metaphern', 'knappe Absätze']")),
                ('do_list', models.JSONField(default=list, help_text="Was der Stil tun soll, z.B. ['konkrete Verben verwenden', 'Subtext vor Erklärung']")),
                ('dont_list', models.JSONField(default=list, help_text="Was der Stil vermeiden soll, z.B. ['abstrakte Emotionslabels', 'Pathos']")),
                ('taboo_list', models.JSONField(default=list, help_text='Absolut verbotene Wörter/Phrasen')),
                ('rhythm_profile', models.JSONField(default=dict, help_text='Zielwerte für Rhythmus: avg_sentence_len_range, sentence_mix (short/medium/long)')),
                ('lens_profile', models.JSONField(default=dict, help_text='POV-Einstellungen: pov_distance (close/medium/distant), introspection_ratio_max')),
                ('dialogue_profile', models.JSONField(default=dict, help_text='Dialog-Stil: subtext_level (low/medium/high), tag_density_max')),
                ('imagery_profile', models.JSONField(default=dict, help_text='Bildsprache: metaphor_density, preferred_domains, sensory_anchors')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('in_lab', 'Im Labor'), ('review', 'Zur Prüfung'), ('production_ready', 'Produktionsreif'), ('archived', 'Archiviert')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_dnas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Author Style DNA',
                'verbose_name_plural': 'Author Style DNAs',
                'db_table': 'writing_author_style_dna',
                'ordering': ['author', '-is_primary', 'name'],
                'unique_together': {('author', 'name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='StyleAcceptanceTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('test_type', models.CharField(choices=[('must_have', 'Muss enthalten'), ('must_not_have', 'Darf nicht enthalten'), ('metric_range', 'Metrik im Bereich'), ('pattern_match', 'Pattern vorhanden'), ('pattern_absent', 'Pattern abwesend')], max_length=20)),
                ('test_config', models.JSONField(help_text='Test-Konfiguration je nach Type')),
                ('severity', models.PositiveIntegerField(default=3, help_text='1=Info, 2=Hinweis, 3=Wichtig, 4=Kritisch, 5=Blocker', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('style_dna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_tests', to='writing_hub.authorstyledna')),
            ],
            options={
                'verbose_name': 'Style Acceptance Test',
                'verbose_name_plural': 'Style Acceptance Tests',
                'db_table': 'writing_style_acceptance_tests',
                'ordering': ['style_dna', '-severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StyleFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.CharField(choices=[('accepted', '✅ Akzeptiert'), ('rejected', '❌ Abgelehnt'), ('partial', '⚠️ Teilweise')], max_length=20)),
                ('accepted_patterns', models.JSONField(default=list, help_text='Akzeptierte Stil-Muster aus diesem Text')),
                ('rejected_patterns', models.JSONField(default=list, help_text='Abgelehnte Stil-Muster')),
                ('author_edits', models.JSONField(default=list, help_text='Autor-Korrekturen: [{original, edit, reason}]')),
                ('general_comment', models.TextField(blank=True, help_text='Allgemeiner Kommentar des Autors')),
                ('given_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='writing_hub.stylecandidate')),
                ('given_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Style Feedback',
                'verbose_name_plural': 'Style Feedbacks',
                'db_table': 'writing_style_feedbacks',
                'ordering': ['candidate', 'given_at'],
            },
        ),
        migrations.CreateModel(
            name='StyleLabSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('purpose', models.CharField(choices=[('new_style', 'Neuen Stil entwickeln'), ('adapt_existing', 'Bestehenden Stil anpassen'), ('hybrid', 'Stile kombinieren'), ('refine', 'Stil verfeinern')], default='new_style', max_length=20)),
                ('target_genres', models.JSONField(default=list, help_text="Ziel-Genres, z.B. ['Roman', 'Thriller', 'SciFi']")),
                ('current_phase', models.CharField(choices=[('init', 'Initialisierung'), ('extraction', 'Stil-Extraktion'), ('synthesis', 'Stil-Synthese'), ('feedback', 'Autor-Feedback'), ('fixation', 'Stil-Fixierung'), ('completed', 'Abgeschlossen'), ('cancelled', 'Abgebrochen')], default='init', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_lab_sessions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Optional: Projekt für das der Stil entwickelt wird', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='style_lab_sessions', to='writing_hub.bookproject')),
                ('target_dna', models.ForeignKey(blank=True, help_text='Ziel-DNA, die entwickelt/verfeinert wird', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_sessions', to='writing_hub.authorstyledna')),
            ],
            options={
                'verbose_name': 'Style Lab Session',
                'verbose_name_plural': 'Style Lab Sessions',
                'db_table': 'writing_style_lab_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='stylecandidate',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='writing_hub.stylelabsession'),
        ),
        migrations.CreateModel(
            name='StyleObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_text', models.TextField(help_text='Analysierter Beispieltext')),
                ('source_type', models.CharField(choices=[('author_sample', 'Eigener Text des Autors'), ('reference', 'Referenztext (Vorbild)'), ('anti_reference', 'Anti-Referenz (so nicht)')], default='author_sample', max_length=50)),
                ('source_name', models.CharField(blank=True, help_text='Name/Titel des Quelltexts', max_length=200)),
                ('observations', models.JSONField(default=dict, help_text='Extrahierte Merkmale: voice, rhythm, metaphors, pov, dialogue, etc.')),
                ('contradictions', models.JSONField(default=list, help_text='Widersprüche zu anderen Texten der Session')),
                ('metrics', models.JSONField(default=dict, help_text='Messbare Metriken: word_count, avg_sentence_length, dialogue_ratio, etc.')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('llm_used', models.CharField(blank=True, max_length=100)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='writing_hub.stylelabsession')),
            ],
            options={
                'verbose_name': 'Style Observation',
                'verbose_name_plural': 'Style Observations',
                'db_table': 'writing_style_observations',
                'ordering': ['session', 'analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='StyleAdoption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('primary', 'Hauptstil'), ('secondary', 'Nebenstil'), ('experimental', 'Experimentell')], default='primary', max_length=20)),
                ('can_modify', models.BooleanField(default=False, help_text='Darf dieser Autor den Stil modifizieren?')),
                ('adopted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_adoptions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Optional: Nur für dieses Projekt', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='style_adoptions', to='writing_hub.bookproject')),
                ('style_dna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to='writing_hub.authorstyledna')),
            ],
            options={
                'verbose_name': 'Style Adoption',
                'verbose_name_plural': 'Style Adoptions',
                'db_table': 'writing_style_adoptions',
                'ordering': ['author', '-is_active', 'role'],
                'unique_together': {('author', 'style_dna', 'project')},
            },
        ),
    ]
