# Generated by Django 5.2.6 on 2026-01-05 13:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing_hub', '0014_style_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sentence_index', models.PositiveIntegerField(help_text='0-basierter Index des Satzes im Text')),
                ('sentence_text', models.TextField(help_text='Der bewertete Satz (für Referenz)')),
                ('rating', models.CharField(choices=[('accepted', '✅ Passt'), ('partial', '⚠️ Fast'), ('rejected', '❌ Nein')], max_length=20)),
                ('comment', models.TextField(blank=True, help_text='Optionaler Kommentar zum Satz')),
                ('pattern_tag', models.CharField(blank=True, help_text="Optionaler Pattern-Tag, z.B. 'cool_observer', 'too_explanatory'", max_length=100)),
                ('given_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_feedbacks', to='writing_hub.stylecandidate')),
                ('given_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sentence Feedback',
                'verbose_name_plural': 'Sentence Feedbacks',
                'db_table': 'writing_style_sentence_feedbacks',
                'ordering': ['candidate', 'sentence_index'],
                'unique_together': {('candidate', 'sentence_index')},
            },
        ),
    ]
