# Generated by Django 5.2.6 on 2026-01-07 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing_hub', '0018_creative_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylelabsession',
            name='llm',
        ),
        migrations.AlterField(
            model_name='bookidea',
            name='conflict_sketch',
            field=models.TextField(blank=True, help_text='Zentraler Konflikt'),
        ),
        migrations.AlterField(
            model_name='bookidea',
            name='protagonist_sketch',
            field=models.TextField(blank=True, help_text='Protagonist-Beschreibung'),
        ),
        migrations.AlterField(
            model_name='bookidea',
            name='setting_sketch',
            field=models.TextField(blank=True, help_text='Setting-Beschreibung'),
        ),
        migrations.AlterField(
            model_name='creativesession',
            name='created_project',
            field=models.ForeignKey(blank=True, help_text='Das aus dieser Session erstellte Projekt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creative_sessions', to='writing_hub.bookproject'),
        ),
    ]
