# Generated by Django 5.2.6 on 2026-01-07 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0042_fix_worlds_technology_level'),
        ('writing_hub', '0019_change_idea_fields_to_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativesession',
            name='llm',
            field=models.ForeignKey(blank=True, help_text='LLM für diese Kreativ-Session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creative_sessions', to='bfagent.llms'),
        ),
    ]
