# Generated by Django 5.2.6 on 2026-01-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing_hub', '0024_add_chapter_scene_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterillustration',
            name='is_selected',
            field=models.BooleanField(default=False, help_text='Ausgewählt für Verwendung im Buch'),
        ),
    ]
