# Generated by Django 5.2.6 on 2026-01-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing_hub', '0025_add_is_selected_to_illustration'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterillustration',
            name='caption',
            field=models.TextField(blank=True, help_text='Abbildungstext/Caption für das Bild'),
        ),
    ]
