# Generated by Django 5.2.6 on 2026-01-08 13:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0044_add_figure_caption_settings'),
        ('writing_hub', '0026_add_figure_caption_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name des Autors, z.B. 'Freida McFadden'", max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Kurze Biografie oder Beschreibung des Autors')),
                ('genres', models.JSONField(default=list, help_text="Genres des Autors, z.B. ['Thriller', 'Suspense']")),
                ('avatar_url', models.URLField(blank=True, help_text='URL zum Autorenbild')),
                ('is_public', models.BooleanField(default=False, help_text='Öffentlich für alle User sichtbar?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_authors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'db_table': 'writing_authors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WritingStyle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name des Stils, z.B. 'Thriller 1. Person', 'Suspense 3. Person'", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Beschreibung des Stils')),
                ('is_default', models.BooleanField(default=False, help_text='Standard-Stil für diesen Autor')),
                ('temperature', models.FloatField(default=0.7, help_text='Kreativitätsparameter (0.0-2.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('max_tokens', models.PositiveIntegerField(default=4000, help_text='Maximale Token pro Generierung')),
                ('system_prompt', models.TextField(blank=True, help_text='System-Prompt für das LLM (beschreibt den Schreibstil)')),
                ('style_instructions', models.TextField(blank=True, help_text='Detaillierte Stilanweisungen')),
                ('do_list', models.JSONField(default=list, help_text='Was der Stil tun soll')),
                ('dont_list', models.JSONField(default=list, help_text='Was der Stil vermeiden soll')),
                ('taboo_words', models.JSONField(default=list, help_text='Verbotene Wörter/Phrasen')),
                ('example_texts', models.JSONField(default=list, help_text='Beispieltexte im Stil des Autors')),
                ('default_pov', models.CharField(choices=[('first', 'Ich-Erzähler (1. Person)'), ('third_limited', 'Personaler Erzähler (3. Person limitiert)'), ('third_omni', 'Auktorialer Erzähler (3. Person allwissend)'), ('second', 'Du-Erzähler (2. Person)')], default='third_limited', help_text='Standard-Erzählperspektive', max_length=20)),
                ('default_tense', models.CharField(choices=[('past', 'Vergangenheit (Präteritum)'), ('present', 'Gegenwart (Präsens)')], default='past', help_text='Standard-Zeitform', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_styles', to='writing_hub.author')),
                ('llm', models.ForeignKey(blank=True, help_text='Bevorzugtes LLM für diesen Stil', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writing_styles', to='bfagent.llms')),
            ],
            options={
                'verbose_name': 'Writing Style',
                'verbose_name_plural': 'Writing Styles',
                'db_table': 'writing_styles',
                'ordering': ['author', '-is_default', 'name'],
                'unique_together': {('author', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProjectAuthor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False, help_text='Hauptautor des Projekts')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_projects', to='writing_hub.author')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_authors', to='bfagent.bookprojects')),
                ('writing_style', models.ForeignKey(blank=True, help_text='Spezifischer Stil für dieses Projekt (sonst Default-Stil)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_assignments', to='writing_hub.writingstyle')),
            ],
            options={
                'verbose_name': 'Project Author',
                'verbose_name_plural': 'Project Authors',
                'db_table': 'writing_project_authors',
                'ordering': ['project', 'order', '-is_primary'],
                'unique_together': {('project', 'author')},
            },
        ),
    ]
