# Generated by Django 5.2.6 on 2026-01-09 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0044_add_figure_caption_settings'),
        ('writing_hub', '0027_author_writing_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorstyledna',
            name='preferred_llm',
            field=models.ForeignKey(blank=True, help_text='Bevorzugtes LLM für diesen Stil', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='style_dnas', to='bfagent.llms'),
        ),
    ]
