# Generated by Django 5.2.6 on 2026-01-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing_hub', '0028_add_preferred_llm_to_style_dna'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Role code (protagonist, antagonist, mentor, sidekick)', max_length=30, unique=True)),
                ('name', models.CharField(help_text='Display name (English)', max_length=100)),
                ('name_de', models.CharField(blank=True, help_text='Display name (German)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Role description')),
                ('color', models.CharField(default='secondary', help_text='Bootstrap color class', max_length=20)),
                ('icon', models.CharField(default='bi-person', help_text='Bootstrap icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Character Role',
                'verbose_name_plural': 'Character Roles',
                'db_table': 'writing_character_roles',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Type code (primary, secondary, parallel, pocket, mirror)', max_length=30, unique=True)),
                ('name', models.CharField(help_text='Display name (English)', max_length=100)),
                ('name_de', models.CharField(blank=True, help_text='Display name (German)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Type description')),
                ('color', models.CharField(default='primary', help_text='Bootstrap color class', max_length=20)),
                ('icon', models.CharField(default='bi-globe', help_text='Bootstrap icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'World Type',
                'verbose_name_plural': 'World Types',
                'db_table': 'writing_world_types',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
