# Generated by Django 5.2.6 on 2026-01-15 09:13
# Fixed: Removed already-existing master_prompt field

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing_hub', '0031_add_preview_image_to_masterstyle'),
    ]

    operations = [
        # Only add language field to World - master_prompt already exists
        migrations.AddField(
            model_name='world',
            name='language',
            field=models.CharField(choices=[('de', '🇩🇪 Deutsch'), ('en', '🇬🇧 English'), ('es', '🇪🇸 Español'), ('fr', '🇫🇷 Français'), ('it', '🇮🇹 Italiano'), ('pt', '🇵🇹 Português')], default='de', help_text='Sprache der Welt-Inhalte', max_length=5),
        ),
    ]
