# Generated by Django 5.2.6 on 2026-01-22 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writing_hub', '0020_add_character_portrait'),
        ('writing_hub', '0032_add_world_language'),
    ]

    operations = [
    ]
