# Generated by Django 5.2.6 on 2026-01-22 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writing_hub', '0022_publishing_models'),
        ('writing_hub', '0033_merge_20260122_1240'),
    ]

    operations = [
    ]
