# Generated by Django 5.2.6 on 2026-01-22 18:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0070_add_screenshot_to_testrequirement'),
        ('writing_hub', '0034_merge_0022_publishing_models_0033_merge_20260122_1240'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # NOTE: AddField for master_prompt removed - column already exists in DB
        migrations.AlterField(
            model_name='promptmasterstyle',
            name='preset',
            field=models.CharField(choices=[('fairy_tale', '🧚 Märchen (Ivan Bilibin)'), ('cinematic', '🎬 Cinematisch'), ('watercolor', '🎨 Aquarell Kinderbuch'), ('manga', '📚 Manga/Anime'), ('realistic', '📷 Fotorealistisch'), ('oil_painting', '🖼️ Ölgemälde'), ('fantasy', '🐉 Fantasy/Episch'), ('steampunk', '⚙️ Steampunk'), ('gothic', '🦇 Gothic/Dunkel'), ('minimalist', '◻️ Minimalistisch'), ('comic', '💥 Comic/Graphic Novel'), ('vintage', '📜 Vintage/Retro'), ('pixel_art', '👾 Pixel Art'), ('impressionist', '🌻 Impressionismus'), ('art_nouveau', '🌸 Jugendstil'), ('custom', '⚙️ Benutzerdefiniert')], default='fairy_tale', max_length=20),
        ),
        migrations.AlterField(
            model_name='promptmasterstyle',
            name='preview_generated_at',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt der letzten Vorschau-Generierung', null=True),
        ),
        migrations.AlterField(
            model_name='promptmasterstyle',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Vorschaubild zur Visualisierung des Stils', null=True, upload_to='master_style_previews/'),
        ),
        migrations.CreateModel(
            name='IllustrationStyleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name der Vorlage', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Beschreibung des Stils')),
                ('style_type', models.CharField(choices=[('watercolor', '🎨 Aquarell'), ('digital_art', '💻 Digital Art'), ('oil_painting', '🖼️ Ölgemälde'), ('manga', '📚 Manga/Anime'), ('realistic', '📷 Fotorealistisch'), ('cartoon', '🎪 Cartoon'), ('pencil', '✏️ Bleistiftzeichnung'), ('custom', '⚙️ Benutzerdefiniert')], default='watercolor', max_length=20)),
                ('base_prompt', models.TextField(default='watercolor painting, fantasy illustration, soft edges, magical atmosphere', help_text='Basis-Stil-Beschreibung für alle Bilder')),
                ('negative_prompt', models.TextField(blank=True, default='photo, realistic, 3d render, blurry, low quality', help_text='Was vermieden werden soll')),
                ('color_palette', models.JSONField(blank=True, default=list, help_text="Hex-Farbcodes z.B. ['#2E5A4C', '#8B4513']")),
                ('provider', models.CharField(choices=[('dalle3', 'DALL-E 3'), ('sdxl', 'Stable Diffusion XL'), ('midjourney', 'Midjourney')], default='dalle3', max_length=20)),
                ('quality', models.CharField(default='hd', max_length=20)),
                ('image_size', models.CharField(default='1024x1024', max_length=20)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='style_templates/')),
                ('is_public', models.BooleanField(default=False, help_text='Für alle Benutzer sichtbar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Illustrations-Stil-Vorlage',
                'verbose_name_plural': 'Illustrations-Stil-Vorlagen',
                'db_table': 'writing_illustration_style_templates',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BookSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name der Buchreihe, z.B. 'Die Macht-Trilogie'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Beschreibung der Reihe und ihres Universums')),
                ('genre', models.CharField(blank=True, help_text='Hauptgenre der Reihe', max_length=100)),
                ('cover_image', models.ImageField(blank=True, help_text='Cover-Bild für die Buchreihe', null=True, upload_to='series_covers/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_series', to=settings.AUTH_USER_MODEL)),
                ('writing_style', models.ForeignKey(blank=True, help_text='Einheitlicher Schreibstil für die Reihe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_using', to='writing_hub.writingstyle')),
                ('illustration_style_template', models.ForeignKey(blank=True, help_text='Einheitlicher visueller Stil für alle Bücher der Reihe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_using', to='writing_hub.illustrationstyletemplate')),
            ],
            options={
                'verbose_name': 'Buchreihe',
                'verbose_name_plural': 'Buchreihen',
                'db_table': 'writing_book_series',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SharedCharacter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('protagonist', 'Protagonist'), ('antagonist', 'Antagonist'), ('deuteragonist', 'Deuteragonist'), ('supporting', 'Nebenrolle'), ('minor', 'Kleinere Rolle'), ('mentor', 'Mentor'), ('love_interest', 'Love Interest')], default='supporting', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Allgemeine Beschreibung des Charakters')),
                ('age_at_series_start', models.PositiveIntegerField(blank=True, help_text='Alter zu Beginn der Reihe', null=True)),
                ('background', models.TextField(blank=True, help_text='Hintergrundgeschichte')),
                ('personality', models.TextField(blank=True, help_text='Persönlichkeitsmerkmale')),
                ('appearance', models.TextField(blank=True, help_text='Physische Beschreibung')),
                ('motivation', models.TextField(blank=True, help_text='Was treibt diesen Charakter an?')),
                ('arc', models.TextField(blank=True, help_text='Charakterentwicklung über die Reihe')),
                ('portrait_image', models.ImageField(blank=True, null=True, upload_to='character_portraits/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='writing_hub.bookseries')),
            ],
            options={
                'verbose_name': 'Gemeinsamer Charakter',
                'verbose_name_plural': 'Gemeinsame Charaktere',
                'db_table': 'writing_shared_characters',
                'ordering': ['series', 'role', 'name'],
                'unique_together': {('series', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SharedWorld',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('world_type', models.CharField(choices=[('primary', 'Hauptwelt'), ('secondary', 'Nebenwelt'), ('realm', 'Reich/Königreich'), ('city', 'Stadt'), ('region', 'Region'), ('dimension', 'Dimension/Parallelwelt')], default='primary', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Allgemeine Beschreibung der Welt')),
                ('geography', models.TextField(blank=True, help_text='Geografie und Landschaft')),
                ('culture', models.TextField(blank=True, help_text='Kultur und Gesellschaft')),
                ('technology_level', models.TextField(blank=True, help_text='Technologisches Niveau')),
                ('magic_system', models.TextField(blank=True, help_text='Magiesystem (falls vorhanden)')),
                ('politics', models.TextField(blank=True, help_text='Politische Strukturen')),
                ('history', models.TextField(blank=True, help_text='Geschichte der Welt')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='world_previews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worlds', to='writing_hub.bookseries')),
            ],
            options={
                'verbose_name': 'Gemeinsame Welt',
                'verbose_name_plural': 'Gemeinsame Welten',
                'db_table': 'writing_shared_worlds',
                'ordering': ['series', 'world_type', 'name'],
                'unique_together': {('series', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProjectCharacterLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age_in_book', models.PositiveIntegerField(blank=True, help_text='Alter des Charakters in diesem Buch', null=True)),
                ('role_in_book', models.CharField(blank=True, help_text='Spezifische Rolle in diesem Buch (falls abweichend)', max_length=100)),
                ('appearance_notes', models.TextField(blank=True, help_text='Anmerkungen zur Erscheinung in diesem Buch')),
                ('first_appearance_chapter', models.PositiveIntegerField(blank=True, help_text='Erstes Kapitel, in dem der Charakter erscheint', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Erscheint dieser Charakter in diesem Buch?')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_links', to='bfagent.bookprojects')),
                ('shared_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='writing_hub.sharedcharacter')),
            ],
            options={
                'verbose_name': 'Projekt-Charakter-Verknüpfung',
                'verbose_name_plural': 'Projekt-Charakter-Verknüpfungen',
                'db_table': 'writing_project_character_links',
                'unique_together': {('project', 'shared_character')},
            },
        ),
        migrations.CreateModel(
            name='ProjectWorldLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_period', models.CharField(blank=True, help_text='Zeitraum/Epoche in diesem Buch', max_length=200)),
                ('relevance', models.CharField(choices=[('primary', 'Hauptschauplatz'), ('secondary', 'Nebenschauplatz'), ('mentioned', 'Nur erwähnt')], default='primary', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Anmerkungen zur Verwendung in diesem Buch')),
                ('is_active', models.BooleanField(default=True, help_text='Wird diese Welt in diesem Buch verwendet?')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_world_links', to='bfagent.bookprojects')),
                ('shared_world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='writing_hub.sharedworld')),
            ],
            options={
                'verbose_name': 'Projekt-Welt-Verknüpfung',
                'verbose_name_plural': 'Projekt-Welt-Verknüpfungen',
                'db_table': 'writing_project_world_links',
                'unique_together': {('project', 'shared_world')},
            },
        ),
    ]
