# Generated by Django 5.2.6 on 2026-01-23 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0072_import_framework_v2_fields'),
        ('writing_hub', '0036_import_framework_v2_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outlinecategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Outline Categories'},
        ),
        migrations.AlterModelOptions(
            name='outlinerecommendation',
            options={'ordering': ['import_session', 'rank']},
        ),
        migrations.RemoveField(
            model_name='importsession',
            name='step_results',
        ),
        migrations.RemoveField(
            model_name='importsession',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='outlinerecommendation',
            name='llm_analysis',
        ),
        migrations.AddField(
            model_name='bookseries',
            name='consistency_rules',
            field=models.TextField(blank=True, help_text="Regeln für Konsistenz (z.B. 'Magie hat immer einen Preis', 'Keine modernen Begriffe')"),
        ),
        migrations.AddField(
            model_name='bookseries',
            name='content_warnings',
            field=models.TextField(blank=True, help_text="Content Warnings für die Reihe (z.B. 'Gewalt, Verlust, PTSD')"),
        ),
        migrations.AddField(
            model_name='bookseries',
            name='forbidden_elements',
            field=models.TextField(blank=True, help_text="Elemente, die NICHT vorkommen sollen (z.B. 'Zeitreisen', 'Deus ex machina')"),
        ),
        migrations.AddField(
            model_name='bookseries',
            name='narrative_voice',
            field=models.CharField(blank=True, choices=[('first_person', 'Ich-Erzähler'), ('third_limited', '3. Person (begrenzt)'), ('third_omniscient', '3. Person (allwissend)'), ('multiple_pov', 'Wechselnde POVs'), ('mixed', 'Gemischt')], help_text='Einheitliche Erzählperspektive für alle Bücher', max_length=50),
        ),
        migrations.AddField(
            model_name='bookseries',
            name='required_elements',
            field=models.TextField(blank=True, help_text="Elemente, die in jedem Buch vorkommen müssen (z.B. 'Rückkehr zum Heimatort')"),
        ),
        migrations.AddField(
            model_name='bookseries',
            name='series_timeline',
            field=models.TextField(blank=True, help_text="Zeitlicher Rahmen der Reihe (z.B. '1920-1945' oder 'Mittelalter')"),
        ),
        migrations.AddField(
            model_name='bookseries',
            name='spice_level',
            field=models.CharField(blank=True, choices=[('clean', 'Clean (keine expliziten Szenen)'), ('mild', 'Mild (closed door)'), ('medium', 'Medium (fade to black)'), ('spicy', 'Spicy (explizit)'), ('very_spicy', 'Sehr Spicy (sehr explizit)')], help_text='Erotik-Level für die gesamte Reihe', max_length=20),
        ),
        migrations.AddField(
            model_name='bookseries',
            name='target_audience',
            field=models.CharField(blank=True, choices=[('children', 'Kinder (6-10)'), ('middle_grade', 'Middle Grade (10-14)'), ('young_adult', 'Young Adult (14-18)'), ('new_adult', 'New Adult (18-25)'), ('adult', 'Erwachsene'), ('all_ages', 'Alle Altersgruppen')], help_text='Zielgruppe der Reihe', max_length=50),
        ),
        migrations.AddField(
            model_name='bookseries',
            name='tone_guidelines',
            field=models.TextField(blank=True, help_text="Ton/Stimmung der Reihe (z.B. 'düster, melancholisch' oder 'humorvoll, leicht')"),
        ),
        migrations.AddField(
            model_name='importsession',
            name='analysis_result',
            field=models.JSONField(blank=True, help_text='Legacy: Vollständiges Analyse-Ergebnis', null=True),
        ),
        migrations.AddField(
            model_name='importsession',
            name='selected_chapters',
            field=models.JSONField(default=list, help_text='Legacy: Ausgewählte Kapitel-Indizes'),
        ),
        migrations.AddField(
            model_name='importsession',
            name='selected_characters',
            field=models.JSONField(default=list, help_text='Legacy: Ausgewählte Charakter-Namen'),
        ),
        migrations.AddField(
            model_name='importsession',
            name='selected_locations',
            field=models.JSONField(default=list, help_text='Legacy: Ausgewählte Locations'),
        ),
        migrations.AddField(
            model_name='importsession',
            name='selected_outline_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_sessions', to='writing_hub.outlinetemplate'),
        ),
        migrations.AddField(
            model_name='importsession',
            name='source_content_hash',
            field=models.CharField(blank=True, help_text='SHA256 Hash des Contents', max_length=64),
        ),
        migrations.AddField(
            model_name='importsession',
            name='total_llm_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='promptmasterstyle',
            name='master_prompt',
            field=models.TextField(blank=True, help_text='Der finale Master-Prompt für die Bildgenerierung. Wird automatisch aus den Komponenten generiert, kann aber manuell editiert werden.'),
        ),
        migrations.AlterField(
            model_name='importprompttemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Beschreibung des Templates'),
        ),
        migrations.AlterField(
            model_name='importprompttemplate',
            name='fallback_model',
            field=models.CharField(blank=True, help_text='Fallback LLM model', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='importprompttemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Ist dieses Template aktiv?'),
        ),
        migrations.AlterField(
            model_name='importprompttemplate',
            name='max_tokens',
            field=models.PositiveIntegerField(default=4000, help_text='Max Output Tokens'),
        ),
        migrations.AlterField(
            model_name='importprompttemplate',
            name='step_name',
            field=models.CharField(help_text='Human-readable step name', max_length=200),
        ),
        migrations.AlterField(
            model_name='importprompttemplate',
            name='step_name_de',
            field=models.CharField(blank=True, help_text='German step name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='importprompttemplate',
            name='step_order',
            field=models.PositiveIntegerField(default=10, help_text='Order of execution'),
        ),
        migrations.AlterField(
            model_name='importprompttemplate',
            name='system_prompt',
            field=models.TextField(help_text='System-Prompt für LLM'),
        ),
        migrations.AlterField(
            model_name='importprompttemplate',
            name='temperature',
            field=models.FloatField(default=0.2, help_text='LLM Temperature (0.0-1.0)'),
        ),
        migrations.AlterField(
            model_name='importprompttemplate',
            name='user_prompt_template',
            field=models.TextField(help_text='User-Prompt mit Platzhaltern: {content}, {context}, {metadata_context}'),
        ),
        migrations.AlterField(
            model_name='importprompttemplate',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Version des Templates'),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='created_project',
            field=models.ForeignKey(blank=True, help_text='Erstelltes Projekt (nach Abschluss)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_sessions', to='bfagent.bookprojects'),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='document_type',
            field=models.CharField(blank=True, help_text='Erkannter Dokumenttyp (expose, manuscript, outline, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='error_message',
            field=models.TextField(blank=True, help_text='Fehlermeldung falls failed'),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='extracted_data',
            field=models.JSONField(blank=True, help_text='Vollständiges AI-Extraktionsergebnis', null=True),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='raw_content',
            field=models.TextField(blank=True, help_text='Original-Inhalt des Dokuments'),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='selected_items',
            field=models.JSONField(blank=True, help_text='Vom User ausgewählte Items für Import', null=True),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='session_id',
            field=models.CharField(help_text='UUID für URL-Referenz', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='source_filename',
            field=models.CharField(help_text='Original-Dateiname', max_length=500),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='source_type',
            field=models.CharField(choices=[('upload', 'File Upload'), ('paste', 'Pasted Content'), ('url', 'URL Import')], default='upload', help_text='Art der Quelle', max_length=20),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='status',
            field=models.CharField(choices=[('started', 'Gestartet'), ('analyzing', 'Analysiert'), ('review', 'User Review'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen'), ('cancelled', 'Abgebrochen')], default='started', max_length=20),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='total_tokens_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='outlinecategory',
            name='code',
            field=models.CharField(help_text="Eindeutiger Code (z.B. 'classic', 'genre_specific')", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='outlinecategory',
            name='description',
            field=models.TextField(blank=True, help_text='Beschreibung der Kategorie'),
        ),
        migrations.AlterField(
            model_name='outlinecategory',
            name='icon',
            field=models.CharField(blank=True, default='bi-diagram-3', help_text='Bootstrap Icon Class', max_length=50),
        ),
        migrations.AlterField(
            model_name='outlinecategory',
            name='name',
            field=models.CharField(help_text='Anzeigename', max_length=200),
        ),
        migrations.AlterField(
            model_name='outlinecategory',
            name='name_de',
            field=models.CharField(blank=True, help_text='Deutscher Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='outlinecategory',
            name='order',
            field=models.IntegerField(default=10, help_text='Sortierreihenfolge'),
        ),
        migrations.AlterField(
            model_name='outlinerecommendation',
            name='import_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outline_recommendations', to='writing_hub.importsession'),
        ),
        migrations.AlterField(
            model_name='outlinerecommendation',
            name='match_reason',
            field=models.TextField(help_text='Begründung für die Empfehlung'),
        ),
        migrations.AlterField(
            model_name='outlinerecommendation',
            name='match_score',
            field=models.FloatField(help_text='Match-Score 0.0-1.0'),
        ),
        migrations.AlterField(
            model_name='outlinerecommendation',
            name='rank',
            field=models.IntegerField(default=1, help_text='Rang der Empfehlung (1 = beste)'),
        ),
        migrations.AlterField(
            model_name='outlinerecommendation',
            name='was_selected',
            field=models.BooleanField(default=False, help_text='Wurde vom User ausgewählt'),
        ),
        migrations.AlterField(
            model_name='outlinetemplate',
            name='avg_rating',
            field=models.FloatField(default=0.0, help_text='Average user rating'),
        ),
        migrations.AlterField(
            model_name='outlinetemplate',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Kategorie des Templates', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='writing_hub.outlinecategory'),
        ),
        migrations.AlterField(
            model_name='outlinetemplate',
            name='code',
            field=models.CharField(help_text="Eindeutiger Code (z.B. 'three_act', 'save_the_cat')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='outlinetemplate',
            name='cons',
            field=models.TextField(blank=True, help_text='Disadvantages of this structure'),
        ),
        migrations.AlterField(
            model_name='outlinetemplate',
            name='description',
            field=models.TextField(help_text='Ausführliche Beschreibung des Templates'),
        ),
        migrations.AlterField(
            model_name='outlinetemplate',
            name='description_de',
            field=models.TextField(blank=True, help_text='Deutsche Beschreibung', null=True),
        ),
        migrations.AlterField(
            model_name='outlinetemplate',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', help_text='Difficulty level for authors', max_length=20),
        ),
        migrations.AlterField(
            model_name='outlinetemplate',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Wird prominent angezeigt'),
        ),
        migrations.AlterField(
            model_name='outlinetemplate',
            name='name',
            field=models.CharField(help_text='Anzeigename', max_length=200),
        ),
        migrations.AlterField(
            model_name='outlinetemplate',
            name='name_de',
            field=models.CharField(blank=True, help_text='Deutscher Name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='outlinetemplate',
            name='pros',
            field=models.TextField(blank=True, help_text='Advantages of this structure'),
        ),
        migrations.AlterField(
            model_name='outlinetemplate',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this template was used'),
        ),
        migrations.AlterField(
            model_name='outlinetemplate',
            name='word_count_max',
            field=models.PositiveIntegerField(default=100000, help_text='Maximale Wortanzahl für Empfehlung'),
        ),
        migrations.AlterField(
            model_name='outlinetemplate',
            name='word_count_min',
            field=models.PositiveIntegerField(default=60000, help_text='Minimale Wortanzahl für Empfehlung'),
        ),
        migrations.AlterField(
            model_name='projectoutline',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this the active outline for the project'),
        ),
        migrations.AlterField(
            model_name='projectoutline',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this outline version'),
        ),
        migrations.AlterField(
            model_name='projectoutline',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Verwendetes Template (null wenn custom)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='writing_hub.outlinetemplate'),
        ),
        migrations.AlterField(
            model_name='projectoutline',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Version number of this outline'),
        ),
        migrations.AlterModelTable(
            name='outlinecategory',
            table='writing_outline_categories',
        ),
        migrations.AlterModelTable(
            name='outlinerecommendation',
            table='writing_outline_recommendations',
        ),
    ]
