# Generated by Django 5.2.6 on 2026-01-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writing_hub', '0037_alter_outlinecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='outlinecategory',
            table='writing_hub_outline_category',
        ),
        migrations.AlterModelTable(
            name='outlinerecommendation',
            table='writing_hub_outline_recommendation',
        ),
    ]
