"""Extract Django model definitions via AST for reference-doc generation.

Produces Markdown tables with field names, types, constraints, and help_text.
No Django import required — pure AST analysis (works without running Django).
"""

from __future__ import annotations

import ast
import logging
from dataclasses import dataclass, field
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass
class FieldInfo:
    name: str
    field_type: str
    max_length: str = ""
    null: bool = False
    blank: bool = False
    unique: bool = False
    db_index: bool = False
    default: str = ""
    help_text: str = ""
    choices: str = ""
    related_model: str = ""


@dataclass
class ModelInfo:
    name: str
    docstring: str = ""
    fields: list[FieldInfo] = field(default_factory=list)
    meta_verbose_name: str = ""
    meta_ordering: str = ""
    parents: list[str] = field(default_factory=list)
    file_path: str = ""
    line_number: int = 0


def extract_models_from_file(file_path: Path) -> list[ModelInfo]:
    """Parse a single Python file and extract Django model definitions."""
    try:
        source = file_path.read_text(encoding="utf-8")
        tree = ast.parse(source, filename=str(file_path))
    except (SyntaxError, UnicodeDecodeError) as exc:
        logger.warning("Cannot parse %s: %s", file_path, exc)
        return []

    models: list[ModelInfo] = []
    for node in ast.iter_child_nodes(tree):
        if not isinstance(node, ast.ClassDef):
            continue

        # Check if it inherits from models.Model (or similar)
        parent_names = _get_base_names(node)
        if not _is_django_model(parent_names):
            continue

        model = ModelInfo(
            name=node.name,
            docstring=ast.get_docstring(node) or "",
            parents=parent_names,
            file_path=str(file_path),
            line_number=node.lineno,
        )

        for item in node.body:
            if isinstance(item, ast.Assign):
                _extract_field_from_assign(item, model)
            elif isinstance(item, ast.ClassDef) and item.name == "Meta":
                _extract_meta(item, model)

        models.append(model)

    return models


def extract_models_from_repo(
    repo_path: Path, *, apps_only: bool = True
) -> list[ModelInfo]:
    """Scan a repository for all Django models."""
    search_dir = repo_path / "apps" if apps_only and (repo_path / "apps").is_dir() else repo_path
    all_models: list[ModelInfo] = []

    for py_file in sorted(search_dir.rglob("models.py")):
        if "migrations" in py_file.parts or "test" in py_file.name:
            continue
        models = extract_models_from_file(py_file)
        all_models.extend(models)

    return all_models


def render_models_markdown(
    models: list[ModelInfo], *, repo_name: str = ""
) -> str:
    """Render extracted models as a Markdown reference document."""
    lines: list[str] = [
        "<!-- AUTO-GENERATED by /session-docu — DO NOT EDIT MANUALLY -->",
        f"<!-- Generated for: {repo_name} -->",
        "",
        "# Models Reference",
        "",
    ]

    if not models:
        lines.append("_No Django models found._")
        return "\n".join(lines)

    lines.append(f"**{len(models)} models** found.\n")

    for model in models:
        lines.append(f"## {model.name}")
        lines.append("")
        if model.docstring:
            first_line = model.docstring.strip().split("\n")[0]
            lines.append(f"> {first_line}")
            lines.append("")
        if model.parents:
            lines.append(f"**Inherits:** `{'`, `'.join(model.parents)}`")
            lines.append("")
        if model.meta_verbose_name:
            lines.append(f"**Verbose name:** {model.meta_verbose_name}")
        if model.meta_ordering:
            lines.append(f"**Ordering:** `{model.meta_ordering}`")
        lines.append("")

        if model.fields:
            lines.append("| Field | Type | Constraints | Description |")
            lines.append("|-------|------|-------------|-------------|")
            for f in model.fields:
                constraints = []
                if f.unique:
                    constraints.append("unique")
                if f.db_index:
                    constraints.append("indexed")
                if f.null:
                    constraints.append("nullable")
                if f.default:
                    constraints.append(f"default: `{f.default}`")
                if f.max_length:
                    constraints.append(f"max_length={f.max_length}")
                if f.choices:
                    constraints.append(f"choices: {f.choices}")
                constraint_str = ", ".join(constraints) if constraints else "—"
                help_str = f.help_text if f.help_text else "—"
                lines.append(
                    f"| `{f.name}` | `{f.field_type}` | {constraint_str} | {help_str} |"
                )
            lines.append("")
        else:
            lines.append("_No fields detected._\n")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _get_base_names(node: ast.ClassDef) -> list[str]:
    """Extract base class names as strings."""
    names = []
    for base in node.bases:
        if isinstance(base, ast.Attribute):
            names.append(f"{_attr_to_str(base)}")
        elif isinstance(base, ast.Name):
            names.append(base.id)
    return names


def _attr_to_str(node: ast.Attribute) -> str:
    if isinstance(node.value, ast.Name):
        return f"{node.value.id}.{node.attr}"
    if isinstance(node.value, ast.Attribute):
        return f"{_attr_to_str(node.value)}.{node.attr}"
    return node.attr


def _is_django_model(parent_names: list[str]) -> bool:
    model_bases = {"models.Model", "Model", "TenantAwareModel", "TimeStampedModel"}
    return any(p in model_bases or p.endswith(".Model") for p in parent_names)


def _extract_field_from_assign(node: ast.Assign, model: ModelInfo) -> None:
    """Extract field info from a class-level assignment like `name = models.CharField(...)`."""
    if len(node.targets) != 1 or not isinstance(node.targets[0], ast.Name):
        return
    if not isinstance(node.value, ast.Call):
        return

    field_name = node.targets[0].id
    if field_name.startswith("_"):
        return

    call = node.value
    field_type = _get_call_name(call)
    if not field_type or "Field" not in field_type:
        # Also catch models.TextField etc.
        if not (field_type and ("models." in field_type or field_type.endswith("Field"))):
            return

    info = FieldInfo(name=field_name, field_type=field_type)

    for kw in call.keywords:
        if kw.arg == "max_length":
            info.max_length = _get_literal_value(kw.value)
        elif kw.arg == "null":
            info.null = _get_literal_value(kw.value) == "True"
        elif kw.arg == "blank":
            info.blank = _get_literal_value(kw.value) == "True"
        elif kw.arg == "unique":
            info.unique = _get_literal_value(kw.value) == "True"
        elif kw.arg == "db_index":
            info.db_index = _get_literal_value(kw.value) == "True"
        elif kw.arg == "default":
            info.default = _get_literal_value(kw.value)
        elif kw.arg == "help_text":
            info.help_text = _get_literal_value(kw.value)
        elif kw.arg == "choices":
            info.choices = _get_literal_value(kw.value)
        elif kw.arg == "primary_key":
            if _get_literal_value(kw.value) == "True":
                info.unique = True

    # ForeignKey / OneToOneField first positional arg = related model
    if call.args and field_type in (
        "models.ForeignKey",
        "models.OneToOneField",
        "ForeignKey",
        "OneToOneField",
    ):
        info.related_model = _get_literal_value(call.args[0])

    model.fields.append(info)


def _extract_meta(node: ast.ClassDef, model: ModelInfo) -> None:
    for item in node.body:
        if isinstance(item, ast.Assign) and len(item.targets) == 1:
            name = getattr(item.targets[0], "id", "")
            if name == "verbose_name":
                model.meta_verbose_name = _get_literal_value(item.value)
            elif name == "ordering":
                model.meta_ordering = _get_literal_value(item.value)


def _get_call_name(call: ast.Call) -> str:
    if isinstance(call.func, ast.Attribute):
        return _attr_to_str(call.func)
    if isinstance(call.func, ast.Name):
        return call.func.id
    return ""


def _get_literal_value(node: ast.expr) -> str:
    """Best-effort extraction of literal values from AST nodes."""
    if isinstance(node, ast.Constant):
        return str(node.value)
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return _attr_to_str(node)
    if isinstance(node, ast.List):
        items = [_get_literal_value(elt) for elt in node.elts]
        return f"[{', '.join(items)}]"
    if isinstance(node, ast.Call):
        return _get_call_name(node) + "(...)"
    return "..."
