"""Extract Django settings and .env.example variables for reference-doc generation.

Parses settings.py for key configuration values and .env.example for
environment variable documentation. Pure file analysis — no Django import.
"""

from __future__ import annotations

import ast
import logging
import re
from dataclasses import dataclass, field
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass
class SettingInfo:
    name: str
    value: str = ""
    source: str = "settings.py"
    line_number: int = 0
    comment: str = ""


@dataclass
class EnvVarInfo:
    name: str
    default: str = ""
    comment: str = ""
    required: bool = True


@dataclass
class ConfigProfile:
    settings: list[SettingInfo] = field(default_factory=list)
    env_vars: list[EnvVarInfo] = field(default_factory=list)
    settings_module: str = ""


def extract_settings(file_path: Path) -> list[SettingInfo]:
    """Extract uppercase assignments from a settings.py file."""
    try:
        source = file_path.read_text(encoding="utf-8")
        tree = ast.parse(source, filename=str(file_path))
    except (SyntaxError, UnicodeDecodeError) as exc:
        logger.warning("Cannot parse %s: %s", file_path, exc)
        return []

    settings: list[SettingInfo] = []
    source_lines = source.splitlines()

    for node in ast.iter_child_nodes(tree):
        if not isinstance(node, ast.Assign):
            continue
        if len(node.targets) != 1 or not isinstance(node.targets[0], ast.Name):
            continue

        name = node.targets[0].id
        # Only capture UPPER_CASE settings (Django convention)
        if not name.isupper() and not name.startswith("CELERY_"):
            continue
        # Skip dunder
        if name.startswith("__"):
            continue

        value = _get_setting_value(node.value)

        # Try to get inline comment from source
        comment = ""
        if node.lineno <= len(source_lines):
            line = source_lines[node.lineno - 1]
            if "#" in line:
                comment = line.split("#", 1)[1].strip()

        settings.append(
            SettingInfo(
                name=name,
                value=value,
                source=str(file_path),
                line_number=node.lineno,
                comment=comment,
            )
        )

    return settings


def extract_env_example(file_path: Path) -> list[EnvVarInfo]:
    """Parse a .env.example file for documented environment variables."""
    if not file_path.exists():
        return []

    env_vars: list[EnvVarInfo] = []
    current_comment = ""

    for line in file_path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()

        if not stripped:
            current_comment = ""
            continue

        if stripped.startswith("#"):
            current_comment = stripped.lstrip("# ").strip()
            continue

        # VAR=value or VAR= (empty)
        match = re.match(r"^([A-Z_][A-Z0-9_]*)=(.*)$", stripped)
        if match:
            name = match.group(1)
            default = match.group(2).strip().strip("'\"")
            env_vars.append(
                EnvVarInfo(
                    name=name,
                    default=default,
                    comment=current_comment,
                    required=not bool(default),
                )
            )
            current_comment = ""

    return env_vars


def extract_config_from_repo(repo_path: Path) -> ConfigProfile:
    """Extract settings + env vars from a Django repo."""
    profile = ConfigProfile()

    # Find settings files
    candidates = [
        repo_path / "config" / "settings.py",
        repo_path / "config" / "settings" / "base.py",
        repo_path / "settings.py",
    ]
    for candidate in candidates:
        if candidate.exists():
            profile.settings.extend(extract_settings(candidate))
            profile.settings_module = str(candidate.relative_to(repo_path))

    # Find .env.example
    env_example = repo_path / ".env.example"
    if env_example.exists():
        profile.env_vars = extract_env_example(env_example)

    return profile


def render_config_markdown(
    profile: ConfigProfile, *, repo_name: str = ""
) -> str:
    """Render extracted config as a Markdown reference document."""
    lines: list[str] = [
        "<!-- AUTO-GENERATED by /session-docu — DO NOT EDIT MANUALLY -->",
        f"<!-- Generated for: {repo_name} -->",
        "",
        "# Configuration Reference",
        "",
    ]

    if profile.settings_module:
        lines.append(f"**Settings module:** `{profile.settings_module}`\n")

    # Django Settings
    if profile.settings:
        lines.append("## Django Settings\n")

        # Group by category
        categories = _categorize_settings(profile.settings)
        for category, settings in categories.items():
            lines.append(f"### {category}\n")
            lines.append("| Setting | Value | Note |")
            lines.append("|---------|-------|------|")
            for s in settings:
                value = _sanitize_value(s.value)
                note = s.comment if s.comment else "—"
                lines.append(f"| `{s.name}` | `{value}` | {note} |")
            lines.append("")
    else:
        lines.append("_No Django settings found._\n")

    # Environment Variables
    if profile.env_vars:
        lines.append("## Environment Variables\n")
        lines.append("From `.env.example`:\n")
        lines.append("| Variable | Default | Required | Description |")
        lines.append("|----------|---------|----------|-------------|")
        for ev in profile.env_vars:
            req = "**yes**" if ev.required else "no"
            default = f"`{ev.default}`" if ev.default else "—"
            desc = ev.comment if ev.comment else "—"
            lines.append(f"| `{ev.name}` | {default} | {req} | {desc} |")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

_SETTING_CATEGORIES = {
    "Database": {"DATABASE", "DB_", "CONN_"},
    "Cache & Redis": {"CACHE", "REDIS", "CELERY"},
    "Security": {"SECRET", "ALLOWED_HOSTS", "CSRF", "CORS", "AUTH", "PASSWORD", "SESSION"},
    "Email": {"EMAIL", "SMTP"},
    "Static & Media": {"STATIC", "MEDIA", "STORAGES"},
    "Logging": {"LOG"},
    "Internationalization": {"LANGUAGE", "TIME_ZONE", "USE_I18N", "USE_L10N", "USE_TZ", "LOCALE"},
}


def _categorize_settings(
    settings: list[SettingInfo],
) -> dict[str, list[SettingInfo]]:
    categories: dict[str, list[SettingInfo]] = {}
    for s in settings:
        cat = "General"
        for category, prefixes in _SETTING_CATEGORIES.items():
            if any(s.name.startswith(p) or p in s.name for p in prefixes):
                cat = category
                break
        categories.setdefault(cat, []).append(s)
    return categories


def _get_setting_value(node: ast.expr) -> str:
    """Best-effort value extraction."""
    if isinstance(node, ast.Constant):
        val = node.value
        if isinstance(val, str) and len(val) > 60:
            return val[:57] + "..."
        return str(val)
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.List):
        return f"[...{len(node.elts)} items]"
    if isinstance(node, ast.Dict):
        return f"{{...{len(node.keys)} keys}}"
    if isinstance(node, ast.Call):
        func = ""
        if isinstance(node.func, ast.Attribute):
            if isinstance(node.func.value, ast.Name):
                func = f"{node.func.value.id}.{node.func.attr}"
            else:
                func = node.func.attr
        elif isinstance(node.func, ast.Name):
            func = node.func.id
        return f"{func}(...)"
    if isinstance(node, ast.BoolOp):
        return "..."
    return "..."


def _sanitize_value(value: str) -> str:
    """Remove potential secrets from display."""
    secret_patterns = ["password", "secret", "token", "key", "api_key"]
    lower = value.lower()
    if any(p in lower for p in secret_patterns):
        return "***"
    if len(value) > 80:
        return value[:77] + "..."
    return value
