# Generated by Django 5.2.6 on 2026-01-04 18:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('redundancy', 'Redundancy'), ('outdated', 'Outdated'), ('structure', 'Structure Issue'), ('orphan', 'Orphan File'), ('broken_link', 'Broken Link')], max_length=50)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('group_name', models.CharField(blank=True, max_length=200, null=True)),
                ('related_files', models.JSONField(blank=True, default=list)),
                ('reason', models.TextField()),
                ('suggestion', models.CharField(choices=[('archive', 'Archive'), ('review', 'Review'), ('merge', 'Merge'), ('delete', 'Delete'), ('update', 'Update'), ('ignore', 'Ignore')], max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dlm_resolved_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analysis Issue',
                'verbose_name_plural': 'Analysis Issues',
                'db_table': 'dlm_analysis_issues',
                'ordering': ['-analysis_run__created_at', 'severity', 'issue_type'],
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('archive', 'Archived'), ('delete', 'Deleted'), ('merge', 'Merged'), ('ignore', 'Ignored'), ('restore', 'Restored')], max_length=50)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dlm_action_logs', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='dlm_hub.analysisissue')),
            ],
            options={
                'verbose_name': 'Action Log',
                'verbose_name_plural': 'Action Logs',
                'db_table': 'dlm_action_logs',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scan_path', models.CharField(max_length=500)),
                ('scan_type', models.CharField(choices=[('redundancy', 'Redundancy Analysis'), ('freshness', 'Freshness Check'), ('coverage', 'Coverage Analysis'), ('full', 'Full Analysis')], max_length=50)),
                ('model_used', models.CharField(default='llama3:8b', max_length=100)),
                ('files_scanned', models.IntegerField(default=0)),
                ('files_total', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dlm_analysis_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analysis Run',
                'verbose_name_plural': 'Analysis Runs',
                'db_table': 'dlm_analysis_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='analysisissue',
            name='analysis_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='dlm_hub.analysisrun'),
        ),
    ]
