# Generated by Django 5.2.6 on 2026-01-12 07:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCPConfigSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_path', models.CharField(max_length=500)),
                ('config_hash', models.CharField(blank=True, help_text='SHA256 hash of config file', max_length=64)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='pending', max_length=20)),
                ('sync_message', models.TextField(blank=True)),
                ('servers_added', models.IntegerField(default=0)),
                ('servers_updated', models.IntegerField(default=0)),
                ('servers_removed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'MCP Config Sync',
                'db_table': 'mcp_config_syncs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MCPServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Eindeutiger Server-Name (z.B. 'bfagent')", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text="Anzeigename (z.B. 'BF Agent MCP')", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('command', models.CharField(default='wsl', help_text="z.B. 'wsl', 'npx', 'python'", max_length=50)),
                ('args', models.JSONField(default=list, help_text='Kommandozeilen-Argumente als Liste')),
                ('env', models.JSONField(blank=True, default=dict, help_text='Umgebungsvariablen')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('disabled', 'Deaktiviert'), ('error', 'Fehler'), ('unknown', 'Unbekannt')], default='unknown', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('disabled_tools', models.JSONField(blank=True, default=list, help_text='Liste deaktivierter Tools')),
                ('source_path', models.CharField(blank=True, help_text='Pfad zum Quellcode (mcp-hub)', max_length=500)),
                ('config_path', models.CharField(blank=True, help_text='Pfad zur Config-Datei', max_length=500)),
                ('repo_url', models.URLField(blank=True, help_text='GitHub/Git Repository URL')),
                ('version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('imported_from_config', models.BooleanField(default=False)),
                ('config_key', models.CharField(blank=True, help_text='Key in mcp_config.json', max_length=100)),
            ],
            options={
                'verbose_name': 'MCP Server',
                'verbose_name_plural': 'MCP Servers',
                'db_table': 'mcp_servers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MCPServerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(choices=[('builtin', 'Built-in (NPX)'), ('custom', 'Custom Python'), ('external', 'External Service')], default='custom', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='bi-box', max_length=50)),
            ],
            options={
                'verbose_name': 'MCP Server Type',
                'db_table': 'mcp_server_types',
            },
        ),
        migrations.CreateModel(
            name='MCPServerLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mcp_hub.mcpserver')),
            ],
            options={
                'verbose_name': 'MCP Server Log',
                'db_table': 'mcp_server_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mcpserver',
            name='server_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='mcp_hub.mcpservertype'),
        ),
        migrations.CreateModel(
            name='MCPTool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Tool-Name (z.B. 'bfagent_resolve_bug')", max_length=200)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('input_schema', models.JSONField(blank=True, default=dict, help_text='JSON Schema für Parameter')),
                ('is_enabled', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, help_text="z.B. 'search', 'file', 'database'", max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='mcp_hub.mcpserver')),
            ],
            options={
                'verbose_name': 'MCP Tool',
                'verbose_name_plural': 'MCP Tools',
                'db_table': 'mcp_tools',
                'ordering': ['server', 'name'],
                'unique_together': {('server', 'name')},
            },
        ),
    ]
