# Generated by Django 5.2.10 on 2026-01-23 15:43

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_local", models.CharField(blank=True, max_length=200)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("city", "Stadt"),
                            ("region", "Region"),
                            ("country", "Land"),
                            ("landmark", "Sehenswürdigkeit"),
                        ],
                        default="city",
                        max_length=20,
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("country_code", models.CharField(max_length=3)),
                ("region", models.CharField(blank=True, max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("primary_language", models.CharField(max_length=50)),
                (
                    "languages",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=10)),
                ("description", models.TextField(blank=True)),
                (
                    "notable_features",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("districts", models.JSONField(blank=True, default=list)),
                ("climate_type", models.CharField(blank=True, max_length=50)),
                (
                    "best_seasons",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("generation_model", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "Base Location",
                "verbose_name_plural": "Base Locations",
                "indexes": [
                    models.Index(fields=["name"], name="locations_b_name_216c75_idx"),
                    models.Index(
                        fields=["country"], name="locations_b_country_5f23b7_idx"
                    ),
                ],
                "unique_together": {("name", "country")},
            },
        ),
        migrations.CreateModel(
            name="ResearchCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cache_key", models.CharField(max_length=255, unique=True)),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("hit_count", models.PositiveIntegerField(default=0)),
                ("last_hit", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Research Cache",
                "verbose_name_plural": "Research Cache",
                "indexes": [
                    models.Index(
                        fields=["cache_key"], name="locations_r_cache_k_54f500_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="locations_r_expires_9be424_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LocationLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("romance", "Romance"),
                            ("thriller", "Thriller"),
                            ("mystery", "Mystery"),
                            ("romantic_suspense", "Romantic Suspense"),
                            ("cozy_mystery", "Cozy Mystery"),
                            ("fantasy", "Fantasy"),
                            ("foodie", "Foodie/Culinary"),
                            ("adventure", "Adventure"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "atmosphere",
                    models.TextField(
                        blank=True,
                        help_text="Genre-spezifische Atmosphärenbeschreibung",
                    ),
                ),
                (
                    "mood_keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "sensory_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"sight": [...], "sound": [...], "smell": [...], "taste": [...]}',
                    ),
                ),
                (
                    "key_locations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste von Orten ideal für dieses Genre",
                    ),
                ),
                (
                    "story_hooks",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        help_text="Potentielle Plot-Elemente",
                        size=None,
                    ),
                ),
                (
                    "typical_characters",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Typische Charaktere für dieses Genre an diesem Ort",
                    ),
                ),
                (
                    "conflict_opportunities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layers",
                        to="locations.baselocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Layer",
                "verbose_name_plural": "Location Layers",
                "unique_together": {("base_location", "genre")},
            },
        ),
    ]
