#!/usr/bin/env python3
"""
Model Splitter - Automatically split monolithic models.py into modular structure

Usage:
    python split_models.py /path/to/apps/bfagent/models.py

This will:
1. Create models/ directory
2. Split models into logical files
3. Create __init__.py with all imports
4. Backup original models.py
"""

import os
import re
import sys
from datetime import datetime
from pathlib import Path

# Model groupings based on your actual models
MODEL_GROUPS = {
    "base.py": [
        "CRUDConfigBase",
        "CRUDConfigMixin",
    ],
    "books.py": [
        "BookProjects",
        "BookChapters",
        "StoryArc",
        "PlotPoint",
        "BookTypes",
    ],
    "characters.py": [
        "Characters",
        "Worlds",
    ],
    "agents.py": [
        "Agents",
        "AgentType",
        "AgentAction",
        "ActionTemplate",
        "AgentExecutions",
        "AgentArtifacts",
    ],
    "prompts.py": [
        "PromptTemplate",
        "PromptExecution",
        "PromptTemplateLegacy",
        "PromptTemplateTest",
    ],
    "workflows.py": [
        "WorkflowPhase",
        "WorkflowTemplate",
        "WorkflowPhaseStep",
        "PhaseAgentConfig",
        "PhaseActionConfig",
        "ProjectPhaseHistory",
        "BookTypePhase",
    ],
    "fields.py": [
        "FieldGroup",
        "FieldDefinition",
        "ProjectFieldValue",
        "FieldValueHistory",
        "FieldTemplate",
        "TemplateField",
    ],
    "enrichment.py": [
        "EnrichmentResponse",
    ],
    "llms.py": [
        "Llms",
    ],
    "monitoring.py": [
        "GraphQLOperation",
        "FieldUsage",
        "QueryPerformanceLog",
    ],
    "master_data.py": [
        "Genre",
        "TargetAudience",
        "WritingStatus",
    ],
    "illustration.py": [
        "GeneratedImage",
        "ImageStyleProfile",
        "IllustrationImage",
        "ImageGenerationBatch",
        "ArtStyle",
        "ImageType",
        "AIProvider",
        "ImageStatus",
    ],
    "story_engine.py": [
        "StoryBible",
        "StoryStrand",
        "StoryCharacter",
        "ChapterBeat",
        "StoryChapter",
    ],
}


def extract_model_code(content: str, model_name: str) -> str:
    """Extract complete model class code including docstring and Meta"""
    # Pattern to match class definition
    pattern = rf"^class {model_name}\(.*?\):\s*$"

    lines = content.split("\n")
    model_lines = []
    in_model = False
    indent_level = 0

    for i, line in enumerate(lines):
        if re.match(pattern, line):
            in_model = True
            indent_level = len(line) - len(line.lstrip())
            model_lines.append(line)
            continue

        if in_model:
            # Check if we've exited the class (new class or unindented line)
            if (
                line.strip()
                and not line.startswith(" " * (indent_level + 1))
                and not line.strip().startswith("#")
            ):
                # Check if it's a new class definition or top-level code
                if line.startswith("class ") or (line and not line[0].isspace()):
                    break
            model_lines.append(line)

    return "\n".join(model_lines)


def create_init_file(model_groups: dict, output_dir: Path) -> str:
    """Generate __init__.py content"""
    init_content = '''"""
Django Models for BF Agent - Modular Structure
Auto-generated by split_models.py
"""

'''

    # Group imports by file
    for filename, models in sorted(model_groups.items()):
        module_name = filename.replace(".py", "")
        init_content += f"# {module_name.replace('_', ' ').title()}\n"
        init_content += f"from .{module_name} import (\n"
        for model in sorted(models):
            init_content += f"    {model},\n"
        init_content += ")\n\n"

    # Create __all__
    all_models = []
    for models in model_groups.values():
        all_models.extend(models)

    init_content += "\n__all__ = [\n"
    for model in sorted(all_models):
        init_content += f"    '{model}',\n"
    init_content += "]\n"

    return init_content


def extract_imports(content: str) -> str:
    """Extract all imports from the beginning of the file"""
    lines = content.split("\n")
    import_lines = []

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("import ") or stripped.startswith("from "):
            import_lines.append(line)
        elif stripped and not stripped.startswith("#") and not stripped.startswith('"""'):
            # Stop at first non-import, non-comment line
            if not any(stripped.startswith(x) for x in ["import ", "from "]):
                break

    return "\n".join(import_lines)


def split_models(models_file: Path):
    """Main function to split models.py"""

    if not models_file.exists():
        print(f"❌ Error: {models_file} not found")
        sys.exit(1)

    print(f"📖 Reading {models_file}")
    content = models_file.read_text()

    # Create models directory
    models_dir = models_file.parent / "models"
    models_dir.mkdir(exist_ok=True)
    print(f"📁 Created {models_dir}")

    # Backup original
    backup_file = models_file.with_suffix(".py.backup")
    models_file.rename(backup_file)
    print(f"💾 Backed up to {backup_file}")

    # Extract common imports
    common_imports = extract_imports(content)

    # Process each group
    created_files = {}
    for filename, model_names in MODEL_GROUPS.items():
        output_file = models_dir / filename

        file_content = f'''"""
{filename.replace('.py', '').replace('_', ' ').title()} Models
Auto-generated from models.py by split_models.py
Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""

{common_imports}

'''

        models_found = []
        for model_name in model_names:
            model_code = extract_model_code(content, model_name)
            if model_code:
                file_content += f"\n\n{model_code}\n"
                models_found.append(model_name)

        if models_found:
            output_file.write_text(file_content)
            created_files[filename] = models_found
            print(f"✅ Created {output_file} with {len(models_found)} models")
        else:
            print(f"⚠️  Skipped {filename} (no models found)")

    # Create __init__.py
    init_file = models_dir / "__init__.py"
    init_content = create_init_file(created_files, models_dir)
    init_file.write_text(init_content)
    print(f"✅ Created {init_file}")

    # Create empty models.py that imports from models/
    new_models_file = models_file.parent / "models.py"
    new_models_content = f'''"""
Django Models for BF Agent
Imports from modular structure in models/ directory

Migration date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Original backed up to: models.py.backup
"""

# Import all models from modular structure
from .models import *  # noqa

# Backward compatibility
__all__ = []
'''
    new_models_file.write_text(new_models_content)
    print(f"✅ Created compatibility {new_models_file}")

    print("\n" + "=" * 60)
    print("✅ Migration complete!")
    print(f"📊 Created {len(created_files)} model files")
    print(f"📝 Total models: {sum(len(models) for models in created_files.values())}")
    print("\nNext steps:")
    print("1. python manage.py makemigrations")
    print("2. python manage.py migrate")
    print("3. Run tests to verify nothing broke")
    print("4. If all good, delete models.py.backup")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python split_models.py /path/to/models.py")
        sys.exit(1)

    models_file = Path(sys.argv[1])
    split_models(models_file)
