# Generated by Django 5.2.6 on 2025-12-17 15:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('query', models.TextField(blank=True, help_text='Main research question or topic', verbose_name='Research Query')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('review', 'In Review'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('current_phase', models.CharField(default='thema_definieren', max_length=50, verbose_name='Current Phase')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_projects', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Research Project',
                'verbose_name_plural': 'Research Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler_name', models.CharField(db_index=True, max_length=100, verbose_name='Handler')),
                ('phase', models.CharField(max_length=50, verbose_name='Phase')),
                ('result_data', models.JSONField(default=dict, verbose_name='Result Data')),
                ('success', models.BooleanField(db_index=True, default=True, verbose_name='Success')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('execution_time_ms', models.PositiveIntegerField(default=0, verbose_name='Execution Time (ms)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='research.researchproject', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Research Result',
                'verbose_name_plural': 'Research Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('url', models.URLField(blank=True, max_length=2000, verbose_name='URL')),
                ('source_type', models.CharField(choices=[('web', 'Web Page'), ('pdf', 'PDF Document'), ('article', 'Article'), ('book', 'Book'), ('video', 'Video'), ('kb', 'Knowledge Base'), ('other', 'Other')], default='web', max_length=20, verbose_name='Type')),
                ('snippet', models.TextField(blank=True, verbose_name='Snippet')),
                ('full_content', models.TextField(blank=True, verbose_name='Full Content')),
                ('relevance_score', models.FloatField(default=0.0, help_text='0.0 to 1.0', verbose_name='Relevance Score')),
                ('credibility_score', models.FloatField(default=0.0, help_text='0.0 to 1.0', verbose_name='Credibility Score')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='research.researchproject', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Research Source',
                'verbose_name_plural': 'Research Sources',
                'ordering': ['-relevance_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('finding_type', models.CharField(choices=[('fact', 'Fact'), ('quote', 'Quote'), ('statistic', 'Statistic'), ('claim', 'Claim'), ('conclusion', 'Conclusion')], default='fact', max_length=20, verbose_name='Type')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('verification_notes', models.TextField(blank=True, verbose_name='Verification Notes')),
                ('importance', models.PositiveSmallIntegerField(default=5, help_text='1-10 scale', verbose_name='Importance')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='research.researchproject', verbose_name='Project')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='research.researchsource', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Research Finding',
                'verbose_name_plural': 'Research Findings',
                'ordering': ['-importance', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='researchproject',
            index=models.Index(fields=['status', 'is_active'], name='research_re_status_ce12ed_idx'),
        ),
        migrations.AddIndex(
            model_name='researchproject',
            index=models.Index(fields=['current_phase'], name='research_re_current_167b9d_idx'),
        ),
        migrations.AddIndex(
            model_name='researchresult',
            index=models.Index(fields=['project', 'handler_name'], name='research_re_project_b6fb91_idx'),
        ),
        migrations.AddIndex(
            model_name='researchresult',
            index=models.Index(fields=['success'], name='research_re_success_33fdee_idx'),
        ),
    ]
