# Generated by Django 5.2.6 on 2025-12-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='citation_style',
            field=models.CharField(choices=[('apa', 'APA (7th Edition)'), ('mla', 'MLA (9th Edition)'), ('chicago', 'Chicago'), ('harvard', 'Harvard'), ('ieee', 'IEEE'), ('vancouver', 'Vancouver')], default='apa', max_length=20, verbose_name='Citation Style'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='output_format',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML'), ('latex', 'LaTeX'), ('pdf', 'PDF'), ('bibtex', 'BibTeX')], default='markdown', max_length=20, verbose_name='Output Format'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='require_peer_reviewed',
            field=models.BooleanField(default=False, help_text='Only include peer-reviewed sources (for academic research)', verbose_name='Require Peer-Reviewed Sources'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='research_type',
            field=models.CharField(choices=[('quick_facts', 'Quick Facts'), ('deep_dive', 'Deep Dive'), ('academic', 'Academic Research')], db_index=True, default='quick_facts', max_length=20, verbose_name='Research Type'),
        ),
        migrations.AddField(
            model_name='researchsource',
            name='authors',
            field=models.JSONField(blank=True, default=list, help_text='List of author names: ["Last, First", "Last, First"]', verbose_name='Authors'),
        ),
        migrations.AddField(
            model_name='researchsource',
            name='doi',
            field=models.CharField(blank=True, help_text='Digital Object Identifier', max_length=100, verbose_name='DOI'),
        ),
        migrations.AddField(
            model_name='researchsource',
            name='is_peer_reviewed',
            field=models.BooleanField(default=False, verbose_name='Peer-Reviewed'),
        ),
        migrations.AddField(
            model_name='researchsource',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='researchsource',
            name='issue',
            field=models.CharField(blank=True, max_length=50, verbose_name='Issue'),
        ),
        migrations.AddField(
            model_name='researchsource',
            name='journal_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Journal/Publisher'),
        ),
        migrations.AddField(
            model_name='researchsource',
            name='pages',
            field=models.CharField(blank=True, max_length=50, verbose_name='Pages'),
        ),
        migrations.AddField(
            model_name='researchsource',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Publication Date'),
        ),
        migrations.AddField(
            model_name='researchsource',
            name='volume',
            field=models.CharField(blank=True, max_length=50, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='researchsource',
            name='source_type',
            field=models.CharField(choices=[('web', 'Web Page'), ('pdf', 'PDF Document'), ('article', 'Article'), ('journal', 'Journal Article'), ('book', 'Book'), ('chapter', 'Book Chapter'), ('conference', 'Conference Paper'), ('thesis', 'Thesis/Dissertation'), ('video', 'Video'), ('kb', 'Knowledge Base'), ('other', 'Other')], default='web', max_length=20, verbose_name='Type'),
        ),
    ]
