# Generated by Django 5.2.6 on 2025-12-17 15:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_add_research_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Template Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('literature_review', 'Literature Review'), ('market_research', 'Market Research'), ('competitive_analysis', 'Competitive Analysis'), ('fact_checking', 'Fact Checking'), ('technical_research', 'Technical Research'), ('general', 'General Research')], default='general', max_length=30, verbose_name='Category')),
                ('research_type', models.CharField(choices=[('quick_facts', 'Quick Facts'), ('deep_dive', 'Deep Dive'), ('academic', 'Academic Research')], default='deep_dive', max_length=20, verbose_name='Research Type')),
                ('output_format', models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML'), ('latex', 'LaTeX'), ('pdf', 'PDF'), ('bibtex', 'BibTeX')], default='markdown', max_length=20, verbose_name='Output Format')),
                ('citation_style', models.CharField(choices=[('apa', 'APA'), ('mla', 'MLA'), ('chicago', 'Chicago'), ('harvard', 'Harvard'), ('ieee', 'IEEE')], default='apa', max_length=20, verbose_name='Citation Style')),
                ('require_peer_reviewed', models.BooleanField(default=False, verbose_name='Require Peer-Reviewed')),
                ('sections', models.JSONField(blank=True, default=list, help_text='List of sections: [{"id": "intro", "title": "Introduction", "query_template": "{topic} overview"}]', verbose_name='Sections')),
                ('default_query_template', models.TextField(blank=True, help_text='Use {topic} as placeholder, e.g., "{topic} research 2024"', verbose_name='Default Query Template')),
                ('source_filters', models.JSONField(blank=True, default=dict, help_text='Filters: {"domains": ["arxiv.org"], "exclude": ["wikipedia.org"]}', verbose_name='Source Filters')),
                ('min_sources', models.PositiveIntegerField(default=5, verbose_name='Minimum Sources')),
                ('max_sources', models.PositiveIntegerField(default=20, verbose_name='Maximum Sources')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public Template')),
                ('is_system', models.BooleanField(default=False, help_text='Built-in template, cannot be deleted', verbose_name='System Template')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Usage Count')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_templates', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Research Template',
                'verbose_name_plural': 'Research Templates',
                'ordering': ['-is_system', '-usage_count', 'name'],
            },
        ),
    ]
