"""Deployment MCP Tools."""

from .docker_tools import (
    compose_down,
    compose_logs,
    compose_ps,
    compose_pull,
    compose_restart,
    compose_up,
    container_list,
    container_logs,
    container_restart,
    container_start,
    container_status,
    container_stop,
)
from .bfagent_tools import bfagent_deploy_web
from .dns_tools import (
    dns_find_records,
    dns_record_create,
    dns_record_delete,
    dns_record_get,
    dns_record_list,
    dns_record_update,
    dns_set_a_record,
    dns_set_cname_record,
    dns_zone_create,
    dns_zone_delete,
    dns_zone_get,
    dns_zone_list,
)
from .env_tools import (
    env_delete,
    env_get,
    env_list,
    env_set,
    env_validate,
    secret_delete,
    secret_list,
    secret_set,
)
from .hetzner_tools import (
    firewall_apply,
    firewall_create,
    firewall_delete,
    firewall_get,
    firewall_list,
    firewall_remove,
    firewall_set_rules,
    images_list,
    locations_list,
    server_create,
    server_delete,
    server_list,
    server_power,
    server_rebuild,
    server_status,
    server_types_list,
    ssh_key_create,
    ssh_key_delete,
    ssh_key_list,
)
from .postgres_tools import (
    db_backup,
    db_backup_list,
    db_create,
    db_drop,
    db_list,
    db_migrate,
    db_query,
    db_restore,
    db_status,
)
from .ssl_tools import (
    ssl_certbot_info,
    ssl_delete,
    ssl_expiring,
    ssl_obtain,
    ssl_renew,
    ssl_revoke,
    ssl_status,
)

__all__ = [
    # Hetzner Server Tools (Phase 1.1 + 3.1)
    "server_list",
    "server_status",
    "server_power",
    "server_create",
    "server_delete",
    "server_rebuild",
    "server_types_list",
    "images_list",
    "locations_list",
    # Firewall Tools (Phase 3.1)
    "firewall_list",
    "firewall_get",
    "firewall_create",
    "firewall_delete",
    "firewall_set_rules",
    "firewall_apply",
    "firewall_remove",
    # SSH Key Tools (Phase 3.1)
    "ssh_key_list",
    "ssh_key_create",
    "ssh_key_delete",
    # Docker Container Tools (Phase 1.2)
    "container_list",
    "container_status",
    "container_logs",
    "container_restart",
    "container_start",
    "container_stop",
    # Docker Compose Tools (Phase 2.1)
    "compose_ps",
    "compose_up",
    "compose_down",
    "compose_logs",
    "compose_pull",
    "compose_restart",
    # BF Agent Tools
    "bfagent_deploy_web",
    # PostgreSQL Tools (Phase 1.3 + 2.2)
    "db_list",
    "db_status",
    "db_create",
    "db_drop",
    "db_query",
    "db_backup",
    "db_backup_list",
    "db_restore",
    "db_migrate",
    # Environment Tools (Phase 2.3)
    "env_list",
    "env_get",
    "env_set",
    "env_delete",
    "env_validate",
    # Secret Tools (Phase 2.3)
    "secret_list",
    "secret_set",
    "secret_delete",
    # SSL Tools (Phase 3.2)
    "ssl_status",
    "ssl_expiring",
    "ssl_renew",
    "ssl_obtain",
    "ssl_revoke",
    "ssl_delete",
    "ssl_certbot_info",
    # DNS Zone Tools (Phase 3.2)
    "dns_zone_list",
    "dns_zone_get",
    "dns_zone_create",
    "dns_zone_delete",
    # DNS Record Tools (Phase 3.2)
    "dns_record_list",
    "dns_record_get",
    "dns_record_create",
    "dns_record_update",
    "dns_record_delete",
    "dns_find_records",
    "dns_set_a_record",
    "dns_set_cname_record",
]
