"""Extract Django URL patterns via AST for reference-doc generation.

Parses `urlpatterns` from urls.py files and produces Markdown tables
with path, view name, and URL name.
"""

from __future__ import annotations

import ast
import logging
from dataclasses import dataclass, field
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass
class URLPattern:
    route: str
    view: str
    name: str = ""
    methods: str = ""
    file_path: str = ""
    line_number: int = 0


@dataclass
class URLModule:
    file_path: str
    app_name: str = ""
    patterns: list[URLPattern] = field(default_factory=list)


def extract_urls_from_file(file_path: Path) -> URLModule:
    """Parse a single urls.py and extract URL patterns."""
    try:
        source = file_path.read_text(encoding="utf-8")
        tree = ast.parse(source, filename=str(file_path))
    except (SyntaxError, UnicodeDecodeError) as exc:
        logger.warning("Cannot parse %s: %s", file_path, exc)
        return URLModule(file_path=str(file_path))

    module = URLModule(file_path=str(file_path))

    for node in ast.walk(tree):
        # Extract app_name = "..."
        if (
            isinstance(node, ast.Assign)
            and len(node.targets) == 1
            and isinstance(node.targets[0], ast.Name)
            and node.targets[0].id == "app_name"
            and isinstance(node.value, ast.Constant)
        ):
            module.app_name = str(node.value.value)

        # Extract urlpatterns = [...]
        if (
            isinstance(node, ast.Assign)
            and len(node.targets) == 1
            and isinstance(node.targets[0], ast.Name)
            and node.targets[0].id == "urlpatterns"
            and isinstance(node.value, ast.List)
        ):
            for elt in node.value.elts:
                pattern = _extract_pattern(elt, file_path)
                if pattern:
                    module.patterns.append(pattern)

        # Handle urlpatterns += [...]
        if (
            isinstance(node, ast.AugAssign)
            and isinstance(node.target, ast.Name)
            and node.target.id == "urlpatterns"
            and isinstance(node.value, ast.List)
        ):
            for elt in node.value.elts:
                pattern = _extract_pattern(elt, file_path)
                if pattern:
                    module.patterns.append(pattern)

    return module


def extract_urls_from_repo(
    repo_path: Path, *, apps_only: bool = True
) -> list[URLModule]:
    """Scan a repository for all urls.py files."""
    search_dir = repo_path / "apps" if apps_only and (repo_path / "apps").is_dir() else repo_path
    modules: list[URLModule] = []

    for urls_file in sorted(search_dir.rglob("urls.py")):
        if "migrations" in urls_file.parts or "test" in urls_file.name:
            continue
        module = extract_urls_from_file(urls_file)
        if module.patterns:
            modules.append(module)

    return modules


def render_urls_markdown(
    modules: list[URLModule], *, repo_name: str = ""
) -> str:
    """Render extracted URL patterns as a Markdown reference document."""
    lines: list[str] = [
        "<!-- AUTO-GENERATED by /session-docu — DO NOT EDIT MANUALLY -->",
        f"<!-- Generated for: {repo_name} -->",
        "",
        "# API / URL Reference",
        "",
    ]

    if not modules:
        lines.append("_No URL patterns found._")
        return "\n".join(lines)

    total = sum(len(m.patterns) for m in modules)
    lines.append(f"**{total} endpoints** across {len(modules)} URL modules.\n")

    for module in modules:
        rel_path = module.file_path
        heading = module.app_name or Path(rel_path).parent.name
        lines.append(f"## {heading}")
        if module.app_name:
            lines.append(f"\n**app_name:** `{module.app_name}`")
        lines.append(f"\n**Source:** `{rel_path}`\n")

        lines.append("| Route | View | Name |")
        lines.append("|-------|------|------|")
        for p in module.patterns:
            name_str = f"`{p.name}`" if p.name else "—"
            lines.append(f"| `{p.route}` | `{p.view}` | {name_str} |")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _extract_pattern(node: ast.expr, file_path: Path) -> URLPattern | None:
    """Extract a single URL pattern from a path() or re_path() call."""
    if not isinstance(node, ast.Call):
        return None

    func_name = _get_call_name(node)
    if func_name not in ("path", "re_path"):
        return None

    route = ""
    view = ""
    name = ""

    # First positional arg = route
    if node.args:
        route = _get_str_value(node.args[0])

    # Second positional arg = view
    if len(node.args) >= 2:
        view = _get_view_name(node.args[1])

    # Keyword arguments
    for kw in node.keywords:
        if kw.arg == "name":
            name = _get_str_value(kw.value)
        elif kw.arg == "view":
            view = _get_view_name(kw.value)

    if not route and not view:
        return None

    return URLPattern(
        route=route,
        view=view,
        name=name,
        file_path=str(file_path),
        line_number=node.lineno,
    )


def _get_call_name(call: ast.Call) -> str:
    if isinstance(call.func, ast.Name):
        return call.func.id
    if isinstance(call.func, ast.Attribute):
        return call.func.attr
    return ""


def _get_str_value(node: ast.expr) -> str:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    return _get_repr(node)


def _get_view_name(node: ast.expr) -> str:
    """Extract view name from various patterns."""
    if isinstance(node, ast.Attribute):
        if isinstance(node.value, ast.Name):
            return f"{node.value.id}.{node.attr}"
        return node.attr
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Call):
        # e.g. SomeView.as_view()
        inner = _get_view_name(node.func)
        if inner.endswith(".as_view"):
            return inner.replace(".as_view", "")
        return inner + "()"
    return _get_repr(node)


def _get_repr(node: ast.expr) -> str:
    if isinstance(node, ast.Constant):
        return str(node.value)
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        if isinstance(node.value, ast.Name):
            return f"{node.value.id}.{node.attr}"
        return node.attr
    return "..."
