# Generated by Django 5.2.6 on 2026-03-11 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdrCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('adr_id', models.CharField(max_length=20, verbose_name='ADR ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='Checked At')),
                ('drift_score', models.FloatField(verbose_name='Drift Score')),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('warning', 'Warning'), ('violation', 'Violation')], max_length=20, verbose_name='Status')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details')),
            ],
            options={
                'verbose_name': 'ADR Compliance',
                'verbose_name_plural': 'ADR Compliance Records',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['tenant_id', 'adr_id'], name='cs_compliance_tenant_adr_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, help_text='0 = platform-internal', verbose_name='Tenant ID')),
                ('source', models.CharField(choices=[('travel-beat', 'Travel Beat'), ('weltenhub', 'Weltenhub'), ('bfagent', 'BF Agent'), ('pptx-hub', 'PPTX Hub'), ('cad-hub', 'CAD Hub'), ('coach-hub', 'Coach Hub'), ('agent-team', 'Agent Team')], max_length=30, verbose_name='Source')),
                ('type', models.CharField(choices=[('story', 'Story'), ('chapter', 'Chapter'), ('world', 'World'), ('scene', 'Scene'), ('character', 'Character'), ('adr', 'ADR'), ('draft', 'Draft'), ('presentation', 'Presentation'), ('cad_model', 'CAD Model'), ('prompt_result', 'Prompt Result')], max_length=30, verbose_name='Content Type')),
                ('ref_id', models.CharField(help_text='App-seitige ID des Quellobjekts', max_length=255, verbose_name='Reference ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('sha256', models.CharField(help_text='Auto-computed on save', max_length=64, verbose_name='SHA-256')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('model_used', models.CharField(blank=True, default='', help_text='e.g. gpt-4o-mini, claude-sonnet-4-20250514', max_length=100, verbose_name='LLM Model')),
                ('prompt_key', models.CharField(blank=True, default='', max_length=200, verbose_name='Prompt Key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Content Item',
                'verbose_name_plural': 'Content Items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'source'], name='cs_tenant_source_idx'), models.Index(fields=['tenant_id', 'type'], name='cs_tenant_type_idx'), models.Index(fields=['ref_id'], name='cs_ref_id_idx'), models.Index(fields=['sha256'], name='cs_sha256_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(help_text="e.g. 'derived_from', 'chapter_of', 'revision_of'", max_length=50, verbose_name='Relation Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('source_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='content_store.contentitem', verbose_name='Source Item')),
                ('target_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='content_store.contentitem', verbose_name='Target Item')),
            ],
            options={
                'verbose_name': 'Content Relation',
                'verbose_name_plural': 'Content Relations',
                'unique_together': {('source_item', 'target_item', 'relation_type')},
            },
        ),
    ]
