# Generated by Django 5.2.10 on 2026-01-23 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        ("stories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("protagonist", "Protagonist"),
                            ("love_interest", "Love Interest"),
                            ("antagonist", "Antagonist"),
                            ("sidekick", "Sidekick"),
                            ("mentor", "Mentor"),
                            ("friend", "Freund/in"),
                            ("family", "Familie"),
                            ("other", "Andere"),
                        ],
                        default="protagonist",
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Männlich"),
                            ("female", "Weiblich"),
                            ("non_binary", "Non-Binary"),
                            ("other", "Andere"),
                        ],
                        default="female",
                        max_length=20,
                    ),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "appearance",
                    models.TextField(blank=True, help_text="Äußeres Erscheinungsbild"),
                ),
                (
                    "personality",
                    models.TextField(blank=True, help_text="Persönlichkeit"),
                ),
                (
                    "background",
                    models.TextField(blank=True, help_text="Hintergrundgeschichte"),
                ),
                (
                    "relationships",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"character_id": "relationship_type"}',
                    ),
                ),
                ("current_status", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "introduced_in",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="introduced_characters",
                        to="stories.story",
                    ),
                ),
            ],
            options={
                "verbose_name": "Charakter",
                "verbose_name_plural": "Charaktere",
                "ordering": ["role", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserWorld",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Mein Story-Universum",
                        help_text="Name deines Story-Universums",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Beschreibung deines Universums"
                    ),
                ),
                ("default_genre", models.CharField(blank=True, max_length=30)),
                (
                    "default_spice_level",
                    models.CharField(default="mild", max_length=20),
                ),
                (
                    "global_triggers_avoid",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Themen die immer vermieden werden",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="world",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User World",
                "verbose_name_plural": "User Worlds",
            },
        ),
        migrations.CreateModel(
            name="PersonalPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                (
                    "place_type",
                    models.CharField(
                        choices=[
                            ("include", "In Stories verwenden"),
                            ("exclude", "NICHT verwenden"),
                            ("favorite", "Favorit (bevorzugt)"),
                        ],
                        default="include",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Warum ist dieser Ort besonders?"
                    ),
                ),
                (
                    "personal_memory",
                    models.TextField(
                        blank=True,
                        help_text="Persönliche Erinnerung (nur für dich sichtbar)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "base_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="locations.baselocation",
                    ),
                ),
                (
                    "user_world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_places",
                        to="worlds.userworld",
                    ),
                ),
            ],
            options={
                "verbose_name": "Persönlicher Ort",
                "verbose_name_plural": "Persönliche Orte",
                "ordering": ["city", "name"],
            },
        ),
        migrations.CreateModel(
            name="LocationMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(help_text="Was ist hier passiert?")),
                (
                    "emotional_significance",
                    models.CharField(
                        blank=True,
                        help_text="emotional tag: romantic, tragic, funny, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "can_reference",
                    models.BooleanField(
                        default=True,
                        help_text="Kann in zukünftigen Stories referenziert werden",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "base_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_memories",
                        to="locations.baselocation",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stories.chapter",
                    ),
                ),
                (
                    "characters_involved",
                    models.ManyToManyField(
                        blank=True,
                        related_name="location_memories",
                        to="worlds.character",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_memories",
                        to="stories.story",
                    ),
                ),
                (
                    "user_world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_memories",
                        to="worlds.userworld",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Memory",
                "verbose_name_plural": "Location Memories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="character",
            name="user_world",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characters",
                to="worlds.userworld",
            ),
        ),
    ]
