# Generated by Django 5.2.12 on 2026-03-27 16:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('scope', models.CharField(blank=True, default='', help_text='Fachbereich, z.B. explosionsschutz, brandschutz, gbu, risk', max_length=50)),
                ('structure_json', models.TextField(default='{"sections": []}', help_text='Template-Struktur als JSON')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('accepted', 'Akzeptiert'), ('archived', 'Archiviert')], default='draft', max_length=20)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('source_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dokumentvorlage',
                'verbose_name_plural': 'Dokumentvorlagen',
                'db_table': 'doc_template',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='ix_doctmpl_tenant_st'), models.Index(fields=['tenant_id', 'scope'], name='ix_doctmpl_tenant_scope')],
            },
        ),
        migrations.CreateModel(
            name='DocumentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('values_json', models.TextField(default='{}', help_text='Ausgefüllte Werte als JSON')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('review', 'In Prüfung'), ('approved', 'Freigegeben')], default='draft', max_length=20)),
                ('source_filename', models.CharField(blank=True, default='', help_text='Dateiname des importierten Dokuments', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='doc_templates.documenttemplate')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
                'db_table': 'doc_instance',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='ix_docinst_tenant_st')],
            },
        ),
    ]
