"""
Cleanup Auto-Generated Views for Re-Generation
Removes all auto-generated CRUD views so generator can recreate them with fixed URL names
"""

import re
from pathlib import Path


def cleanup_autogenerated_views():
    """Remove auto-generated view sections from main_views.py"""
    views_file = Path("apps/bfagent/views/main_views.py")

    if not views_file.exists():
        print(f"❌ File not found: {views_file}")
        return False

    content = views_file.read_text(encoding="utf-8")

    # Backup original
    backup_file = views_file.with_suffix(".py.backup")
    backup_file.write_text(content, encoding="utf-8")
    print(f"✅ Backup created: {backup_file}")

    # Find all auto-generated CRUD view blocks (between # ===CRUD=== markers or class definitions)
    # Pattern: From "class ModelNameListView" to end of DeleteView for that model

    models_to_clean = [
        "BookProjects",
        "Agents",
        "BookChapters",
        "StoryArc",
        "PlotPoint",
        "Characters",
        "BookTypes",
        "Llms",
        "AgentExecutions",
        "AgentArtifacts",
        "GraphQLOperation",
        "FieldUsage",
        "QueryPerformanceLog",
        "Genre",
        "TargetAudience",
        "WritingStatus",
        "Worlds",
        "WorkflowPhase",
        "WorkflowTemplate",
        "WorkflowPhaseStep",
        "PhaseActionConfig",
        "ProjectPhaseHistory",
    ]

    lines = content.split("\n")
    new_lines = []
    skip_until_blank = False
    current_model = None
    in_crud_block = False

    for i, line in enumerate(lines):
        # Check if we're starting a CRUD view block
        for model in models_to_clean:
            if f"class {model}ListView" in line:
                in_crud_block = True
                current_model = model
                print(f"  🗑️  Removing {model} CRUD views...")
                break

        # If in CRUD block, skip until we hit DeleteView's delete method end
        if in_crud_block and current_model:
            if f"class {current_model}DeleteView" in line:
                skip_until_blank = True
            elif skip_until_blank and line.strip() == "" and i + 1 < len(lines):
                # Check next line - if it's another class or comment section, stop skipping
                next_line = lines[i + 1].strip()
                if next_line.startswith("class ") or next_line.startswith("#"):
                    in_crud_block = False
                    skip_until_blank = False
                    current_model = None
                    new_lines.append(line)  # Keep the blank line
                    continue
            continue

        new_lines.append(line)

    # Write cleaned content
    cleaned_content = "\n".join(new_lines)
    views_file.write_text(cleaned_content, encoding="utf-8")

    print(f"\n✅ Cleaned views file: {views_file}")
    print(f"📊 Original lines: {len(lines)}")
    print(f"📊 New lines: {len(new_lines)}")
    print(f"📊 Removed: {len(lines) - len(new_lines)} lines")

    return True


if __name__ == "__main__":
    print("🧹 Cleaning up auto-generated views...")
    print("=" * 60)

    if cleanup_autogenerated_views():
        print("\n✅ SUCCESS! Auto-generated views removed.")
        print("\n🔄 Next step: Run generator with --fix to recreate views")
        print("   python scripts/auto_compliance_fixer.py --fix")
    else:
        print("\n❌ FAILED to cleanup views")
