"""
Script Reorganization Tool
Version: 1.0.0

Reorganizes scripts into proper folders:
- tools/ for production tools
- helpers/ for one-time helper scripts
- archive/ for obsolete scripts
"""

import shutil
from pathlib import Path

# Project root
PROJECT_ROOT = Path(__file__).parent.parent

# Directories
SCRIPTS_DIR = PROJECT_ROOT / "scripts"
TOOLS_DIR = SCRIPTS_DIR / "tools"
HELPERS_DIR = SCRIPTS_DIR / "helpers"
ARCHIVE_DIR = SCRIPTS_DIR / "archive"
MGMT_COMMANDS = PROJECT_ROOT / "apps" / "genagent" / "management" / "commands"

# Ensure directories exist
TOOLS_DIR.mkdir(exist_ok=True)
HELPERS_DIR.mkdir(exist_ok=True)
ARCHIVE_DIR.mkdir(exist_ok=True)

# Production Tools (keep in scripts/, move to tools/)
PRODUCTION_TOOLS = [
    "htmx_scanner.py",
    "code_formatter.py",
    "model_consistency_checker.py",
    "template_url_validator.py",
    "url_template_consistency_checker.py",
    "git-sync-tool.py",
    "migration_analyzer.py",
    "migration_utils.py",
    "safe_migrate.py",
    "screen_documentation_framework.py",
    "visual_model_explorer.py",
    "api_endpoint_checker.py",
    "control_center.py",
    "consistency_framework.py",
    "agent_action_manager.py",
    "phase_agent_template_manager.py",
    "css_theme_switcher.py",
    "make_help.py",
    "make_interactive.py",
    "generate_tool_docs_enhanced.py",
    "setup_htmx_csrf.py",
]

# Helper Scripts (move from scripts/ to helpers/)
HELPER_SCRIPTS = [
    "init_phases_and_actions.py",
    "setup_mini_test_book.py",
    "create_planning_agent.py",
    "check_table.py",
    "check_superuser.py",
    "reset_superuser_password.py",
    "kill_server.py",
]

# Cleanup/Fix Scripts (move to helpers/)
CLEANUP_SCRIPTS = [
    "cleanup_autogenerated_views.py",
    "cleanup_obsolete_tools.py",
    "fix_broken_migrations.py",
    "auto_fix_migrations.py",
    "clean_all_migrations.py",
]

# Possibly Obsolete (move to archive/)
ARCHIVE_SCRIPTS = [
    "auto_compliance_fixer.py",
    "add_filters_to_views.py",
    "check_action_templates.py",
    "check_creation_compliance.py",
    "generate_list_templates.py",
    "validate_migrations.py",
]

# Management Commands to move to helpers/
MGMT_COMMANDS_TO_MOVE = [
    "cleanup_duplicate_phases.py",
    "create_demo_phases.py",
]


def move_file(src: Path, dst: Path, category: str):
    """Move file with safety checks"""
    if not src.exists():
        print(f"⚠️  {category}: {src.name} not found, skipping")
        return False
    
    if dst.exists():
        print(f"⏭️  {category}: {dst.name} already exists, skipping")
        return False
    
    try:
        shutil.copy2(src, dst)
        print(f"✅ {category}: {src.name} → {dst.name}")
        return True
    except Exception as e:
        print(f"❌ {category}: Error moving {src.name}: {e}")
        return False


def main():
    print("🔄 Script Reorganization Tool")
    print("=" * 60)
    
    moved_count = 0
    
    # Move production tools to tools/
    print("\n📦 Moving Production Tools to tools/...")
    for script in PRODUCTION_TOOLS:
        src = SCRIPTS_DIR / script
        dst = TOOLS_DIR / script
        if move_file(src, dst, "Tools"):
            moved_count += 1
    
    # Move helper scripts to helpers/
    print("\n🔧 Moving Helper Scripts to helpers/...")
    for script in HELPER_SCRIPTS + CLEANUP_SCRIPTS:
        src = SCRIPTS_DIR / script
        dst = HELPERS_DIR / script
        if move_file(src, dst, "Helpers"):
            moved_count += 1
    
    # Move management commands to helpers/
    print("\n📋 Moving Management Commands to helpers/...")
    for script in MGMT_COMMANDS_TO_MOVE:
        src = MGMT_COMMANDS / script
        dst = HELPERS_DIR / script
        if move_file(src, dst, "Commands"):
            moved_count += 1
    
    # Move obsolete scripts to archive/
    print("\n🗄️  Moving Obsolete Scripts to archive/...")
    for script in ARCHIVE_SCRIPTS:
        src = SCRIPTS_DIR / script
        dst = ARCHIVE_DIR / script
        if move_file(src, dst, "Archive"):
            moved_count += 1
    
    print("\n" + "=" * 60)
    print(f"✅ Reorganization complete! {moved_count} files moved.")
    print("\n📚 Next steps:")
    print("1. Review moved files and verify correctness")
    print("2. Update Makefile paths if necessary")
    print("3. Update imports in other scripts")
    print("4. Run tests to ensure nothing broke")
    print("5. Git commit the reorganization")
    print("\n💡 Run in DRY RUN mode first to see what would be moved!")


def dry_run():
    """Show what would be moved without actually moving"""
    print("🔄 Script Reorganization - DRY RUN")
    print("=" * 60)
    
    # Collect all categorized scripts
    all_categorized = set(
        PRODUCTION_TOOLS + 
        HELPER_SCRIPTS + 
        CLEANUP_SCRIPTS + 
        ARCHIVE_SCRIPTS +
        MGMT_COMMANDS_TO_MOVE
    )
    
    # Scan actual scripts directory
    all_scripts = [f.name for f in SCRIPTS_DIR.glob("*.py") if f.is_file()]
    uncategorized = [s for s in all_scripts if s not in all_categorized]
    
    # Count statistics
    tools_count = len([s for s in PRODUCTION_TOOLS if (SCRIPTS_DIR / s).exists()])
    helpers_count = len([s for s in HELPER_SCRIPTS + CLEANUP_SCRIPTS if (SCRIPTS_DIR / s).exists()])
    archive_count = len([s for s in ARCHIVE_SCRIPTS if (SCRIPTS_DIR / s).exists()])
    mgmt_count = len([s for s in MGMT_COMMANDS_TO_MOVE if (MGMT_COMMANDS / s).exists()])
    
    print(f"\n📊 Summary:")
    print(f"  Total scripts in scripts/: {len(all_scripts)}")
    print(f"  → tools/: {tools_count}")
    print(f"  → helpers/: {helpers_count + mgmt_count}")
    print(f"  → archive/: {archive_count}")
    print(f"  ⚠️  Uncategorized: {len(uncategorized)}")
    
    print("\n📦 Production Tools → tools/ ({})".format(tools_count))
    for script in sorted(PRODUCTION_TOOLS):
        src = SCRIPTS_DIR / script
        if src.exists():
            print(f"  ✓ {script}")
        else:
            print(f"  ⚠️  {script} (not found)")
    
    print("\n🔧 Helper Scripts → helpers/ ({})".format(helpers_count + mgmt_count))
    for script in sorted(HELPER_SCRIPTS + CLEANUP_SCRIPTS):
        src = SCRIPTS_DIR / script
        if src.exists():
            print(f"  ✓ {script}")
        else:
            print(f"  ⚠️  {script} (not found)")
    
    print("\n📋 Management Commands → helpers/")
    for script in sorted(MGMT_COMMANDS_TO_MOVE):
        src = MGMT_COMMANDS / script
        if src.exists():
            print(f"  ✓ {script}")
        else:
            print(f"  ⚠️  {script} (not found)")
    
    print("\n🗄️  Obsolete Scripts → archive/ ({})".format(archive_count))
    for script in sorted(ARCHIVE_SCRIPTS):
        src = SCRIPTS_DIR / script
        if src.exists():
            print(f"  ✓ {script}")
        else:
            print(f"  ⚠️  {script} (not found)")
    
    if uncategorized:
        print(f"\n⚠️  UNCATEGORIZED SCRIPTS ({len(uncategorized)}):")
        print("    These scripts are NOT in any category and will NOT be moved:")
        for script in sorted(uncategorized):
            # Auto-suggest category based on name patterns
            suggestion = ""
            if any(x in script for x in ["cleanup", "clean_", "fix_", "auto_fix"]):
                suggestion = " → helpers/"
            elif any(x in script for x in ["init_", "setup_", "create_", "reset_"]):
                suggestion = " → helpers/"
            elif any(x in script for x in ["check_", "validate_"]):
                suggestion = " → archive/ or helpers/"
            elif "reorganize" in script:
                suggestion = " → helpers/ (this script)"
            else:
                suggestion = " → tools/ or archive/?"
            
            print(f"  ❓ {script}{suggestion}")
    
    print("\n" + "=" * 60)
    print("💡 To execute: python scripts/reorganize_scripts.py --execute")
    print("💡 Review uncategorized scripts and add them to appropriate lists")


if __name__ == "__main__":
    import sys
    
    if "--execute" not in sys.argv:
        print("⚠️  DRY RUN MODE - No files will be moved\n")
        dry_run()
        exit(0)
    
    print("🚀 EXECUTING - Files will be moved!\n")
    main()
