# Generated by Django 6.0 on 2025-12-11 12:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "domain_id",
                    models.CharField(
                        help_text="Unique identifier (e.g. 'novel', 'essay', 'movie')",
                        max_length=100,
                        unique=True,
                        verbose_name="Domain ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name (e.g. 'Novel Writing Workflow')",
                        max_length=200,
                        verbose_name="Display Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of this domain template",
                        verbose_name="Description",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("creative_writing", "Creative Writing"),
                            ("technical_writing", "Technical Writing"),
                            ("media_production", "Media Production"),
                            ("research", "Research & Analysis"),
                            ("business", "Business & Reports"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Domain category for organization",
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-file-text",
                        help_text="Bootstrap icon class (e.g. 'bi-file-text')",
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="UI color in hex format (e.g. #3B82F6)",
                        max_length=7,
                        verbose_name="Color",
                    ),
                ),
                (
                    "phases_config",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of phase definitions with actions",
                        verbose_name="Phases Configuration",
                    ),
                ),
                (
                    "required_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of required configuration fields",
                        verbose_name="Required Fields",
                    ),
                ),
                (
                    "optional_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of optional configuration fields",
                        verbose_name="Optional Fields",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        help_text="Template creator",
                        max_length=200,
                        verbose_name="Author",
                    ),
                ),
                (
                    "version",
                    models.CharField(default="1.0.0", max_length=20, verbose_name="Version"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive templates are hidden",
                        verbose_name="Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Custom Domain",
                "verbose_name_plural": "Custom Domains",
                "db_table": "genagent_custom_domains",
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"], name="genagent_cu_categor_3e096b_idx"
                    ),
                    models.Index(fields=["domain_id"], name="genagent_cu_domain__462cf8_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Phase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the workflow phase",
                        max_length=100,
                        verbose_name="Phase Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of what happens in this phase",
                        verbose_name="Description",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Execution order (phases run sequentially)",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive phases are skipped during execution",
                        verbose_name="Active",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="UI color in hex format (e.g. #3B82F6)",
                        max_length=7,
                        verbose_name="Color",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "GenAgent Phase",
                "verbose_name_plural": "GenAgent Phases",
                "db_table": "genagent_phases",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(fields=["order", "is_active"], name="genagent_ph_order_675106_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this action",
                        max_length=100,
                        verbose_name="Action Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="What this action does", verbose_name="Description"
                    ),
                ),
                (
                    "handler_class",
                    models.CharField(
                        help_text="Full Python path to handler class (e.g. apps.genagent.handlers.demo_handlers.WelcomeHandler)",
                        max_length=200,
                        verbose_name="Handler Class",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Execution order within the phase",
                        verbose_name="Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive actions are skipped",
                        verbose_name="Active",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON configuration passed to handler",
                        verbose_name="Configuration",
                    ),
                ),
                (
                    "timeout_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum execution time (optional)",
                        null=True,
                        verbose_name="Timeout (seconds)",
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of retries on failure",
                        verbose_name="Retry Count",
                    ),
                ),
                (
                    "continue_on_error",
                    models.BooleanField(
                        default=False,
                        help_text="If true, workflow continues even if this action fails",
                        verbose_name="Continue on Error",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="genagent.phase",
                        verbose_name="Phase",
                    ),
                ),
            ],
            options={
                "verbose_name": "GenAgent Action",
                "verbose_name_plural": "GenAgent Actions",
                "db_table": "genagent_actions",
                "ordering": ["phase__order", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Started At"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Finished At"),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True,
                        help_text="Execution time in seconds",
                        null=True,
                        verbose_name="Duration (seconds)",
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Context data passed to handler",
                        verbose_name="Input Data",
                    ),
                ),
                (
                    "output_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Result data returned by handler",
                        verbose_name="Output Data",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error details if execution failed",
                        verbose_name="Error Message",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="genagent.action",
                        verbose_name="Action",
                    ),
                ),
            ],
            options={
                "verbose_name": "GenAgent Execution Log",
                "verbose_name_plural": "GenAgent Execution Logs",
                "db_table": "genagent_execution_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "-created_at"], name="genagent_ex_action__cef494_idx"
                    ),
                    models.Index(
                        fields=["status", "-created_at"], name="genagent_ex_status_4af2ac_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["phase", "order", "is_active"], name="genagent_ac_phase_i_3cd7fa_idx"
            ),
        ),
    ]
