# Generated by Django 5.2.10 on 2026-01-23 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("trips", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("title", models.CharField(blank=True, max_length=200)),
                ("act", models.CharField(blank=True, max_length=20)),
                ("beat", models.CharField(blank=True, max_length=50)),
                (
                    "pacing",
                    models.CharField(
                        choices=[
                            ("action", "Action"),
                            ("emotional", "Emotional"),
                            ("reflective", "Reflektiv"),
                            ("atmospheric", "Atmosphärisch"),
                            ("romantic", "Romantisch"),
                            ("mysterious", "Mysteriös"),
                        ],
                        default="atmospheric",
                        max_length=20,
                    ),
                ),
                ("story_location", models.CharField(blank=True, max_length=200)),
                ("reader_location", models.CharField(blank=True, max_length=200)),
                ("reading_date", models.DateField(blank=True, null=True)),
                ("content", models.TextField(blank=True)),
                ("word_count", models.PositiveIntegerField(default=0)),
                ("target_words", models.PositiveIntegerField(default=3000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Wartend"),
                            ("generating", "Wird generiert"),
                            ("completed", "Fertig"),
                            ("failed", "Fehlgeschlagen"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("generation_prompt", models.TextField(blank=True)),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kapitel",
                "verbose_name_plural": "Kapitel",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="ReadingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chapters_completed", models.PositiveIntegerField(default=0)),
                ("words_read", models.PositiveIntegerField(default=0)),
                ("total_reading_minutes", models.PositiveIntegerField(default=0)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("bookmarks", models.JSONField(blank=True, default=list)),
                (
                    "current_chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stories.chapter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesefortschritt",
                "verbose_name_plural": "Lesefortschritte",
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("romance", "Romance"),
                            ("thriller", "Thriller"),
                            ("mystery", "Mystery"),
                            ("romantic_suspense", "Romantic Suspense"),
                            ("cozy_mystery", "Cozy Mystery"),
                            ("fantasy", "Fantasy"),
                            ("adventure", "Adventure"),
                        ],
                        default="romantic_suspense",
                        max_length=30,
                    ),
                ),
                (
                    "spice_level",
                    models.CharField(
                        choices=[
                            ("none", "Keine expliziten Szenen"),
                            ("mild", "Angedeutete Intimität"),
                            ("moderate", "Sinnliche Szenen"),
                            ("spicy", "Explizite Szenen"),
                        ],
                        default="mild",
                        max_length=20,
                    ),
                ),
                (
                    "ending_type",
                    models.CharField(
                        choices=[
                            ("happy", "Happy End"),
                            ("sad", "Trauriges Ende"),
                            ("open", "Offenes Ende"),
                            ("surprise", "Überraschung"),
                        ],
                        default="happy",
                        max_length=20,
                    ),
                ),
                (
                    "triggers_avoid",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Themen die vermieden werden sollen",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Wartend"),
                            ("generating", "Wird generiert"),
                            ("completed", "Fertig"),
                            ("failed", "Fehlgeschlagen"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("generation_started", models.DateTimeField(blank=True, null=True)),
                ("generation_completed", models.DateTimeField(blank=True, null=True)),
                ("generation_error", models.TextField(blank=True)),
                ("total_chapters", models.PositiveIntegerField(default=0)),
                ("total_words", models.PositiveIntegerField(default=0)),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                (
                    "generation_cost_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story",
                        to="trips.trip",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Story",
                "verbose_name_plural": "Stories",
                "ordering": ["-created_at"],
            },
        ),
    ]
