# Generated by Django 5.2.10 on 2026-01-23 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stories", "0001_initial"),
        ("worlds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="user_world",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stories",
                to="worlds.userworld",
            ),
        ),
        migrations.AddField(
            model_name="readingprogress",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reading_progress",
                to="stories.story",
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="stories.story",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="readingprogress",
            unique_together={("user", "story")},
        ),
        migrations.AlterUniqueTogether(
            name="chapter",
            unique_together={("story", "number")},
        ),
    ]
