"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add packages directory to Python path
sys.path.insert(0, str(BASE_DIR / "packages"))

# Load environment variables from .env file
try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / ".env")
except ImportError:
    # Fallback: Load .env manually if python-dotenv is not installed
    env_file = BASE_DIR / ".env"
    if env_file.exists():
        with open(env_file) as f:
            for line in f:
                if line.strip() and not line.startswith("#") and "=" in line:
                    key, value = line.strip().split("=", 1)
                    os.environ.setdefault(key, value)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-q9l)2wxgz*_dj1tp_s$zn2!vti^8b_&%!42dvp7uankwcjyk7y"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "*"]

# CSRF Settings (for development and Cascade browser preview)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://127.0.0.1:45234",  # Cascade browser preview proxy
    "http://localhost:45234",
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",  # For intcomma, naturaltime, etc.
    # BF Agent Apps
    "apps.core",
    "apps.bfagent",
    "apps.writing_hub.apps.WritingHubConfig",  # Writing Hub mit Lookup Tables
    "apps.presentation_studio",
    "apps.genagent",
    "apps.control_center",
    "apps.api.apps.ApiConfig",  # MCP Orchestration API
    "apps.ui_hub.apps.UiHubConfig",  # UI Hub - HTMX Guardrails
    "apps.dlm_hub.apps.DlmHubConfig",  # DLM Hub
    "apps.media_hub.apps.MediaHubConfig",  # Media Hub - Production Pipeline
    "apps.graph_core.apps.GraphCoreConfig",  # Graph Core - Workflow Orchestration
    # MCP Integration
    "bfagent.mcp.apps.MCPConfig",  # MCP SQLite Server
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "apps.core.middleware.auto_healing.AutoHealingMiddleware",  # Auto-healing
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
            BASE_DIR / "apps" / "graph_core" / "templates",  # Graph Core templates
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "debug": True,  # Enable template debugging and disable caching
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Dynamic Navigation from Database
                "apps.control_center.context_processors_unified.unified_navigation",
                # Available Domains for Bug/Feature Reporter
                "apps.control_center.context_processors_unified.available_domains_context",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "bfagent_dev"),
        "USER": os.environ.get("POSTGRES_USER", "bfagent"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "bfagent_dev_2024"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (User uploaded content, generated images)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =============================================================================
# DYNAMIC NAVIGATION CONFIGURATION
# =============================================================================
USE_UNIFIED_NAVIGATION = True  # Enable 100% DB-driven navigation

NAVIGATION_FEATURES = {
    "USE_NEW_SCHEMA": True,  # Use NavigationSection/NavigationItem (not DomainSection)
    "DEBUG_NAVIGATION": False,  # Enable debug output for navigation helpers
}

# =============================================================================
# CELERY CONFIGURATION
# =============================================================================
# Celery settings (for async tasks like auto-illustration)

CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes max per task
CELERY_RESULT_EXPIRES = 3600  # Results expire after 1 hour

# Task routing (optional - for organizing tasks)
CELERY_TASK_ROUTES = {
    "apps.bfagent.tasks.auto_illustrate_chapter_task": {"queue": "illustration"},
}

# Worker settings
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Process one task at a time
CELERY_WORKER_MAX_TASKS_PER_CHILD = 50  # Restart worker after 50 tasks (memory cleanup)

# =============================================================================
# N8N CONFIGURATION (Hostinger)
# =============================================================================
N8N_BASE_URL = os.environ.get("N8N_BASE_URL", "https://n8n.srv1154685.hstgr.cloud")
N8N_API_KEY = os.environ.get("N8N_API_KEY", "")
N8N_WEBHOOK_URL = os.environ.get("N8N_WEBHOOK_URL", f"{N8N_BASE_URL}/webhook/")

# =============================================================================
# MCP SQLITE SERVER CONFIGURATION
# =============================================================================
MCP_READ_ONLY = False  # Set to True in production for safety
MCP_POOL_SIZE = 10  # Database connection pool size
MCP_AUDIT_ENABLED = True  # Enable query audit logging
MCP_METRICS_ENABLED = True  # Enable performance metrics

# =============================================================================
# SENTRY INTEGRATION (Error Tracking & AI Analysis)
# =============================================================================
SENTRY_DSN = os.environ.get("SENTRY_DSN", "")  # Set in .env file
SENTRY_ENVIRONMENT = os.environ.get("SENTRY_ENVIRONMENT", "development")
SENTRY_RELEASE = os.environ.get("SENTRY_RELEASE", None)
SENTRY_TRACES_SAMPLE_RATE = float(os.environ.get("SENTRY_TRACES_SAMPLE_RATE", "1.0"))
SENTRY_PROFILES_SAMPLE_RATE = float(os.environ.get("SENTRY_PROFILES_SAMPLE_RATE", "1.0"))

# Sentry will auto-initialize if DSN is set
# See: apps/bfagent/services/sentry_integration.py

# =============================================================================
# GRAFANA INTEGRATION (Monitoring & Observability)
# =============================================================================
GRAFANA_URL = os.environ.get("GRAFANA_URL", "")  # e.g., https://YOUR_ORG.grafana.net
GRAFANA_TOKEN = os.environ.get("GRAFANA_TOKEN", "")  # Service Account Token
GRAFANA_ORG_ID = os.environ.get("GRAFANA_ORG_ID", "")  # Optional org ID

# Grafana will auto-initialize if URL and TOKEN are set
# See: apps/bfagent/services/grafana_integration.py

# =============================================================================
# LOCAL DEVELOPMENT OVERRIDE (automatically loads settings_local.py if exists)
# =============================================================================
try:
    from .settings_local import *

    print("📝 Loaded local settings override")
except ImportError:
    pass
