"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / ".env")
except ImportError:
    env_file = BASE_DIR / ".env"
    if env_file.exists():
        with open(env_file) as f:
            for line in f:
                if line.strip() and not line.startswith("#") and "=" in line:
                    key, value = line.strip().split("=", 1)
                    os.environ.setdefault(key, value)


# =============================================================================
# SECURITY SETTINGS
# =============================================================================

SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-q9l)2wxgz*_dj1tp_s$zn2!vti^8b_&%!42dvp7uankwcjyk7y"
)

# DEBUG: Default to False in production!
DEBUG = os.environ.get("DEBUG", "False").lower() in ("true", "1", "yes")

# IMMEDIATE DEBUG OUTPUT (to stderr to avoid buffering)
import sys
sys.stderr.write(f"\n{'='*60}\n")
sys.stderr.write(f"[SETTINGS.PY LOADED] DEBUG ENV VAR: {os.environ.get('DEBUG', 'NOT SET')}\n")
sys.stderr.write(f"[SETTINGS.PY LOADED] DEBUG VALUE: {DEBUG}\n")
sys.stderr.write(f"{'='*60}\n\n")
sys.stderr.flush()

# =============================================================================
# ALLOWED_HOSTS Configuration
# =============================================================================
if DEBUG:
    # Development: Allow localhost and Docker internal
    ALLOWED_HOSTS = [
        "localhost",
        "127.0.0.1",
        "0.0.0.0",
        "[::1]",
        "host.docker.internal",
    ]
    # Add custom hosts from ENV for development
    _extra_hosts = os.environ.get("ALLOWED_HOSTS", "")
    if _extra_hosts:
        ALLOWED_HOSTS.extend([h.strip() for h in _extra_hosts.split(",") if h.strip()])
else:
    # Production: Load from ALLOWED_HOSTS environment variable (REQUIRED!)
    _env_hosts = os.environ.get("ALLOWED_HOSTS", "")
    if _env_hosts:
        ALLOWED_HOSTS = [h.strip() for h in _env_hosts.split(",") if h.strip()]
    else:
        # Fallback: minimal localhost only (should never happen in production)
        ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
        print("[ERROR] No ALLOWED_HOSTS configured for production! Set ALLOWED_HOSTS env var.")

# Remove duplicates while preserving order
ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))

# IMMEDIATE DEBUG OUTPUT (to stderr)
sys.stderr.write(f"[SETTINGS.PY LOADED] ALLOWED_HOSTS: {ALLOWED_HOSTS}\n")
sys.stderr.write(f"{'='*60}\n\n")
sys.stderr.flush()

# Debug output
print(f"[Django] DEBUG={DEBUG}")
print(f"[Django] ALLOWED_HOSTS={ALLOWED_HOSTS}")

# =============================================================================
# Nginx Reverse Proxy Configuration (Hetzner Deployment)
# =============================================================================
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# =============================================================================
# CSRF Settings
# =============================================================================
if DEBUG:
    # Development: Allow localhost with various ports
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "http://localhost",
        "http://127.0.0.1",
    ]
    CSRF_COOKIE_DOMAIN = None
    CSRF_COOKIE_SECURE = False
else:
    # Production: Build CSRF_TRUSTED_ORIGINS from ALLOWED_HOSTS
    CSRF_TRUSTED_ORIGINS = []
    for host in ALLOWED_HOSTS:
        if host not in ["localhost", "127.0.0.1", "0.0.0.0", "[::1]"]:
            # Add both HTTP and HTTPS for production domains
            CSRF_TRUSTED_ORIGINS.append(f"http://{host}")
            CSRF_TRUSTED_ORIGINS.append(f"https://{host}")
    # Remove duplicates
    CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))
    print(f"[Django] CSRF_TRUSTED_ORIGINS={CSRF_TRUSTED_ORIGINS}")

# =============================================================================
# Application definition
# =============================================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # BF Agent Apps
    "apps.core",
    "apps.workflow_system",
    "apps.writing_hub.apps.WritingHubConfig",
    "apps.checklist_system.apps.ChecklistSystemConfig",
    "apps.bfagent",
    "apps.presentation_studio",
    "apps.genagent",
    "apps.control_center",
    "apps.format_hub",
    "apps.expert_hub.apps.ExpertHubConfig",
    "apps.medtrans",
    # Compliance Framework
    "apps.compliance_core.apps.ComplianceCoreConfig",
    "apps.dsb.apps.DsbConfig",
    # Analysis & Research
    "apps.cad_analysis.apps.CadAnalysisConfig",
    "apps.research.apps.ResearchConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "debug": DEBUG,
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.bfagent.context_processors.sidebar_navigation",
                "apps.bfagent.context_processors.theme_context",
                "apps.control_center.context_processors.dynamic_navigation_context",
                "apps.control_center.context_processors.control_center_context",
                "apps.control_center.context_processors_unified.unified_navigation",
                "apps.control_center.context_processors_unified.active_domain_context",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# =============================================================================
# Database
# =============================================================================
DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# =============================================================================
# Password validation
# =============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# =============================================================================
# Internationalization
# =============================================================================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# =============================================================================
# Static files
# =============================================================================
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# =============================================================================
# Default primary key
# =============================================================================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =============================================================================
# CELERY CONFIGURATION
# =============================================================================
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_RESULT_EXPIRES = 3600

CELERY_TASK_ROUTES = {
    "apps.bfagent.tasks.auto_illustrate_chapter_task": {"queue": "illustration"},
}

CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 50

# =============================================================================
# NAVIGATION SYSTEM - FEATURE FLAGS
# =============================================================================
NAVIGATION_FEATURES = {
    "USE_NEW_SCHEMA": True,
    "ENABLE_DUAL_MODE": True,
    "USE_DOMAIN_FILTERING": True,
    "USE_NEW_PERMISSIONS": False,
    "DEBUG_NAVIGATION": DEBUG,
    "FALLBACK_TO_STATIC": True,
}

USE_UNIFIED_NAVIGATION = True

# =============================================================================
# RESEARCH DOMAIN - Configuration
# =============================================================================
RESEARCH_DOMAIN = {
    "DEFAULT_DEPTH": "standard",
    "DEFAULT_SOURCES": ["web", "academic"],
    "CACHE_TTL": 3600,
    "MAX_RESULTS_PER_SOURCE": 10,
    "ENABLE_RAG": False,
    "ENABLE_SCRAPERS": False,
}

# n8n Integration
N8N_BASE_URL = os.getenv("N8N_BASE_URL", "https://n8n.srv1154685.hstgr.cloud")
N8N_WEBHOOK_PATH = "/webhook/research-execute"

# API Keys
BRAVE_API_KEY = os.getenv("BRAVE_API_KEY")
TOGETHER_API_KEY = os.getenv("TOGETHER_API_KEY")
SERPER_API_KEY = os.getenv("SERPER_API_KEY")
EXA_API_KEY = os.getenv("EXA_API_KEY")
FIRECRAWL_API_KEY = os.getenv("FIRECRAWL_API_KEY")
CLAUDE_API_KEY = os.getenv("CLAUDE-API-KEY")
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
SEMANTIC_SCHOLAR_API_KEY = None

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}

# Add file logging only if not in Docker (where we have no write permissions)
if not os.getenv("DOCKER_CONTAINER") and DEBUG:
    LOGGING["handlers"]["file"] = {
        "class": "logging.FileHandler",
        "filename": BASE_DIR / "logs" / "django.log",
        "formatter": "verbose",
    }
    LOGGING["root"]["handlers"].append("file")
    LOGGING["loggers"]["django"]["handlers"].append("file")

# =============================================================================
# PRODUCTION SECURITY
# =============================================================================
if not DEBUG:
    # Vorsicht: SSL Redirect kann Health Checks stören
    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "False").lower() == "true"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
