"""
Test script for LLM Processing Handler and Markdown File Output Handler

This tests the complete story generation pipeline with real LLM integration.
"""

import os
import sys
import django

# Setup Django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.development")
django.setup()

from apps.bfagent.models import BookProjects, Llms
from apps.bfagent.services.handlers.registries import (
    InputHandlerRegistry,
    ProcessingHandlerRegistry,
    OutputHandlerRegistry
)

print("=" * 70)
print("🧪 LLM PROCESSING HANDLER & MARKDOWN FILE WRITER TEST")
print("=" * 70)
print()

# Show registered handlers
print("📋 Registered Handlers:")
print(f"   Input: {InputHandlerRegistry.list_handlers()}")
print(f"   Processing: {ProcessingHandlerRegistry.list_handlers()}")
print(f"   Output: {OutputHandlerRegistry.list_handlers()}")
print()

# Get test data
print("🔍 Loading test data...")
project = BookProjects.objects.first()
llm = Llms.objects.filter(is_active=True).first()

if not project:
    print("❌ No project found in database")
    sys.exit(1)

if not llm:
    print("❌ No active LLM found in database")
    sys.exit(1)

print(f"   📚 Project: {project.title}")
print(f"   🤖 LLM: {llm.llm_name} ({llm.provider})")
print()

# Test 1: LLM Processing Handler (without actual API call)
print("=" * 70)
print("🧪 TEST 1: LLM Processing Handler (Mock)")
print("=" * 70)

try:
    # Get handler class from registry
    LLMHandler = ProcessingHandlerRegistry.get("llm_processor")
    
    # Create instance with config
    llm_handler = LLMHandler(
        config={
            "llm_id": llm.id,
            "temperature": 0.7,
            "max_tokens": 500
        }
    )
    
    print(f"✅ Handler created: {llm_handler.handler_name}")
    print(f"   Config: llm_id={llm.id}, temp=0.7, max_tokens=500")
    print(f"   LLM: {llm.llm_name} ({llm.provider})")
    
    # Test with mock data (don't actually call API in test)
    print("   ⚠️  Skipping actual API call (requires API key configuration)")
    print()
    
except Exception as e:
    print(f"❌ Error: {e}")
    import traceback
    traceback.print_exc()
    print()

# Test 2: Markdown File Output Handler
print("=" * 70)
print("🧪 TEST 2: Markdown File Output Handler")
print("=" * 70)

try:
    # Get handler class from registry
    MDHandler = OutputHandlerRegistry.get("markdown_file_writer")
    
    # Create instance with config
    md_handler = MDHandler(
        config={
            "output_dir": "stories/generated/",
            "filename_template": "test_{project_id}_{timestamp}.md",
            "create_backup": True,
            "add_frontmatter": True
        }
    )
    
    print(f"✅ Handler created: {md_handler.handler_name}")
    print()
    
    # Test with mock generated content
    mock_content = """# {project_title}

## Chapter 1: The Beginning

Once upon a time, in a world not so different from our own...

This is a test story generated by the BF Agent Pipeline System.
It demonstrates the markdown file writing capabilities.

## Chapter 2: The Middle

The story continues with exciting developments...

## Chapter 3: The End

And they lived happily ever after.
""".replace("{project_title}", project.title)
    
    processed_data = {
        "generated_content": mock_content,
        "llm_name": llm.llm_name,
        "tokens_used": 150,
        "generation_cost": 0.005
    }
    
    context = {
        "project": project,
        "action_name": "test_story_generation"
    }
    
    result = md_handler.handle(processed_data, context)
    
    print("📤 File Writing Result:")
    print(f"   ✅ Status: {result['status']}")
    print(f"   📁 File: {result['filename']}")
    print(f"   📍 Path: {result['file_path']}")
    print(f"   📏 Size: {result['file_size']} bytes")
    print(f"   💾 Backup Created: {result['backup_created']}")
    print()
    print(f"📄 Content Preview:")
    print(f"   {result['content_preview']}")
    print()
    
except Exception as e:
    print(f"❌ Error: {e}")
    import traceback
    traceback.print_exc()
    print()

# Test 3: Complete Pipeline Configuration (Example)
print("=" * 70)
print("📋 EXAMPLE: Complete Story Generation Pipeline Config")
print("=" * 70)

pipeline_config = {
    "name": "complete_story_generator",
    "description": "Generate complete story from project metadata",
    "stages": {
        "input": [
            {
                "handler": "project_fields",
                "config": {
                    "mode": "all"  # Auto-discover all fields
                }
            }
        ],
        "processing": [
            {
                "handler": "template_renderer",
                "config": {
                    "template": """
You are a creative story writer. Based on the following project details, write a complete story:

Title: {{ title }}
Genre: {{ genre }}
Description: {{ description }}
Setting: {{ setting_time }}, {{ setting_location }}
Main Conflict: {{ main_conflict }}
Stakes: {{ stakes }}

Write a complete story (5000-10000 words) with:
- Multiple chapters
- Rich character development
- Engaging dialogue
- Vivid descriptions
- Satisfying conclusion

Format the output as markdown with chapter headings.
"""
                }
            },
            {
                "handler": "llm_processor",
                "config": {
                    "llm_id": llm.id,
                    "temperature": 0.8,
                    "max_tokens": 15000,
                    "fallback_llm_id": None
                }
            }
        ],
        "output": [
            {
                "handler": "markdown_file_writer",
                "config": {
                    "output_dir": "stories/generated/",
                    "filename_template": "{project_id}_{title}_{timestamp}.md",
                    "create_backup": True,
                    "add_frontmatter": True
                }
            }
        ]
    }
}

print(f"📝 Pipeline: {pipeline_config['name']}")
print(f"   {pipeline_config['description']}")
print()
print(f"   📥 Input Handlers: {len(pipeline_config['stages']['input'])}")
for handler in pipeline_config['stages']['input']:
    print(f"      • {handler['handler']}")
print()
print(f"   ⚙️  Processing Handlers: {len(pipeline_config['stages']['processing'])}")
for handler in pipeline_config['stages']['processing']:
    print(f"      • {handler['handler']}")
print()
print(f"   📤 Output Handlers: {len(pipeline_config['stages']['output'])}")
for handler in pipeline_config['stages']['output']:
    print(f"      • {handler['handler']}")
print()

print("=" * 70)
print("✅ ALL TESTS COMPLETE!")
print("=" * 70)
print()
print("💡 Next Steps:")
print("   1. Configure LLM API keys in database")
print("   2. Create ActionTemplate with this pipeline config")
print("   3. Test with real LLM generation")
print("   4. Add benchmarking for multiple LLMs")
print()
