# Generated by Django 6.0 on 2025-12-11 12:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IFCModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1, verbose_name="Version")),
                (
                    "ifc_file",
                    models.FileField(upload_to="ifc_models/%Y/%m/", verbose_name="IFC Datei"),
                ),
                (
                    "xkt_file",
                    models.FileField(
                        blank=True,
                        upload_to="ifc_models/%Y/%m/",
                        verbose_name="XKT Datei (3D Viewer)",
                    ),
                ),
                (
                    "ifc_schema",
                    models.CharField(blank=True, max_length=20, verbose_name="IFC Schema"),
                ),
                (
                    "application",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Erstellungs-Software"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Wird hochgeladen"),
                            ("processing", "Wird verarbeitet"),
                            ("ready", "Bereit"),
                            ("error", "Fehler"),
                        ],
                        default="uploading",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Fehlermeldung")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "IFC Modell",
                "verbose_name_plural": "IFC Modelle",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("ifc_guid", models.CharField(max_length=36, verbose_name="IFC GUID")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "code",
                    models.CharField(blank=True, max_length=20, verbose_name="Kurzbezeichnung"),
                ),
                ("elevation", models.FloatField(default=0, verbose_name="Höhe (m)")),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "ifc_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floors",
                        to="cad_hub.ifcmodel",
                        verbose_name="IFC Modell",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geschoss",
                "verbose_name_plural": "Geschosse",
                "ordering": ["sort_order", "elevation"],
            },
        ),
        migrations.CreateModel(
            name="IFCProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Same UUID as IFC MCP Backend",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Projektname")),
                (
                    "mcp_project_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Reference to IFC MCP Backend",
                        null=True,
                        verbose_name="IFC MCP Projekt-ID",
                    ),
                ),
                (
                    "cached_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cached data from IFC MCP API",
                        verbose_name="Cached Project Data",
                    ),
                ),
                (
                    "cached_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Cache Timestamp"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="UI User",
                    ),
                ),
            ],
            options={
                "verbose_name": "IFC Projekt (Cache)",
                "verbose_name_plural": "IFC Projekte (Cache)",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="ifcmodel",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="cad_hub.ifcproject",
                verbose_name="Projekt",
            ),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("ifc_guid", models.CharField(max_length=36, verbose_name="IFC GUID")),
                ("number", models.CharField(max_length=20, verbose_name="Raumnummer")),
                ("name", models.CharField(max_length=100, verbose_name="Raumname")),
                (
                    "long_name",
                    models.CharField(blank=True, max_length=255, verbose_name="Langname"),
                ),
                ("area", models.FloatField(default=0, verbose_name="Fläche (m²)")),
                ("height", models.FloatField(default=0, verbose_name="Höhe (m)")),
                ("volume", models.FloatField(default=0, verbose_name="Volumen (m³)")),
                ("perimeter", models.FloatField(default=0, verbose_name="Umfang (m)")),
                (
                    "usage_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NF1.1", "NF 1.1 - Wohnen/Aufenthalt"),
                            ("NF1.2", "NF 1.2 - Büroarbeit"),
                            ("NF1.3", "NF 1.3 - Produktion"),
                            ("NF2", "NF 2 - Büroflächen"),
                            ("NF3", "NF 3 - Lager/Verteilen"),
                            ("NF4", "NF 4 - Bildung/Kultur"),
                            ("NF5", "NF 5 - Heilen/Pflegen"),
                            ("NF6", "NF 6 - Sonstige"),
                            ("TF7", "TF 7 - Technikflächen"),
                            ("VF8", "VF 8 - Verkehrsflächen"),
                        ],
                        max_length=10,
                        verbose_name="Nutzungsart (DIN 277)",
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="cad_hub.floor",
                        verbose_name="Geschoss",
                    ),
                ),
                (
                    "ifc_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="cad_hub.ifcmodel",
                        verbose_name="IFC Modell",
                    ),
                ),
            ],
            options={
                "verbose_name": "Raum",
                "verbose_name_plural": "Räume",
                "ordering": ["floor__sort_order", "number"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="ifcmodel",
            unique_together={("project", "version")},
        ),
    ]
