# Generated by Django 6.0 on 2025-12-11 13:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cad_hub", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Door",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("ifc_guid", models.CharField(max_length=36, verbose_name="IFC GUID")),
                ("number", models.CharField(blank=True, max_length=50, verbose_name="Nummer")),
                ("name", models.CharField(blank=True, max_length=100, verbose_name="Name")),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Breite (m)",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Höhe (m)",
                    ),
                ),
                ("door_type", models.CharField(blank=True, max_length=50, verbose_name="Türtyp")),
                ("material", models.CharField(blank=True, max_length=100, verbose_name="Material")),
                (
                    "fire_rating",
                    models.CharField(blank=True, max_length=20, verbose_name="Feuerwiderstand"),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doors",
                        to="cad_hub.floor",
                        verbose_name="Geschoss",
                    ),
                ),
                (
                    "from_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doors_from",
                        to="cad_hub.room",
                        verbose_name="Von Raum",
                    ),
                ),
                (
                    "ifc_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doors",
                        to="cad_hub.ifcmodel",
                        verbose_name="IFC Modell",
                    ),
                ),
                (
                    "to_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doors_to",
                        to="cad_hub.room",
                        verbose_name="Nach Raum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tür",
                "verbose_name_plural": "Türen",
                "db_table": "cad_hub_door",
                "ordering": ["floor__sort_order", "number"],
            },
        ),
        migrations.CreateModel(
            name="Slab",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("ifc_guid", models.CharField(max_length=36, verbose_name="IFC GUID")),
                ("name", models.CharField(blank=True, max_length=100, verbose_name="Name")),
                (
                    "slab_type",
                    models.CharField(
                        choices=[
                            ("FLOOR", "Geschossdecke"),
                            ("ROOF", "Dach"),
                            ("BASESLAB", "Bodenplatte"),
                            ("LANDING", "Podest"),
                        ],
                        default="FLOOR",
                        max_length=20,
                        verbose_name="Typ",
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Fläche (m²)",
                    ),
                ),
                (
                    "thickness",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Dicke (m)",
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Volumen (m³)",
                    ),
                ),
                (
                    "perimeter",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Umfang (m)",
                    ),
                ),
                ("material", models.CharField(blank=True, max_length=100, verbose_name="Material")),
                (
                    "floor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slabs",
                        to="cad_hub.floor",
                        verbose_name="Geschoss",
                    ),
                ),
                (
                    "ifc_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slabs",
                        to="cad_hub.ifcmodel",
                        verbose_name="IFC Modell",
                    ),
                ),
            ],
            options={
                "verbose_name": "Decke/Platte",
                "verbose_name_plural": "Decken/Platten",
                "db_table": "cad_hub_slab",
                "ordering": ["floor__sort_order", "slab_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Wall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("ifc_guid", models.CharField(max_length=36, verbose_name="IFC GUID")),
                ("name", models.CharField(blank=True, max_length=100, verbose_name="Name")),
                (
                    "length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Länge (m)",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Höhe (m)",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Dicke (m)",
                    ),
                ),
                (
                    "gross_area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Bruttofläche (m²)",
                    ),
                ),
                (
                    "net_area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Nettofläche (m²)",
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Volumen (m³)",
                    ),
                ),
                ("is_external", models.BooleanField(default=False, verbose_name="Außenwand")),
                ("is_load_bearing", models.BooleanField(default=False, verbose_name="Tragend")),
                ("material", models.CharField(blank=True, max_length=100, verbose_name="Material")),
                (
                    "floor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="walls",
                        to="cad_hub.floor",
                        verbose_name="Geschoss",
                    ),
                ),
                (
                    "ifc_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="walls",
                        to="cad_hub.ifcmodel",
                        verbose_name="IFC Modell",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wand",
                "verbose_name_plural": "Wände",
                "db_table": "cad_hub_wall",
                "ordering": ["floor__sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Window",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("ifc_guid", models.CharField(max_length=36, verbose_name="IFC GUID")),
                ("number", models.CharField(blank=True, max_length=50, verbose_name="Nummer")),
                ("name", models.CharField(blank=True, max_length=100, verbose_name="Name")),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Breite (m)",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Höhe (m)",
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Fläche (m²)",
                    ),
                ),
                (
                    "wall_position",
                    models.CharField(blank=True, max_length=50, verbose_name="Wandposition"),
                ),
                (
                    "elevation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Höhe (m)",
                    ),
                ),
                ("material", models.CharField(blank=True, max_length=100, verbose_name="Material")),
                (
                    "glazing_type",
                    models.CharField(blank=True, max_length=100, verbose_name="Verglasungstyp"),
                ),
                (
                    "u_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="U-Wert (W/m²K)",
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="windows",
                        to="cad_hub.floor",
                        verbose_name="Geschoss",
                    ),
                ),
                (
                    "ifc_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="windows",
                        to="cad_hub.ifcmodel",
                        verbose_name="IFC Modell",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="windows",
                        to="cad_hub.room",
                        verbose_name="Raum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fenster",
                "verbose_name_plural": "Fenster",
                "db_table": "cad_hub_window",
                "ordering": ["floor__sort_order", "number"],
            },
        ),
    ]
