# Generated by Django 6.0 on 2025-12-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cad_hub", "0002_door_slab_wall_window"),
    ]

    operations = [
        migrations.AddField(
            model_name="door",
            name="properties",
            field=models.JSONField(blank=True, default=dict, verbose_name="IFC Properties"),
        ),
        migrations.AddField(
            model_name="wall",
            name="properties",
            field=models.JSONField(blank=True, default=dict, verbose_name="IFC Properties"),
        ),
        migrations.AddField(
            model_name="window",
            name="properties",
            field=models.JSONField(blank=True, default=dict, verbose_name="IFC Properties"),
        ),
    ]
