# Generated by Django 6.0 on 2025-12-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cad_hub", "0003_door_properties_wall_properties_window_properties"),
    ]

    operations = [
        migrations.AddField(
            model_name="slab",
            name="properties",
            field=models.JSONField(blank=True, default=dict, verbose_name="IFC Properties"),
        ),
    ]
