# Generated by Django 5.2.6 on 2025-12-19 07:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_hub', '0005_avb_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandschutzPruefung',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projekt_name', models.CharField(max_length=200)),
                ('projekt_id', models.UUIDField(blank=True, null=True)),
                ('plan_datei', models.FileField(blank=True, null=True, upload_to='brandschutz/plaene/')),
                ('plan_name', models.CharField(blank=True, max_length=200)),
                ('etage', models.CharField(blank=True, default='EG', max_length=50)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('in_bearbeitung', 'In Bearbeitung'), ('geprueft', 'Geprüft'), ('maengel', 'Mängel festgestellt'), ('freigegeben', 'Freigegeben'), ('abgelehnt', 'Abgelehnt')], default='offen', max_length=50)),
                ('analyse_ergebnis', models.JSONField(blank=True, null=True)),
                ('flaeche_m2', models.FloatField(default=0, help_text='Geprüfte Fläche')),
                ('anzahl_fluchtwege', models.IntegerField(default=0)),
                ('anzahl_feuerloescher', models.IntegerField(default=0)),
                ('anzahl_rauchmelder', models.IntegerField(default=0)),
                ('anzahl_ex_bereiche', models.IntegerField(default=0)),
                ('maengel', models.JSONField(blank=True, default=list, null=True)),
                ('warnungen', models.JSONField(blank=True, default=list, null=True)),
                ('anzahl_maengel', models.IntegerField(default=0)),
                ('vorgeschlagene_symbole', models.JSONField(blank=True, default=list, null=True)),
                ('eingefuegte_symbole', models.JSONField(blank=True, default=list, null=True)),
                ('pruefer', models.CharField(blank=True, max_length=200)),
                ('geprueft_am', models.DateTimeField(blank=True, null=True)),
                ('freigegeben_von', models.CharField(blank=True, max_length=200)),
                ('freigegeben_am', models.DateTimeField(blank=True, null=True)),
                ('bemerkungen', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brandschutz-Prüfung',
                'verbose_name_plural': 'Brandschutz-Prüfungen',
                'db_table': 'cad_hub_brandschutz_pruefung',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrandschutzRegelwerk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kuerzel', models.CharField(help_text='z.B. ASR_A2_2', max_length=50, unique=True)),
                ('name', models.CharField(help_text='z.B. ASR A2.2 - Feuerlöscher', max_length=200)),
                ('typ', models.CharField(choices=[('asr', 'Arbeitsstättenregel'), ('din', 'DIN-Norm'), ('lbo', 'Landesbauordnung'), ('mbo', 'Musterbauordnung'), ('vstaettvo', 'Versammlungsstättenverordnung'), ('indbauril', 'Industriebaurichtlinie'), ('sonstige', 'Sonstige')], default='din', max_length=20)),
                ('kategorien', models.JSONField(default=list, help_text='Anwendbare Kategorien')),
                ('regeln', models.JSONField(default=dict, help_text='Prüfregeln als JSON')),
                ('url', models.URLField(blank=True)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('gueltig_ab', models.DateField(blank=True, null=True)),
                ('aktiv', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brandschutz-Regelwerk',
                'verbose_name_plural': 'Brandschutz-Regelwerke',
                'db_table': 'cad_hub_brandschutz_regelwerk',
                'ordering': ['typ', 'kuerzel'],
            },
        ),
        migrations.CreateModel(
            name='BrandschutzSymbol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name des Symbols', max_length=100)),
                ('din_nummer', models.CharField(help_text='z.B. F001, E001', max_length=20)),
                ('kategorie', models.CharField(choices=[('fluchtweg', 'Fluchtweg'), ('notausgang', 'Notausgang'), ('brandabschnitt', 'Brandabschnitt'), ('feuerloescher', 'Feuerlöscher'), ('rauchmelder', 'Rauchmelder'), ('sprinkler', 'Sprinkler'), ('rwa', 'RWA'), ('ex_zone', 'Ex-Zone'), ('brandmelder', 'Brandmelder'), ('hydrant', 'Hydrant')], default='feuerloescher', max_length=50)),
                ('beschreibung', models.TextField(blank=True)),
                ('block_dxf', models.FileField(blank=True, null=True, upload_to='brandschutz/symbole/')),
                ('block_json', models.JSONField(blank=True, help_text='Block-Definition als JSON', null=True)),
                ('farbe', models.CharField(default='rot', help_text='rot, grün, gelb, blau', max_length=20)),
                ('groesse_mm', models.FloatField(default=200, help_text='Standard-Größe in mm')),
                ('regelwerk', models.CharField(blank=True, help_text='z.B. ASR A2.2', max_length=100)),
                ('aktiv', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brandschutz-Symbol',
                'verbose_name_plural': 'Brandschutz-Symbole',
                'db_table': 'cad_hub_brandschutz_symbol',
                'ordering': ['kategorie', 'din_nummer'],
            },
        ),
        migrations.CreateModel(
            name='BrandschutzMangel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kategorie', models.CharField(choices=[('fluchtweg', 'Fluchtweg'), ('notausgang', 'Notausgang'), ('brandabschnitt', 'Brandabschnitt'), ('feuerloescher', 'Feuerlöscher'), ('rauchmelder', 'Rauchmelder'), ('sprinkler', 'Sprinkler'), ('rwa', 'RWA'), ('ex_zone', 'Ex-Zone'), ('brandmelder', 'Brandmelder'), ('hydrant', 'Hydrant')], max_length=50)),
                ('beschreibung', models.TextField()),
                ('schweregrad', models.CharField(choices=[('kritisch', 'Kritisch'), ('hoch', 'Hoch'), ('mittel', 'Mittel'), ('gering', 'Gering')], default='mittel', max_length=20)),
                ('position_x', models.FloatField(blank=True, null=True)),
                ('position_y', models.FloatField(blank=True, null=True)),
                ('regelwerk', models.CharField(blank=True, max_length=100)),
                ('paragraph', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('in_bearbeitung', 'In Bearbeitung'), ('behoben', 'Behoben'), ('akzeptiert', 'Akzeptiert (mit Begründung)')], default='offen', max_length=20)),
                ('massnahme', models.TextField(blank=True, help_text='Empfohlene Maßnahme')),
                ('massnahme_umgesetzt', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='brandschutz/maengel/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pruefung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangel_liste', to='cad_hub.brandschutzpruefung')),
            ],
            options={
                'verbose_name': 'Brandschutz-Mangel',
                'verbose_name_plural': 'Brandschutz-Mängel',
                'db_table': 'cad_hub_brandschutz_mangel',
                'ordering': ['-schweregrad', '-created_at'],
            },
        ),
    ]
