# Generated by Django 5.2.6 on 2025-12-19 08:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_hub', '0006_brandschutzpruefung_brandschutzregelwerk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandschutzmangel',
            options={'ordering': ['-schweregrad', '-erstellt_am'], 'verbose_name': 'Brandschutz-Mangel', 'verbose_name_plural': 'Brandschutz-Mängel'},
        ),
        migrations.AlterModelOptions(
            name='brandschutzpruefung',
            options={'ordering': ['-pruef_datum', '-erstellt_am'], 'verbose_name': 'Brandschutz-Prüfung', 'verbose_name_plural': 'Brandschutz-Prüfungen'},
        ),
        migrations.RenameField(
            model_name='brandschutzmangel',
            old_name='updated_at',
            new_name='aktualisiert_am',
        ),
        migrations.RenameField(
            model_name='brandschutzmangel',
            old_name='massnahme_umgesetzt',
            new_name='behoben',
        ),
        migrations.RenameField(
            model_name='brandschutzmangel',
            old_name='created_at',
            new_name='erstellt_am',
        ),
        migrations.RenameField(
            model_name='brandschutzpruefung',
            old_name='updated_at',
            new_name='aktualisiert_am',
        ),
        migrations.RenameField(
            model_name='brandschutzpruefung',
            old_name='bemerkungen',
            new_name='beschreibung',
        ),
        migrations.RenameField(
            model_name='brandschutzpruefung',
            old_name='created_at',
            new_name='erstellt_am',
        ),
        migrations.RenameField(
            model_name='brandschutzpruefung',
            old_name='plan_datei',
            new_name='quelldatei',
        ),
        migrations.RemoveField(
            model_name='brandschutzmangel',
            name='massnahme',
        ),
        migrations.RemoveField(
            model_name='brandschutzmangel',
            name='paragraph',
        ),
        migrations.RemoveField(
            model_name='brandschutzmangel',
            name='regelwerk',
        ),
        migrations.RemoveField(
            model_name='brandschutzmangel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='brandschutzpruefung',
            name='anzahl_ex_bereiche',
        ),
        migrations.RemoveField(
            model_name='brandschutzpruefung',
            name='anzahl_feuerloescher',
        ),
        migrations.RemoveField(
            model_name='brandschutzpruefung',
            name='anzahl_fluchtwege',
        ),
        migrations.RemoveField(
            model_name='brandschutzpruefung',
            name='anzahl_maengel',
        ),
        migrations.RemoveField(
            model_name='brandschutzpruefung',
            name='anzahl_rauchmelder',
        ),
        migrations.RemoveField(
            model_name='brandschutzpruefung',
            name='eingefuegte_symbole',
        ),
        migrations.RemoveField(
            model_name='brandschutzpruefung',
            name='flaeche_m2',
        ),
        migrations.RemoveField(
            model_name='brandschutzpruefung',
            name='freigegeben_am',
        ),
        migrations.RemoveField(
            model_name='brandschutzpruefung',
            name='freigegeben_von',
        ),
        migrations.RemoveField(
            model_name='brandschutzpruefung',
            name='geprueft_am',
        ),
        migrations.RemoveField(
            model_name='brandschutzpruefung',
            name='maengel',
        ),
        migrations.RemoveField(
            model_name='brandschutzpruefung',
            name='plan_name',
        ),
        migrations.RemoveField(
            model_name='brandschutzpruefung',
            name='vorgeschlagene_symbole',
        ),
        migrations.RemoveField(
            model_name='brandschutzpruefung',
            name='warnungen',
        ),
        migrations.AddField(
            model_name='brandschutzmangel',
            name='behoben_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandschutzmangel',
            name='behoben_kommentar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brandschutzmangel',
            name='notizen',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brandschutzmangel',
            name='regelwerk_referenz',
            field=models.CharField(blank=True, help_text='z.B. ASR A2.3 §5', max_length=100),
        ),
        migrations.AddField(
            model_name='brandschutzpruefung',
            name='flaeche_qm',
            field=models.FloatField(blank=True, help_text='Geprüfte Fläche in m²', null=True),
        ),
        migrations.AddField(
            model_name='brandschutzpruefung',
            name='gebaeude_typ',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='brandschutzpruefung',
            name='naechste_pruefung',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandschutzpruefung',
            name='pruef_datum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandschutzpruefung',
            name='report_pdf',
            field=models.FileField(blank=True, null=True, upload_to='brandschutz/reports/'),
        ),
        migrations.AddField(
            model_name='brandschutzpruefung',
            name='titel',
            field=models.CharField(default='', help_text='Titel der Prüfung', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brandschutzmangel',
            name='kategorie',
            field=models.CharField(choices=[('fluchtweg', 'Fluchtweg'), ('notausgang', 'Notausgang'), ('brandabschnitt', 'Brandabschnitt'), ('feuerloescher', 'Feuerlöscher'), ('rauchmelder', 'Rauchmelder'), ('sprinkler', 'Sprinkler'), ('rwa', 'RWA'), ('ex_zone', 'Ex-Zone'), ('brandmelder', 'Brandmelder'), ('hydrant', 'Hydrant')], default='fluchtweg', max_length=50),
        ),
        migrations.AlterField(
            model_name='brandschutzmangel',
            name='pruefung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maengel', to='cad_hub.brandschutzpruefung'),
        ),
        migrations.AlterField(
            model_name='brandschutzpruefung',
            name='status',
            field=models.CharField(choices=[('entwurf', 'Entwurf'), ('in_pruefung', 'In Prüfung'), ('abgeschlossen', 'Abgeschlossen'), ('maengel', 'Mängel festgestellt'), ('freigegeben', 'Freigegeben')], default='entwurf', max_length=50),
        ),
        migrations.CreateModel(
            name='BrandschutzSymbolVorschlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol_typ', models.CharField(help_text='z.B. F001, RM, E001', max_length=50)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('raum_referenz', models.CharField(blank=True, max_length=100)),
                ('begruendung', models.TextField(blank=True)),
                ('regelwerk_basis', models.CharField(blank=True, max_length=100)),
                ('prioritaet', models.IntegerField(default=2, help_text='1=hoch, 2=mittel, 3=niedrig')),
                ('status', models.CharField(choices=[('vorgeschlagen', 'Vorgeschlagen'), ('genehmigt', 'Genehmigt'), ('abgelehnt', 'Abgelehnt'), ('eingefuegt', 'Eingefügt')], default='vorgeschlagen', max_length=20)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('pruefung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbole', to='cad_hub.brandschutzpruefung')),
            ],
            options={
                'verbose_name': 'Symbol-Vorschlag',
                'verbose_name_plural': 'Symbol-Vorschläge',
                'db_table': 'cad_hub_brandschutz_symbol_vorschlag',
                'ordering': ['prioritaet', '-erstellt_am'],
            },
        ),
    ]
