# Generated by Django 6.0 on 2025-12-11 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("bfagent", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique domain code (e.g., 'bookwriting', 'medtrans', 'genagent')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable domain name (e.g., 'Book Writing', 'Medical Translation')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of this domain and its characteristics"
                    ),
                ),
                (
                    "characteristics",
                    models.TextField(
                        help_text="Key characteristics, workflows, and industry-specific requirements for AI context"
                    ),
                ),
                (
                    "typical_phases",
                    models.TextField(
                        blank=True,
                        help_text="Common phases typically found in this domain (for AI reference)",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-folder",
                        help_text="Bootstrap icon class (e.g., 'bi-book', 'bi-translate', 'bi-robot')",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="primary",
                        help_text="Bootstrap color class (primary, success, warning, info, etc.)",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project_count",
                    models.IntegerField(
                        default=0, help_text="Number of projects using this domain"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workflow_domains",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique project type code within domain (e.g., 'novel', 'medical_report')",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Human-readable project type name", max_length=150),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of this project type and its specific requirements"
                    ),
                ),
                (
                    "characteristics",
                    models.TextField(
                        help_text="Key characteristics, deliverables, and specific workflows for this project type"
                    ),
                ),
                (
                    "typical_duration_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Typical project duration in days (for AI estimation)",
                        null=True,
                    ),
                ),
                (
                    "complexity_level",
                    models.CharField(
                        choices=[
                            ("simple", "Simple (1-2 weeks)"),
                            ("moderate", "Moderate (1-2 months)"),
                            ("complex", "Complex (3-6 months)"),
                            ("enterprise", "Enterprise (6+ months)"),
                        ],
                        default="moderate",
                        help_text="Complexity level for AI phase estimation",
                        max_length=20,
                    ),
                ),
                (
                    "industry_standards",
                    models.TextField(
                        blank=True,
                        help_text="Industry standards, regulations, or best practices relevant to this project type",
                    ),
                ),
                (
                    "common_deliverables",
                    models.TextField(
                        blank=True,
                        help_text="Common deliverables and outputs for this project type",
                    ),
                ),
                (
                    "stakeholder_types",
                    models.TextField(
                        blank=True, help_text="Typical stakeholders involved in this project type"
                    ),
                ),
                (
                    "phase_generation_hints",
                    models.TextField(
                        blank=True,
                        help_text="Specific hints for AI phase generation (e.g., 'Include regulatory review', 'Emphasize testing')",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0, help_text="Number of times this project type has been used"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_types",
                        to="control_center.workflowdomain",
                    ),
                ),
            ],
            options={
                "db_table": "project_types",
                "ordering": ["domain__name", "name"],
                "unique_together": {("domain", "code")},
            },
        ),
        migrations.CreateModel(
            name="NavigationSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique section code (e.g., 'workflow_engine', 'content_management')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Display name for the section", max_length=100),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this navigation section"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-folder",
                        help_text="Bootstrap icon class for the section",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="primary", help_text="Bootstrap color class", max_length=20
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower numbers appear first)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_collapsible",
                    models.BooleanField(
                        default=True, help_text="Whether this section can be collapsed"
                    ),
                ),
                (
                    "is_collapsed_default",
                    models.BooleanField(
                        default=False, help_text="Whether this section is collapsed by default"
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True,
                        help_text="URL-safe identifier (Phase 1+: for new schema)",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="domain_id",
                        help_text="Domain this section belongs to (Phase 1+: FK to DomainArt)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="navigation_sections_new",
                        to="bfagent.domainart",
                    ),
                ),
                (
                    "required_groups",
                    models.ManyToManyField(
                        blank=True, help_text="Groups required to see this section", to="auth.group"
                    ),
                ),
                (
                    "required_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Permissions required to see this section",
                        to="auth.permission",
                    ),
                ),
                (
                    "domains",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Domains where this section is visible (empty = all domains)",
                        to="control_center.workflowdomain",
                    ),
                ),
            ],
            options={
                "db_table": "navigation_sections",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "phases_json",
                    models.JSONField(
                        help_text="JSON array of phase definitions with name, description, estimated_days, required, order"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default template for the project type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("usage_count", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_templates",
                        to="control_center.projecttype",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_templates_v2",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserNavigationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_collapsed",
                    models.BooleanField(
                        default=False, help_text="Whether user has collapsed this section"
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False, help_text="Whether user has hidden this section"
                    ),
                ),
                (
                    "custom_order",
                    models.IntegerField(
                        blank=True, help_text="User's custom ordering preference", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="control_center.navigationsection",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "user_navigation_preferences",
                "unique_together": {("user", "section")},
            },
        ),
        migrations.CreateModel(
            name="NavigationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(help_text="Unique item code within section", max_length=50),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the navigation item", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Tooltip or description text"),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("link", "Link"),
                            ("dropdown", "Dropdown"),
                            ("separator", "Separator"),
                            ("header", "Header"),
                        ],
                        default="link",
                        max_length=20,
                    ),
                ),
                (
                    "url_name",
                    models.CharField(
                        blank=True,
                        help_text="Django URL name (e.g., 'control_center:workflow-v2-dashboard')",
                        max_length=100,
                    ),
                ),
                (
                    "url_params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="URL parameters as JSON (e.g., {'domain': 'bookwriting'})",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True, help_text="External URL (if not using Django URL name)"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-circle", help_text="Bootstrap icon class", max_length=50
                    ),
                ),
                (
                    "badge_text",
                    models.CharField(
                        blank=True,
                        help_text="Badge text (e.g., 'V2', 'NEW', 'BETA')",
                        max_length=20,
                    ),
                ),
                (
                    "badge_color",
                    models.CharField(
                        default="primary", help_text="Badge color class", max_length=20
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order within section")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "opens_in_new_tab",
                    models.BooleanField(default=False, help_text="Whether link opens in new tab"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="control_center.navigationitem",
                    ),
                ),
                (
                    "required_groups",
                    models.ManyToManyField(
                        blank=True, help_text="Groups required to see this item", to="auth.group"
                    ),
                ),
                (
                    "required_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Permissions required to see this item",
                        to="auth.permission",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="navigation_items",
                        to="control_center.navigationsection",
                    ),
                ),
                (
                    "domains",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Limit this item to specific domains (empty = all domains)",
                        to="control_center.workflowdomain",
                    ),
                ),
            ],
            options={
                "db_table": "navigation_items",
                "ordering": ["section__order", "order", "name"],
                "unique_together": {("section", "code")},
            },
        ),
    ]
