# Generated by Django 5.2.6 on 2025-12-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsection',
            name='external_url',
            field=models.URLField(blank=True, help_text='External URL for section header (if not using Django URL name)'),
        ),
        migrations.AddField(
            model_name='navigationsection',
            name='url_name',
            field=models.CharField(blank=True, help_text="Django URL name for section header link (e.g., 'control_center:workflow-v2-dashboard')", max_length=100),
        ),
    ]
