"""
Export Handlers - Book Writing Domain
Generate formatted exports (Markdown, HTML, PDF, EPUB)
"""
import logging
import os
from typing import Dict, Any, List
from datetime import datetime
from io import BytesIO

from django.conf import settings
from apps.bfagent.models import BookProjects, BookChapters, Characters, Worlds

logger = logging.getLogger(__name__)


class MarkdownExportHandler:
    """
    Export book as formatted Markdown
    
    Input:
    - project_id: int
    - include_metadata: bool (default True)
    - include_toc: bool (default True)
    
    Output:
    - content: str (markdown content)
    - filename: str
    - word_count: int
    """
    
    @staticmethod
    def handle(data: Dict[str, Any], config: Dict[str, Any] = None) -> Dict[str, Any]:
        """Generate Markdown export"""
        project_id = data.get('project_id')
        include_metadata = data.get('include_metadata', True)
        include_toc = data.get('include_toc', True)
        
        if not project_id:
            return {'success': False, 'error': 'project_id required'}
        
        try:
            project = BookProjects.objects.get(id=project_id)
            chapters = BookChapters.objects.filter(project=project).order_by('chapter_number')
            characters = Characters.objects.filter(project=project)
            worlds = Worlds.objects.filter(project=project)
        except BookProjects.DoesNotExist:
            return {'success': False, 'error': f'Project {project_id} not found'}
        
        lines = []
        
        # Title
        lines.extend([
            f"# {project.title}",
            "",
        ])
        
        # Metadata
        if include_metadata:
            lines.extend([
                "---",
                "",
                f"**Genre:** {project.genre or 'Fiction'}",
                f"**Status:** {project.status or 'Draft'}",
                f"**Created:** {project.created_at.strftime('%Y-%m-%d') if project.created_at else 'Unknown'}",
                "",
            ])
            
            if project.description:
                lines.extend([
                    "## Synopsis",
                    "",
                    project.description,
                    "",
                ])
            
            if project.story_premise:
                lines.extend([
                    "## Premise",
                    "",
                    project.story_premise,
                    "",
                ])
            
            lines.append("---")
            lines.append("")
        
        # Table of Contents
        if include_toc and chapters.exists():
            lines.extend([
                "## Table of Contents",
                "",
            ])
            for chapter in chapters:
                lines.append(f"- [{chapter.title}](#chapter-{chapter.chapter_number})")
            lines.append("")
            lines.append("---")
            lines.append("")
        
        # Characters Section (optional)
        if characters.exists() and include_metadata:
            lines.extend([
                "## Characters",
                "",
            ])
            for char in characters:
                lines.append(f"### {char.name}")
                if char.role:
                    lines.append(f"**Role:** {char.role}")
                if char.description:
                    lines.append(f"\n{char.description}")
                lines.append("")
            lines.append("---")
            lines.append("")
        
        # Chapters
        for chapter in chapters:
            lines.extend([
                f"## Chapter {chapter.chapter_number}: {chapter.title} {{#chapter-{chapter.chapter_number}}}",
                "",
            ])
            
            if chapter.content:
                lines.append(chapter.content)
            else:
                lines.append("*Chapter content not yet written*")
            
            lines.append("")
            lines.append("---")
            lines.append("")
        
        # Footer
        lines.extend([
            "",
            "---",
            "",
            f"*Generated by BF Agent on {datetime.now().strftime('%Y-%m-%d %H:%M')}*",
        ])
        
        content = "\n".join(lines)
        word_count = len(content.split())
        filename = f"{project.title.replace(' ', '_').lower()}_manuscript.md"
        
        return {
            'success': True,
            'content': content,
            'filename': filename,
            'word_count': word_count,
            'chapter_count': chapters.count(),
            'format': 'markdown'
        }


class HTMLExportHandler:
    """
    Export book as styled HTML
    
    Input:
    - project_id: int
    - template: str (default 'book', options: 'book', 'ebook', 'print')
    
    Output:
    - content: str (HTML content)
    - filename: str
    """
    
    TEMPLATES = {
        'book': {
            'font_family': 'Georgia, serif',
            'font_size': '16px',
            'line_height': '1.6',
            'max_width': '800px',
            'chapter_break': True,
        },
        'ebook': {
            'font_family': 'system-ui, sans-serif',
            'font_size': '14px',
            'line_height': '1.5',
            'max_width': '100%',
            'chapter_break': False,
        },
        'print': {
            'font_family': 'Times New Roman, serif',
            'font_size': '12pt',
            'line_height': '1.8',
            'max_width': '6in',
            'chapter_break': True,
        },
    }
    
    @staticmethod
    def handle(data: Dict[str, Any], config: Dict[str, Any] = None) -> Dict[str, Any]:
        """Generate HTML export"""
        project_id = data.get('project_id')
        template_name = data.get('template', 'book')
        
        if not project_id:
            return {'success': False, 'error': 'project_id required'}
        
        try:
            project = BookProjects.objects.get(id=project_id)
            chapters = BookChapters.objects.filter(project=project).order_by('chapter_number')
        except BookProjects.DoesNotExist:
            return {'success': False, 'error': f'Project {project_id} not found'}
        
        template = HTMLExportHandler.TEMPLATES.get(template_name, HTMLExportHandler.TEMPLATES['book'])
        
        # Build HTML
        html_parts = [
            '<!DOCTYPE html>',
            '<html lang="en">',
            '<head>',
            f'<meta charset="UTF-8">',
            f'<meta name="viewport" content="width=device-width, initial-scale=1.0">',
            f'<title>{project.title}</title>',
            '<style>',
            f'''
            body {{
                font-family: {template['font_family']};
                font-size: {template['font_size']};
                line-height: {template['line_height']};
                max-width: {template['max_width']};
                margin: 0 auto;
                padding: 2em;
                background: #fefefe;
                color: #333;
            }}
            h1 {{
                text-align: center;
                margin-bottom: 0.5em;
                font-size: 2.5em;
            }}
            h2 {{
                margin-top: 2em;
                border-bottom: 1px solid #ddd;
                padding-bottom: 0.3em;
            }}
            .metadata {{
                text-align: center;
                color: #666;
                margin-bottom: 2em;
            }}
            .chapter {{
                margin-bottom: 3em;
            }}
            .chapter-title {{
                font-size: 1.5em;
                margin-bottom: 1em;
            }}
            .chapter-content {{
                text-align: justify;
            }}
            .chapter-content p {{
                text-indent: 1.5em;
                margin: 0.5em 0;
            }}
            @media print {{
                .chapter {{
                    page-break-before: always;
                }}
            }}
            ''',
            '</style>',
            '</head>',
            '<body>',
            f'<h1>{project.title}</h1>',
            f'<div class="metadata">',
            f'<p><strong>Genre:</strong> {project.genre or "Fiction"}</p>',
        ]
        
        if project.description:
            html_parts.append(f'<p><em>{project.description[:200]}...</em></p>')
        
        html_parts.extend([
            '</div>',
            '<hr>',
        ])
        
        # Chapters
        for chapter in chapters:
            chapter_class = 'chapter'
            if template['chapter_break']:
                chapter_class += ' page-break'
            
            html_parts.extend([
                f'<div class="{chapter_class}">',
                f'<h2 class="chapter-title">Chapter {chapter.chapter_number}: {chapter.title}</h2>',
                '<div class="chapter-content">',
            ])
            
            if chapter.content:
                # Convert paragraphs
                paragraphs = chapter.content.split('\n\n')
                for p in paragraphs:
                    if p.strip():
                        html_parts.append(f'<p>{p.strip()}</p>')
            else:
                html_parts.append('<p><em>Chapter content not yet written</em></p>')
            
            html_parts.extend([
                '</div>',
                '</div>',
            ])
        
        # Footer
        html_parts.extend([
            '<hr>',
            f'<footer style="text-align: center; color: #999; font-size: 0.8em;">',
            f'Generated by BF Agent on {datetime.now().strftime("%Y-%m-%d %H:%M")}',
            '</footer>',
            '</body>',
            '</html>',
        ])
        
        content = '\n'.join(html_parts)
        filename = f"{project.title.replace(' ', '_').lower()}_manuscript.html"
        
        return {
            'success': True,
            'content': content,
            'filename': filename,
            'template': template_name,
            'chapter_count': chapters.count(),
            'format': 'html'
        }


class PDFExportHandler:
    """
    Export book as PDF (requires weasyprint or reportlab)
    
    Input:
    - project_id: int
    - page_size: str (default 'A4', options: 'A4', 'Letter', '6x9')
    
    Output:
    - content: bytes (PDF binary)
    - filename: str
    """
    
    @staticmethod
    def handle(data: Dict[str, Any], config: Dict[str, Any] = None) -> Dict[str, Any]:
        """Generate PDF export"""
        project_id = data.get('project_id')
        
        if not project_id:
            return {'success': False, 'error': 'project_id required'}
        
        # First generate HTML
        html_result = HTMLExportHandler.handle({
            'project_id': project_id,
            'template': 'print'
        })
        
        if not html_result.get('success'):
            return html_result
        
        html_content = html_result['content']
        
        try:
            # Try WeasyPrint first
            from weasyprint import HTML
            
            pdf_bytes = HTML(string=html_content).write_pdf()
            
            project = BookProjects.objects.get(id=project_id)
            filename = f"{project.title.replace(' ', '_').lower()}_manuscript.pdf"
            
            return {
                'success': True,
                'content': pdf_bytes,
                'filename': filename,
                'format': 'pdf',
                'size_bytes': len(pdf_bytes)
            }
            
        except ImportError:
            # WeasyPrint not available
            logger.warning("WeasyPrint not installed. Returning HTML instead.")
            return {
                'success': True,
                'content': html_content.encode('utf-8'),
                'filename': html_result['filename'].replace('.html', '_for_pdf.html'),
                'format': 'html',
                'note': 'PDF export requires WeasyPrint. HTML provided instead.'
            }
        except Exception as e:
            logger.error(f"PDF export error: {e}")
            return {'success': False, 'error': str(e)}


class EPUBExportHandler:
    """
    Export book as EPUB (requires ebooklib)
    
    Input:
    - project_id: int
    - cover_image: str (optional, path to cover image)
    
    Output:
    - content: bytes (EPUB binary)
    - filename: str
    """
    
    @staticmethod
    def handle(data: Dict[str, Any], config: Dict[str, Any] = None) -> Dict[str, Any]:
        """Generate EPUB export"""
        project_id = data.get('project_id')
        
        if not project_id:
            return {'success': False, 'error': 'project_id required'}
        
        try:
            project = BookProjects.objects.get(id=project_id)
            chapters = BookChapters.objects.filter(project=project).order_by('chapter_number')
        except BookProjects.DoesNotExist:
            return {'success': False, 'error': f'Project {project_id} not found'}
        
        try:
            from ebooklib import epub
            
            book = epub.EpubBook()
            
            # Metadata
            book.set_identifier(f'bfagent-{project_id}')
            book.set_title(project.title)
            book.set_language('en')
            book.add_author('BF Agent')
            
            if project.description:
                book.add_metadata('DC', 'description', project.description)
            if project.genre:
                book.add_metadata('DC', 'subject', project.genre)
            
            # Style
            style = '''
            body { font-family: Georgia, serif; line-height: 1.6; }
            h1 { text-align: center; }
            h2 { margin-top: 2em; }
            p { text-indent: 1.5em; margin: 0.5em 0; }
            '''
            nav_css = epub.EpubItem(
                uid="style_nav",
                file_name="style/nav.css",
                media_type="text/css",
                content=style
            )
            book.add_item(nav_css)
            
            # Chapters
            epub_chapters = []
            for chapter in chapters:
                c = epub.EpubHtml(
                    title=f"Chapter {chapter.chapter_number}: {chapter.title}",
                    file_name=f'chapter_{chapter.chapter_number}.xhtml',
                    lang='en'
                )
                
                content = chapter.content or '*Chapter content not yet written*'
                paragraphs = '\n'.join([f'<p>{p}</p>' for p in content.split('\n\n') if p.strip()])
                
                c.content = f'''
                <html>
                <head><link rel="stylesheet" href="style/nav.css" type="text/css"/></head>
                <body>
                <h2>Chapter {chapter.chapter_number}: {chapter.title}</h2>
                {paragraphs}
                </body>
                </html>
                '''
                
                book.add_item(c)
                epub_chapters.append(c)
            
            # Navigation
            book.toc = tuple(epub_chapters)
            book.add_item(epub.EpubNcx())
            book.add_item(epub.EpubNav())
            
            # Spine
            book.spine = ['nav'] + epub_chapters
            
            # Write to bytes
            output = BytesIO()
            epub.write_epub(output, book, {})
            epub_bytes = output.getvalue()
            
            filename = f"{project.title.replace(' ', '_').lower()}_manuscript.epub"
            
            return {
                'success': True,
                'content': epub_bytes,
                'filename': filename,
                'format': 'epub',
                'size_bytes': len(epub_bytes),
                'chapter_count': chapters.count()
            }
            
        except ImportError:
            logger.warning("ebooklib not installed. Returning Markdown instead.")
            return MarkdownExportHandler.handle(data, config)
        except Exception as e:
            logger.error(f"EPUB export error: {e}")
            return {'success': False, 'error': str(e)}


class UniversalExportHandler:
    """
    Universal export handler - routes to appropriate format handler
    
    Input:
    - project_id: int
    - format: str ('markdown', 'html', 'pdf', 'epub')
    - options: dict (format-specific options)
    
    Output:
    - Varies by format
    """
    
    HANDLERS = {
        'markdown': MarkdownExportHandler,
        'md': MarkdownExportHandler,
        'html': HTMLExportHandler,
        'pdf': PDFExportHandler,
        'epub': EPUBExportHandler,
    }
    
    @staticmethod
    def handle(data: Dict[str, Any], config: Dict[str, Any] = None) -> Dict[str, Any]:
        """Route to appropriate export handler"""
        export_format = data.get('format', 'markdown').lower()
        
        handler_class = UniversalExportHandler.HANDLERS.get(export_format)
        
        if not handler_class:
            return {
                'success': False,
                'error': f"Unknown format: {export_format}. Supported: {list(UniversalExportHandler.HANDLERS.keys())}"
            }
        
        return handler_class.handle(data, config)
