# Generated by Django 6.0 on 2025-12-11 12:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(help_text="Template collection name", max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this template collection"
                    ),
                ),
                (
                    "client",
                    models.CharField(blank=True, help_text="Client/Company name", max_length=200),
                ),
                ("project", models.CharField(blank=True, help_text="Project name", max_length=200)),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tech", "Technology"),
                            ("healthcare", "Healthcare"),
                            ("finance", "Finance"),
                            ("education", "Education"),
                            ("consulting", "Consulting"),
                            ("legal", "Legal"),
                            ("retail", "Retail"),
                            ("manufacturing", "Manufacturing"),
                            ("other", "Other"),
                        ],
                        help_text="Industry/sector for this template",
                        max_length=100,
                    ),
                ),
                (
                    "templates",
                    models.JSONField(
                        default=dict,
                        help_text="Template slide configurations: {template_type: {layout_name, slide_index, ...}}",
                    ),
                ),
                (
                    "master_pptx",
                    models.FileField(
                        help_text="Master PPTX file containing all template slides",
                        upload_to="template_collections/%Y/%m/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this collection is available for use"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Use as default for new presentations"
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="System-provided template (cannot be deleted)"
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0, help_text="Number of presentations using this collection"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="template_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Collection",
                "verbose_name_plural": "Template Collections",
                "db_table": "presentation_studio_template_collection",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Presentation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(help_text="Presentation title", max_length=200)),
                ("description", models.TextField(blank=True, help_text="Optional description")),
                (
                    "original_file",
                    models.FileField(
                        help_text="Original PPTX file", upload_to="presentations/originals/%Y/%m/"
                    ),
                ),
                (
                    "enhanced_file",
                    models.FileField(
                        blank=True,
                        help_text="Enhanced PPTX file",
                        null=True,
                        upload_to="presentations/enhanced/%Y/%m/",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enhancement_status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("analyzing", "Analyzing"),
                            ("ready", "Ready to Enhance"),
                            ("enhancing", "Enhancing"),
                            ("completed", "Enhanced"),
                            ("failed", "Enhancement Failed"),
                        ],
                        db_index=True,
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("slide_count_original", models.IntegerField(default=0)),
                ("slide_count_enhanced", models.IntegerField(default=0)),
                (
                    "concepts_added",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of concepts added during enhancements",
                    ),
                ),
                (
                    "enhancement_metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional enhancement metadata"
                    ),
                ),
                (
                    "slide_templates",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Analyzed slide templates from this PPTX (legacy/fallback)",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presentations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template_collection",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template collection used for this presentation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="presentations",
                        to="presentation_studio.templatecollection",
                    ),
                ),
            ],
            options={
                "db_table": "presentation_studio_presentation",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Enhancement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "enhancement_type",
                    models.CharField(
                        choices=[
                            ("medical", "Medical Case"),
                            ("business", "Business Strategy"),
                            ("scientific", "Scientific Research"),
                            ("technical", "Technical Documentation"),
                            ("custom", "Custom"),
                        ],
                        help_text="Type of enhancement template used",
                        max_length=50,
                    ),
                ),
                (
                    "enhancement_mode",
                    models.CharField(
                        choices=[("append", "Append at End"), ("smart", "Smart Positioning")],
                        default="append",
                        max_length=20,
                    ),
                ),
                ("concepts", models.JSONField(help_text="List of concepts/slides to add")),
                (
                    "configuration",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional configuration options"
                    ),
                ),
                ("slides_before", models.IntegerField()),
                ("slides_after", models.IntegerField()),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                (
                    "result_data",
                    models.JSONField(blank=True, default=dict, help_text="Detailed result data"),
                ),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True, help_text="Enhancement execution time", null=True
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presentation_enhancements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "presentation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enhancements",
                        to="presentation_studio.presentation",
                    ),
                ),
            ],
            options={
                "db_table": "presentation_studio_enhancement",
                "ordering": ["-executed_at"],
                "indexes": [
                    models.Index(
                        fields=["presentation", "-executed_at"],
                        name="presentatio_present_7120c8_idx",
                    ),
                    models.Index(
                        fields=["enhancement_type"], name="presentatio_enhance_a77e6d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DesignProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "profile_name",
                    models.CharField(
                        help_text="e.g. 'Corporate Blue', 'Academic Style'", max_length=100
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("extracted", "Extracted from Upload"),
                            ("template", "System Template"),
                            ("custom", "Custom Created"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "colors",
                    models.JSONField(
                        default=dict,
                        help_text="Color scheme: primary, secondary, accents, text, background",
                    ),
                ),
                (
                    "fonts",
                    models.JSONField(
                        default=dict, help_text="Font definitions: heading, body, caption"
                    ),
                ),
                ("is_system_template", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "presentation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source presentation if extracted",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_profiles",
                        to="presentation_studio.presentation",
                    ),
                ),
            ],
            options={
                "db_table": "presentation_studio_design_profile",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["source_type"], name="presentatio_source__1b715e_idx"),
                    models.Index(
                        fields=["is_system_template"], name="presentatio_is_syst_b7bbe3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PreviewSlide",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("preview_order", models.IntegerField(help_text="Display order in preview list")),
                ("title", models.CharField(help_text="Slide title", max_length=500)),
                (
                    "content_data",
                    models.JSONField(
                        help_text="Full slide content structure (SlideContent format)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preview", "Preview - Not Converted"),
                            ("converted", "Converted to PPTX"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="preview",
                        max_length=20,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("markdown", "Markdown File"),
                            ("json", "JSON File"),
                            ("pdf", "PDF Extract"),
                            ("manual", "Manual Entry"),
                        ],
                        help_text="Where this preview came from",
                        max_length=50,
                    ),
                ),
                (
                    "source_file_name",
                    models.CharField(
                        blank=True, help_text="Original source file name", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "converted_at",
                    models.DateTimeField(blank=True, help_text="When converted to PPTX", null=True),
                ),
                (
                    "pptx_slide_number",
                    models.IntegerField(
                        blank=True, help_text="Slide number in final PPTX", null=True
                    ),
                ),
                (
                    "presentation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preview_slides",
                        to="presentation_studio.presentation",
                    ),
                ),
            ],
            options={
                "db_table": "presentation_studio_preview_slide",
                "ordering": ["presentation", "preview_order"],
                "indexes": [
                    models.Index(
                        fields=["presentation", "status"], name="presentatio_present_3bcbb2_idx"
                    ),
                    models.Index(
                        fields=["presentation", "preview_order"],
                        name="presentatio_present_c4d4a6_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="templatecollection",
            index=models.Index(fields=["client"], name="presentatio_client_664c13_idx"),
        ),
        migrations.AddIndex(
            model_name="templatecollection",
            index=models.Index(fields=["industry"], name="presentatio_industr_0f6158_idx"),
        ),
        migrations.AddIndex(
            model_name="templatecollection",
            index=models.Index(
                fields=["is_active", "is_default"], name="presentatio_is_acti_9d00ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="presentation",
            index=models.Index(
                fields=["uploaded_by", "-uploaded_at"], name="presentatio_uploade_b0dc07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="presentation",
            index=models.Index(
                fields=["enhancement_status"], name="presentatio_enhance_13c0c5_idx"
            ),
        ),
    ]
