"""
Template Enforcer
=================

Generiert Handler-Code der BY DESIGN standard-konform ist.
Nutzt Jinja2 Templates die alle Standards eingebaut haben.
"""

from typing import Dict, List, Any
import re


def to_snake_case(name: str) -> str:
    """CamelCase → snake_case"""
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()


class TemplateEnforcer:
    """Generiert standard-konformen Code durch Templates"""
    
    def generate_handler(
        self,
        handler_name: str,
        description: str,
        domain: str,
        input_fields: List[Dict[str, Any]],
        output_fields: List[Dict[str, Any]],
        use_cases: List[str] = None,
        version: str = "1.0.0",
    ) -> Dict[str, str]:
        """
        Generiert Handler + Test Code.
        
        Returns:
            {"handler_code": str, "test_code": str, ...}
        """
        use_cases = use_cases or ["Process data"]
        snake_name = to_snake_case(handler_name)
        
        # Handler Code generieren
        handler_code = self._generate_handler_code(
            handler_name=handler_name,
            snake_name=snake_name,
            description=description,
            domain=domain,
            input_fields=input_fields,
            output_fields=output_fields,
            use_cases=use_cases,
            version=version,
        )
        
        # Test Code generieren
        test_code = self._generate_test_code(
            handler_name=handler_name,
            snake_name=snake_name,
            domain=domain,
            input_fields=input_fields,
            output_fields=output_fields,
        )
        
        return {
            "handler_code": handler_code,
            "test_code": test_code,
            "handler_filename": f"{snake_name}.py",
            "test_filename": f"test_{snake_name}.py",
        }
    
    def _generate_handler_code(self, **ctx) -> str:
        """Generiert Handler Code (inline Template)"""
        
        # Input Fields formatieren
        input_fields_str = self._format_fields(ctx["input_fields"])
        output_fields_str = self._format_fields(ctx["output_fields"])
        use_cases_str = "\n".join(f"    - {uc}" for uc in ctx["use_cases"])
        
        return f'''"""
{ctx["handler_name"]} - {ctx["description"]}

Auto-generated by BF Agent MCP Server
Standards: H001, H002, H003, H004, S001, S002, E001, L001, D001
"""

from typing import Dict, List, Any, Optional
from pydantic import BaseModel, Field, ValidationError

from apps.core.handlers.base import BaseHandler, HandlerResult


# ═══════════════════════════════════════════════════════════════════════════════
# SCHEMAS (Standards S001, S002, S003)
# ═══════════════════════════════════════════════════════════════════════════════

class {ctx["handler_name"]}Input(BaseModel):
    """Input Schema für {ctx["handler_name"]}"""
{input_fields_str}


class {ctx["handler_name"]}Output(BaseModel):
    """Output Schema für {ctx["handler_name"]}"""
{output_fields_str}


# ═══════════════════════════════════════════════════════════════════════════════
# HANDLER (Standards H001, H002, H003, H004, E001, L001, D001)
# ═══════════════════════════════════════════════════════════════════════════════

class {ctx["handler_name"]}(BaseHandler):
    """
    {ctx["description"]}
    
    Use Cases:
{use_cases_str}
    """
    
    # Metadata (H004)
    name = "{ctx["snake_name"]}"
    description = "{ctx["description"]}"
    version = "{ctx["version"]}"
    
    # Schemas (S001, S002)
    input_schema = {ctx["handler_name"]}Input
    output_schema = {ctx["handler_name"]}Output
    
    async def validate(self, context: Dict[str, Any]) -> None:
        """Phase 1: Validation (H002)"""
        self.logger.debug(f"Validating {{self.name}}")
        self.validated_input = self.input_schema(**context.get("input", {{}}))
    
    async def process(self, context: Dict[str, Any]) -> HandlerResult:
        """Phase 2: Processing (H002, H003, E001)"""
        try:
            self.logger.info(f"Processing {{self.name}}")
            
            # TODO: Implement business logic
            result_data = await self._do_process(self.validated_input)
            
            # Validate output
            output = self.output_schema(**result_data)
            
            self.logger.info(f"Completed {{self.name}}")
            
            return HandlerResult.success(
                data=output.model_dump(),
                metadata={{"handler": self.name, "version": self.version}}
            )
            
        except ValidationError as e:
            self.logger.warning(f"Validation failed: {{e}}")
            return HandlerResult.error(message=str(e), error_code="VALIDATION_ERROR")
        except Exception as e:
            self.logger.exception(f"Error in {{self.name}}")
            return HandlerResult.error(message=str(e), error_code="PROCESSING_ERROR")
    
    async def cleanup(self, context: Dict[str, Any]) -> None:
        """Phase 3: Cleanup (H002)"""
        self.logger.debug(f"Cleanup {{self.name}}")
    
    async def _do_process(self, input_data: {ctx["handler_name"]}Input) -> Dict[str, Any]:
        """Core processing - override this method"""
        raise NotImplementedError("Implement _do_process()")
'''
    
    def _generate_test_code(self, **ctx) -> str:
        """Generiert Test Code"""
        
        return f'''"""
Tests for {ctx["handler_name"]}

Standards: T001, T002, T003
"""

import pytest
from unittest.mock import patch, AsyncMock

from apps.{ctx["domain"]}.handlers.{ctx["snake_name"]} import (
    {ctx["handler_name"]},
    {ctx["handler_name"]}Input,
    {ctx["handler_name"]}Output,
)


class Test{ctx["handler_name"]}:
    """Test suite for {ctx["handler_name"]} (T001)"""
    
    @pytest.fixture
    def handler(self):
        return {ctx["handler_name"]}()
    
    @pytest.fixture
    def valid_input(self):
        return {{
            # TODO: Add valid test data
        }}
    
    @pytest.mark.asyncio
    async def test_process_success(self, handler, valid_input):
        """Happy path test (T002)"""
        context = {{"input": valid_input}}
        
        with patch.object(handler, "_do_process", new_callable=AsyncMock) as mock:
            mock.return_value = {{}}  # TODO: Add expected output
            result = await handler.execute(context)
        
        assert result.success is True
    
    @pytest.mark.asyncio
    async def test_process_error(self, handler):
        """Error path test (T003)"""
        context = {{"input": {{}}}}  # Invalid input
        
        result = await handler.execute(context)
        
        # Should handle gracefully
        assert result is not None
'''
    
    def _format_fields(self, fields: List[Dict[str, Any]]) -> str:
        """Formatiert Pydantic Fields"""
        if not fields:
            return "    pass"
        
        lines = []
        for f in fields:
            name = f.get("name", "field")
            ftype = f.get("type", "str")
            desc = f.get("description", "Field description")
            required = f.get("required", True)
            default = f.get("default", "None")
            
            if required:
                lines.append(f'    {name}: {ftype} = Field(..., description="{desc}")')
            else:
                lines.append(f'    {name}: {ftype} = Field(default={default}, description="{desc}")')
        
        return "\n".join(lines)
