# Generated by Django 5.2.6 on 2025-10-07 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0012_targetaudience_writingstatus_genre"),
    ]

    operations = []
