# Generated by Django 5.2.6 on 2025-12-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0040_handler_actionhandler_handlerexecution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illustrationimage',
            name='image_url',
            field=models.TextField(help_text='URL to generated image'),
        ),
        migrations.AlterField(
            model_name='illustrationimage',
            name='thumbnail_url',
            field=models.TextField(blank=True, help_text='URL to thumbnail', null=True),
        ),
    ]
