# Generated by Django 5.2.6 on 2025-12-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0041_idea_generation_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worlds',
            name='technology_level',
            field=models.TextField(blank=True, null=True),
        ),
    ]
