# Generated by Django 5.2.6 on 2026-01-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0043_bookprojects_field_lengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookprojects',
            name='figure_numbering_style',
            field=models.CharField(choices=[('global', 'Global (Abb. 1, 2, 3...)'), ('per_chapter', 'Pro Kapitel (Abb. 1.1, 1.2, 2.1...)')], default='global', help_text='Nummerierungsstil für Abbildungen', max_length=20),
        ),
        migrations.AddField(
            model_name='bookprojects',
            name='include_figure_index',
            field=models.BooleanField(default=True, help_text='Abbildungsverzeichnis am Ende generieren'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='category',
            field=models.CharField(choices=[('character', 'Character Development'), ('chapter', 'Chapter Writing'), ('world', 'World Building'), ('plot', 'Plot Development'), ('dialogue', 'Dialogue'), ('description', 'Description'), ('analysis', 'Analysis'), ('revision', 'Revision'), ('correction', 'Repetition Correction')], db_index=True, help_text='Template category', max_length=50),
        ),
    ]
