# Generated by Django 5.2.6 on 2026-01-10 07:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0045_testrequirement_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CascadeWorkLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('info', 'Info'), ('action', 'Action'), ('stdout', 'Stdout'), ('stderr', 'Stderr'), ('success', 'Success'), ('error', 'Error'), ('warning', 'Warning'), ('file_change', 'File Change'), ('test_result', 'Test Result')], max_length=20)),
                ('iteration', models.IntegerField(default=0)),
                ('message', models.TextField()),
                ('details', models.JSONField(default=dict, help_text='Extra context (files, line numbers, etc.)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cascade Work Log',
                'verbose_name_plural': 'Cascade Work Logs',
                'db_table': 'cascade_work_logs',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CascadeWorkSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('stopped', 'Manually Stopped'), ('max_iterations', 'Max Iterations Reached')], default='pending', max_length=20)),
                ('current_iteration', models.IntegerField(default=0)),
                ('max_iterations', models.IntegerField(default=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initial_context', models.TextField(help_text='Bug context at session start (Markdown)')),
                ('final_summary', models.TextField(blank=True, help_text='Summary when session ends')),
                ('files_changed', models.JSONField(default=list, help_text='List of files modified')),
                ('error_count', models.IntegerField(default=0)),
                ('success_indicators', models.JSONField(default=list, help_text='Success patterns detected')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cascade Work Session',
                'verbose_name_plural': 'Cascade Work Sessions',
                'db_table': 'cascade_work_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='testrequirement',
            new_name='bfagent_tes_domain_b06cbf_idx',
            old_name='bfagent_tes_domain_idx',
        ),
        migrations.AddField(
            model_name='cascadeworksession',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cascade_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cascadeworksession',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cascade_sessions', to='bfagent.testrequirement'),
        ),
        migrations.AddField(
            model_name='cascadeworklog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='bfagent.cascadeworksession'),
        ),
    ]
