# Generated by Django 5.2.6 on 2026-01-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0046_cascade_work_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cascadeworksession',
            name='domain',
            field=models.CharField(default='core', help_text='Domain this session belongs to (e.g., writing_hub, control_center, cad_hub)', max_length=50),
        ),
    ]
