# Generated by Django 5.2.6 on 2026-01-10 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0047_cascade_add_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrequirement',
            name='complexity',
            field=models.CharField(choices=[('auto', 'Auto (Heuristik)'), ('low', 'Low - Einfach'), ('medium', 'Medium - Moderat'), ('high', 'High - Komplex')], default='auto', help_text='Komplexität des Tasks (auto = automatische Erkennung)', max_length=20),
        ),
        migrations.AddField(
            model_name='testrequirement',
            name='llm_override',
            field=models.ForeignKey(blank=True, help_text='LLM-Override (leer = automatisch basierend auf Complexity)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_overrides', to='bfagent.llms'),
        ),
        migrations.AlterField(
            model_name='testrequirement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Testing'), ('in_progress', 'Testing in Progress'), ('done', 'Done'), ('completed', 'Testing Completed'), ('blocked', 'Blocked'), ('obsolete', 'Obsolete/Redundant'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
