# Generated by Django 5.2.6 on 2026-01-10 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0048_add_complexity_and_llm_to_requirement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('comment', 'Kommentar'), ('progress', 'Fortschritt'), ('blocker', 'Blocker'), ('question', 'Frage'), ('solution', 'Lösung'), ('screenshot', 'Screenshot')], default='comment', max_length=20)),
                ('content', models.TextField(help_text='Feedback-Inhalt')),
                ('screenshot', models.ImageField(blank=True, help_text='Optional: Screenshot als Beleg', null=True, upload_to='requirement_feedback/%Y/%m/%d/')),
                ('is_from_cascade', models.BooleanField(default=False, help_text='True wenn von Cascade AI generiert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='bfagent.testrequirement')),
            ],
            options={
                'verbose_name': 'Requirement Feedback',
                'verbose_name_plural': 'Requirement Feedbacks',
                'db_table': 'bfagent_requirement_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
