# Generated by Django 5.2.6 on 2026-01-10 15:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0050_add_testcase_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugResolutionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('tier_1_count', models.IntegerField(default=0)),
                ('tier_2_count', models.IntegerField(default=0)),
                ('tier_3_count', models.IntegerField(default=0)),
                ('tier_1_success_rate', models.FloatField(default=0)),
                ('tier_2_success_rate', models.FloatField(default=0)),
                ('tier_3_success_rate', models.FloatField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_saved_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tokens', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'bug_resolution_stats',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='BugLLMAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('initial_tier', models.CharField(choices=[('tier_1', '💚 Tier 1 (Günstig)'), ('tier_2', '💛 Tier 2 (Standard)'), ('tier_3', '🔴 Tier 3 (Premium)')], default='tier_1', help_text='Ursprünglich zugewiesener Tier', max_length=20)),
                ('current_tier', models.CharField(choices=[('tier_1', '💚 Tier 1 (Günstig)'), ('tier_2', '💛 Tier 2 (Standard)'), ('tier_3', '🔴 Tier 3 (Premium)')], default='tier_1', help_text='Aktueller Tier (nach Eskalationen)', max_length=20)),
                ('complexity_score', models.IntegerField(default=0, help_text='Berechneter Komplexitäts-Score')),
                ('attempts', models.IntegerField(default=0)),
                ('escalation_count', models.IntegerField(default=0)),
                ('tokens_input', models.IntegerField(default=0)),
                ('tokens_output', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, help_text='Kosten in USD', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('in_progress', 'In Bearbeitung'), ('resolved', 'Gelöst'), ('escalated', 'Eskaliert'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=20)),
                ('resolution_confidence', models.FloatField(blank=True, help_text='Konfidenz der Lösung (0-1)', null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notizen zur Lösung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_history', models.JSONField(default=list, help_text='\n        Historie aller Versuche. Format:\n        [{\n            "attempt": 1,\n            "tier": "tier_1",\n            "llm": "gpt-3.5-turbo",\n            "tokens": 1500,\n            "cost": 0.0015,\n            "success": false,\n            "error": "Tests failed",\n            "timestamp": "2026-01-10T15:00:00Z"\n        }]\n        ')),
                ('llm_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_assignments', to='bfagent.llms')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_assignments', to='bfagent.testrequirement')),
            ],
            options={
                'db_table': 'bug_llm_assignments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'current_tier'], name='bug_llm_ass_status_4244e1_idx'), models.Index(fields=['created_at'], name='bug_llm_ass_created_9340a6_idx')],
            },
        ),
    ]
