# Generated by Django 5.2.6 on 2026-01-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0051_bug_llm_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrequirement',
            name='doc_checked_at',
            field=models.DateTimeField(blank=True, help_text='Wann wurde die Dokumentation zuletzt geprüft?', null=True),
        ),
        migrations.AddField(
            model_name='testrequirement',
            name='doc_files',
            field=models.JSONField(blank=True, default=list, help_text='Liste verknüpfter Dokumentations-Dateien (Pfade)'),
        ),
        migrations.AddField(
            model_name='testrequirement',
            name='doc_notes',
            field=models.TextField(blank=True, help_text='Welche Dokumentation muss erstellt/aktualisiert werden?'),
        ),
        migrations.AddField(
            model_name='testrequirement',
            name='doc_status',
            field=models.CharField(choices=[('not_checked', 'Nicht geprüft'), ('exists', 'Dokumentation vorhanden'), ('needs_update', 'Aktualisierung nötig'), ('needs_creation', 'Neu zu erstellen'), ('updated', 'Aktualisiert'), ('created', 'Erstellt')], default='not_checked', help_text='Status der zugehörigen Dokumentation', max_length=20),
        ),
    ]
