# Generated by Django 5.2.6 on 2026-01-12 06:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0052_add_documentation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangelogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('feature', '✨ Feature'), ('bugfix', '🐛 Bugfix'), ('enhancement', '💡 Enhancement'), ('breaking', '⚠️ Breaking Change'), ('security', '🔒 Security'), ('performance', '⚡ Performance'), ('docs', '📚 Documentation'), ('refactor', '♻️ Refactoring'), ('deprecation', '🗑️ Deprecation')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, help_text='z.B. 2.1.0', max_length=20)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True, help_text='In öffentlichen Release Notes zeigen?')),
                ('is_breaking', models.BooleanField(default=False, help_text='Breaking Change?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changelog_entries', to='bfagent.domainart')),
                ('requirement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changelog_entry', to='bfagent.testrequirement')),
            ],
            options={
                'verbose_name': 'Changelog-Eintrag',
                'verbose_name_plural': 'Changelog-Einträge',
                'db_table': 'documentation_changelog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DomainDocumentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('overview', 'Übersicht'), ('features', 'Features'), ('api', 'API'), ('models', 'Datenmodelle'), ('handlers', 'Handlers'), ('views', 'Views/URLs'), ('templates', 'Templates'), ('changelog', 'Änderungshistorie')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Markdown-Inhalt')),
                ('order', models.IntegerField(default=0, help_text='Sortierung innerhalb der Domain')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation', to='bfagent.domainart')),
            ],
            options={
                'verbose_name': 'Domain-Dokumentation',
                'verbose_name_plural': 'Domain-Dokumentationen',
                'db_table': 'documentation_domain',
                'ordering': ['domain', 'order', 'section'],
                'unique_together': {('domain', 'section')},
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('definition', models.TextField()),
                ('category', models.CharField(blank=True, help_text="z.B. 'Handler', 'Model', 'API'", max_length=50)),
                ('examples', models.TextField(blank=True, help_text='Code-Beispiele oder Anwendungsfälle')),
                ('see_also', models.TextField(blank=True, help_text='Externe Links oder Referenzen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domains', models.ManyToManyField(blank=True, related_name='glossary_terms', to='bfagent.domainart')),
                ('related_terms', models.ManyToManyField(blank=True, to='bfagent.glossaryterm')),
            ],
            options={
                'verbose_name': 'Glossar-Begriff',
                'verbose_name_plural': 'Glossar-Begriffe',
                'db_table': 'documentation_glossary',
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='SystemDocumentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('doc_type', models.CharField(choices=[('architecture', 'Architektur'), ('deployment', 'Deployment'), ('security', 'Sicherheit'), ('performance', 'Performance'), ('integration', 'Integration'), ('api_overview', 'API Übersicht'), ('concept', 'Konzept'), ('guide', 'Anleitung')], max_length=50)),
                ('summary', models.TextField(blank=True, help_text='Kurzzusammenfassung (1-2 Sätze)')),
                ('content', models.TextField(help_text='Markdown-Inhalt')),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_current', models.BooleanField(default=True, help_text='Ist dies die aktuelle Version?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_file', models.CharField(blank=True, help_text='Ursprünglicher MD-Dateipfad (falls importiert)', max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_created', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newer_versions', to='bfagent.systemdocumentation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System-Dokumentation',
                'verbose_name_plural': 'System-Dokumentationen',
                'db_table': 'documentation_system',
                'ordering': ['doc_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DocumentationLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_file', models.CharField(blank=True, help_text='Pfad zu externer MD-Datei (falls nicht in DB)', max_length=500)),
                ('link_type', models.CharField(choices=[('affected', 'Betroffen'), ('updated', 'Aktualisiert'), ('created', 'Neu erstellt'), ('reference', 'Referenz')], default='reference', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Was wurde geändert/ist relevant?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation_links', to='bfagent.testrequirement')),
                ('domain_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_links', to='bfagent.domaindocumentation')),
                ('system_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_links', to='bfagent.systemdocumentation')),
            ],
            options={
                'verbose_name': 'Dokumentations-Verknüpfung',
                'verbose_name_plural': 'Dokumentations-Verknüpfungen',
                'db_table': 'documentation_links',
            },
        ),
    ]
