# Generated by Django 5.2.6 on 2026-01-13 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0058_mcpusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrequirement',
            name='depends_on',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.SET_NULL, 
                related_name='blocks', 
                to='bfagent.testrequirement',
                help_text='Dieses Requirement kann erst gestartet werden, wenn das verknüpfte erledigt ist'
            ),
        ),
    ]
