# Generated by Django 5.2.6 on 2026-01-13 20:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0060_code_refactor_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('patch', 'Patch (Unified Diff)'), ('code_block', 'Code Block'), ('stdout', 'Standard Output'), ('stderr', 'Standard Error'), ('report', 'Report'), ('analysis', 'Analyse-Ergebnis'), ('meta', 'Metadata')], db_index=True, max_length=20)),
                ('file_path', models.CharField(help_text='Relativer Pfad im Workspace', max_length=500)),
                ('content', models.TextField(blank=True, help_text='Inhalt (für kleine Artifacts)')),
                ('sha256', models.CharField(help_text='SHA256 Hash des Inhalts', max_length=64)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Artifact',
                'verbose_name_plural': 'Artifacts',
                'db_table': 'bfagent_autocoding_artifacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutocodingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_text', models.TextField(help_text='Vollständige Aufgabenbeschreibung für LLM')),
                ('repo_url', models.URLField(blank=True, help_text='Git Repository URL')),
                ('base_branch', models.CharField(blank=True, default='main', max_length=100)),
                ('workspace_path', models.CharField(blank=True, help_text='Lokaler Workspace-Pfad', max_length=500)),
                ('complexity', models.CharField(choices=[('S', 'Klein'), ('M', 'Mittel'), ('L', 'Groß')], default='S', max_length=1)),
                ('risk', models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch')], default='low', max_length=10)),
                ('routing_reason', models.CharField(blank=True, help_text='Grund für LLM-Auswahl', max_length=200)),
                ('status', models.CharField(choices=[('created', 'Erstellt'), ('analyzing', 'Analysiert...'), ('planning', 'Plant...'), ('executing', 'Führt aus...'), ('reviewing', 'Wartet auf Review'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen'), ('cancelled', 'Abgebrochen')], db_index=True, default='created', max_length=20)),
                ('current_iteration', models.PositiveIntegerField(default=0)),
                ('max_iterations', models.PositiveIntegerField(default=6)),
                ('error_message', models.TextField(blank=True)),
                ('analysis_result', models.JSONField(blank=True, default=dict, help_text='LLM-Analyse Ergebnis')),
                ('tasks_extracted', models.JSONField(blank=True, default=list, help_text='Extrahierte Tasks')),
                ('total_tokens_input', models.PositiveIntegerField(default=0)),
                ('total_tokens_output', models.PositiveIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Autocoding Run',
                'verbose_name_plural': 'Autocoding Runs',
                'db_table': 'bfagent_autocoding_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(db_index=True, help_text='Name des Tools (z.B. git.clone, build.run)', max_length=100)),
                ('handler_class', models.CharField(blank=True, help_text='Python-Klasse des Handlers', max_length=200)),
                ('args_redacted', models.JSONField(default=dict, help_text='Redaktierte Argumente (keine Secrets)')),
                ('args_sha256', models.CharField(blank=True, help_text='SHA256 Hash der Original-Args', max_length=64)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('ok', models.BooleanField(default=False)),
                ('exit_code', models.IntegerField(default=0)),
                ('stdout_redacted', models.TextField(blank=True, help_text='Redaktierter stdout (max 10KB)')),
                ('stderr_redacted', models.TextField(blank=True, help_text='Redaktierter stderr (max 10KB)')),
                ('stdout_sha256', models.CharField(blank=True, max_length=64)),
                ('stderr_sha256', models.CharField(blank=True, max_length=64)),
                ('artifacts_meta', models.JSONField(blank=True, default=dict, help_text='Metadaten zu erstellten Artifacts')),
                ('policy_events', models.JSONField(blank=True, default=dict, help_text='Policy-Checks und Events')),
            ],
            options={
                'verbose_name': 'Tool Call',
                'verbose_name_plural': 'Tool Calls',
                'db_table': 'bfagent_autocoding_tool_calls',
                'ordering': ['started_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='coderefactorsession',
            new_name='bfagent_cod_require_733bb2_idx',
            old_name='bfagent_cod_require_idx',
        ),
        migrations.RenameIndex(
            model_name='coderefactorsession',
            new_name='bfagent_cod_file_pa_793cd4_idx',
            old_name='bfagent_cod_file_pa_idx',
        ),
        migrations.RenameIndex(
            model_name='coderefactorsession',
            new_name='bfagent_cod_status_6f9570_idx',
            old_name='bfagent_cod_status_idx',
        ),
        migrations.RenameIndex(
            model_name='initiative',
            new_name='bfagent_ini_status_35495b_idx',
            old_name='bfagent_ini_status_idx',
        ),
        migrations.RenameIndex(
            model_name='initiative',
            new_name='bfagent_ini_domain_87cd3c_idx',
            old_name='bfagent_ini_domain_idx',
        ),
        migrations.RenameIndex(
            model_name='initiativeactivity',
            new_name='bfagent_ini_initiat_9c08b4_idx',
            old_name='bfagent_ini_init_created_idx',
        ),
        migrations.RenameIndex(
            model_name='initiativeactivity',
            new_name='bfagent_ini_action_b0c8a9_idx',
            old_name='bfagent_ini_action_idx',
        ),
        migrations.RenameIndex(
            model_name='initiativeactivity',
            new_name='bfagent_ini_mcp_too_f87d63_idx',
            old_name='bfagent_ini_mcp_tool_idx',
        ),
        migrations.RenameIndex(
            model_name='mcpusagelog',
            new_name='bfagent_mcp_tool_na_3ce7dc_idx',
            old_name='bfagent_mcp_tool_na_8e9f4a_idx',
        ),
        migrations.RenameIndex(
            model_name='mcpusagelog',
            new_name='bfagent_mcp_tool_ca_2def60_idx',
            old_name='bfagent_mcp_tool_ca_b2c3d4_idx',
        ),
        migrations.RenameIndex(
            model_name='mcpusagelog',
            new_name='bfagent_mcp_status_38494f_idx',
            old_name='bfagent_mcp_status_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='mcpusagelog',
            new_name='bfagent_mcp_session_3d69a8_idx',
            old_name='bfagent_mcp_session_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='mcpusagelog',
            new_name='bfagent_mcp_created_eb2b09_idx',
            old_name='bfagent_mcp_created_g7h8i9_idx',
        ),
        migrations.AddField(
            model_name='artifact',
            name='refactor_session',
            field=models.ForeignKey(blank=True, help_text='Automatisch erstellte Refactor-Session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='bfagent.coderefactorsession'),
        ),
        migrations.AddField(
            model_name='autocodingrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autocoding_runs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autocodingrun',
            name='llm',
            field=models.ForeignKey(blank=True, help_text='Verwendetes LLM', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bfagent.llms'),
        ),
        migrations.AddField(
            model_name='autocodingrun',
            name='requirement',
            field=models.ForeignKey(help_text='Verknüpftes Requirement aus Test Studio', on_delete=django.db.models.deletion.CASCADE, related_name='autocoding_runs', to='bfagent.testrequirement'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='bfagent.autocodingrun'),
        ),
        migrations.AddField(
            model_name='toolcall',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='bfagent.autocodingrun'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='tool_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='bfagent.toolcall'),
        ),
        migrations.AddIndex(
            model_name='autocodingrun',
            index=models.Index(fields=['status', 'created_at'], name='bfagent_aut_status_82d819_idx'),
        ),
        migrations.AddIndex(
            model_name='autocodingrun',
            index=models.Index(fields=['requirement', 'status'], name='bfagent_aut_require_c16ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='toolcall',
            index=models.Index(fields=['run', 'tool_name'], name='bfagent_aut_run_id_d10546_idx'),
        ),
        migrations.AddIndex(
            model_name='toolcall',
            index=models.Index(fields=['started_at'], name='bfagent_aut_started_22134b_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['run', 'kind'], name='bfagent_aut_run_id_1b417e_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['sha256'], name='bfagent_aut_sha256_d2fa66_idx'),
        ),
    ]
