# Generated by Django 5.2.6 on 2026-01-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0061_autocoding_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegatedtask',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='delegatedtask',
            name='llm_selected',
        ),
        migrations.RemoveField(
            model_name='delegatedtask',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='taskexecutionlog',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskfeedback',
            name='task',
        ),
        migrations.DeleteModel(
            name='RoutingAnalytics',
        ),
        migrations.DeleteModel(
            name='TaskExecutionLog',
        ),
        migrations.DeleteModel(
            name='DelegatedTask',
        ),
        migrations.DeleteModel(
            name='TaskFeedback',
        ),
    ]
