# Generated by Django 5.2.6 on 2026-01-15 15:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0062_controlling_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert_type', models.CharField(choices=[('budget_warning', 'Budget Warnung'), ('budget_exceeded', 'Budget überschritten'), ('error_rate_high', 'Hohe Fehlerrate'), ('latency_high', 'Hohe Latenz'), ('fallback_frequent', 'Häufige Fallbacks')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warnung'), ('critical', 'Kritisch')], default='warning', max_length=20)),
                ('message', models.TextField(help_text='Alert-Nachricht')),
                ('threshold_value', models.FloatField(help_text='Schwellwert der überschritten wurde', null=True)),
                ('actual_value', models.FloatField(help_text='Tatsächlicher Wert', null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Controlling Alert',
                'verbose_name_plural': 'Controlling Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ControllingBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metric_type', models.CharField(db_index=True, help_text="Metrik-Typ (z.B. 'django_errors', 'llm_cost', 'quality')", max_length=50)),
                ('period_days', models.IntegerField(default=30, help_text='Zeitraum der Messung in Tagen')),
                ('data', models.JSONField(help_text='Baseline-Daten als JSON')),
                ('description', models.TextField(blank=True, help_text='Beschreibung der Baseline', null=True)),
            ],
            options={
                'verbose_name': 'Controlling Baseline',
                'verbose_name_plural': 'Controlling Baselines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='agent_class',
            field=models.CharField(blank=True, help_text='Python-Pfad zum ausführenden Agent: apps.bfagent.agents.ResearchAgent', max_length=200),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='allowed_tools',
            field=models.JSONField(blank=True, default=list, help_text='Pre-approved Tools: ["Bash(git:*)", "Read", "Write", "WebSearch"]'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='author',
            field=models.CharField(blank=True, help_text='Skill-Autor oder Team', max_length=100),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='compatibility',
            field=models.CharField(blank=True, help_text="Umgebungsanforderungen (z.B. 'Requires internet access, Python 3.8+')", max_length=500),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='license',
            field=models.CharField(blank=True, default='Proprietary', help_text="Lizenz für diesen Skill (z.B. 'Apache-2.0', 'MIT', 'Proprietary')", max_length=100),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='references',
            field=models.JSONField(blank=True, default=dict, help_text='Referenz-Dokumente: {"REFERENCE": "...", "FORMS": "...", "domain": "..."}'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='skill_description',
            field=models.TextField(blank=True, help_text="Kurzbeschreibung mit Keywords für Auto-Matching (1-1024 chars). AgentSkills.io 'description' field für Trigger-Erkennung."),
        ),
        migrations.CreateModel(
            name='AgentValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent', models.CharField(db_index=True, help_text="Agent-Name (z.B. 'DjangoAgent')", max_length=50)),
                ('action', models.CharField(help_text="Validierungs-Aktion (z.B. 'validate_python_file')", max_length=50)),
                ('passed', models.BooleanField(help_text='Validierung bestanden (keine Fehler)?')),
                ('errors_count', models.IntegerField(default=0, help_text='Anzahl gefundener Fehler')),
                ('warnings_count', models.IntegerField(default=0, help_text='Anzahl gefundener Warnungen')),
                ('errors_prevented', models.JSONField(default=list, help_text='Liste der verhinderten Fehler (Rule + Message)')),
                ('file_path', models.CharField(blank=True, help_text='Geprüfte Datei', max_length=500, null=True)),
                ('cascade_session_id', models.CharField(blank=True, help_text='Cascade Session ID für Zuordnung', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Agent Validation Log',
                'verbose_name_plural': 'Agent Validation Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'agent'], name='bfagent_age_timesta_8b9ad0_idx'), models.Index(fields=['agent', 'action'], name='bfagent_age_agent_286b27_idx')],
            },
        ),
        migrations.CreateModel(
            name='LLMUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent', models.CharField(db_index=True, help_text="Agent-Name (z.B. 'DjangoAgent', 'DocAgent', 'direct')", max_length=50)),
                ('task', models.CharField(help_text="Task-Name (z.B. 'validate_view', 'translate_docstring')", max_length=100)),
                ('model', models.CharField(db_index=True, help_text="Model-Name (z.B. 'gpt-4o', 'llama-3.1-8b')", max_length=50)),
                ('provider', models.CharField(default='unknown', help_text="Provider (z.B. 'openai', 'groq', 'gemini')", max_length=30)),
                ('tokens_in', models.IntegerField(default=0, help_text='Input Tokens')),
                ('tokens_out', models.IntegerField(default=0, help_text='Output Tokens')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Kosten in USD', max_digits=10)),
                ('latency_ms', models.FloatField(default=0.0, help_text='Latenz in Millisekunden')),
                ('cached', models.BooleanField(default=False, help_text='Aus Cache beantwortet?')),
                ('fallback_used', models.BooleanField(default=False, help_text='Fallback-Model verwendet?')),
                ('success', models.BooleanField(default=True, help_text='Erfolgreich abgeschlossen?')),
                ('error_message', models.TextField(blank=True, help_text='Fehlermeldung bei Fehler', null=True)),
                ('request_hash', models.CharField(blank=True, db_index=True, help_text='Hash des Requests für Deduplizierung', max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'LLM Usage Log',
                'verbose_name_plural': 'LLM Usage Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'agent'], name='bfagent_llm_timesta_cc1711_idx'), models.Index(fields=['timestamp', 'model'], name='bfagent_llm_timesta_72a149_idx'), models.Index(fields=['agent', 'task'], name='bfagent_llm_agent_08aaf8_idx')],
            },
        ),
    ]
