# Generated by Django 5.2.6 on 2026-01-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0064_usage_tracking_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='djangogenerationerror',
            new_name='bfagent_dja_timesta_012de4_idx',
            old_name='bfagent_dja_timesta_idx01',
        ),
        migrations.RenameIndex(
            model_name='djangogenerationerror',
            new_name='bfagent_dja_error_t_1bb280_idx',
            old_name='bfagent_dja_error_t_idx02',
        ),
        migrations.RenameIndex(
            model_name='djangogenerationerror',
            new_name='bfagent_dja_source_b58ff8_idx',
            old_name='bfagent_dja_source_idx03',
        ),
        migrations.RenameIndex(
            model_name='toolusagelog',
            new_name='bfagent_too_timesta_39e569_idx',
            old_name='bfagent_too_timesta_idx01',
        ),
        migrations.RenameIndex(
            model_name='toolusagelog',
            new_name='bfagent_too_caller__0fbc69_idx',
            old_name='bfagent_too_caller__idx02',
        ),
        migrations.RenameIndex(
            model_name='toolusagelog',
            new_name='bfagent_too_tool_na_24f22e_idx',
            old_name='bfagent_too_tool_na_idx03',
        ),
        migrations.RenameIndex(
            model_name='toolusagelog',
            new_name='bfagent_too_app_lab_5b4f21_idx',
            old_name='bfagent_too_app_lab_idx04',
        ),
        migrations.AlterField(
            model_name='toolusagelog',
            name='tool_category',
            field=models.CharField(blank=True, db_index=True, help_text="Tool category (e.g., 'code_quality', 'generation')", max_length=50, null=True),
        ),
    ]
