# Generated by Django 5.2.6 on 2026-01-16 07:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0065_terminal_error_capture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('process_name', models.CharField(help_text='z.B. runserver, pytest, npm', max_length=100)),
                ('command', models.TextField(blank=True, help_text='Vollständiger Befehl')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('log_file', models.CharField(help_text='Pfad zur JSONL Log-Datei', max_length=500)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('crashed', 'Crashed')], default='running', max_length=20)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('total_lines', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Terminal Session',
                'verbose_name_plural': 'Terminal Sessions',
                'db_table': 'bfagent_terminal_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TerminalError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_hash', models.CharField(help_text='SHA256 für Deduplizierung', max_length=64, unique=True)),
                ('error_type', models.CharField(choices=[('import_error', 'Import Error'), ('template_error', 'Template Error'), ('syntax_error', 'Syntax Error'), ('database_error', 'Database Error'), ('url_error', 'URL/Routing Error'), ('attribute_error', 'Attribute Error'), ('type_error', 'Type Error'), ('value_error', 'Value Error'), ('key_error', 'Key Error'), ('runtime_error', 'Runtime Error'), ('npm_error', 'NPM/Node Error'), ('browser_error', 'Browser/JS Error'), ('other', 'Other')], default='other', max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('source', models.CharField(choices=[('django', 'Django'), ('python', 'Python'), ('npm', 'NPM/Node'), ('browser', 'Browser Console'), ('test', 'Test Runner'), ('migration', 'Migration'), ('other', 'Other')], default='django', max_length=50)),
                ('error_class', models.CharField(blank=True, help_text='z.B. ImportError, TemplateDoesNotExist', max_length=100)),
                ('message', models.TextField(help_text='Fehlermeldung')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('column_number', models.IntegerField(blank=True, null=True)),
                ('function_name', models.CharField(blank=True, max_length=200, null=True)),
                ('code_snippet', models.TextField(blank=True, help_text='Code um die Fehlerzeile', null=True)),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('raw_output', models.TextField(help_text='Original Terminal-Output')),
                ('occurrence_count', models.IntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('analyzing', 'AI Analyzing'), ('ready', 'Fix Ready'), ('in_progress', 'Fix In Progress'), ('fixed', 'Fixed'), ('verified', 'Verified'), ('ignored', 'Ignored'), ('wont_fix', "Won't Fix")], default='new', max_length=20)),
                ('ai_analysis', models.TextField(blank=True, help_text='KI-Analyse des Fehlers', null=True)),
                ('ai_solution_steps', models.JSONField(blank=True, default=list, help_text='Liste der Lösungsschritte von der KI')),
                ('ai_confidence', models.FloatField(blank=True, help_text='Konfidenz der KI (0-1)', null=True)),
                ('ai_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_terminal_errors', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to='bfagent.terminalsession')),
            ],
            options={
                'verbose_name': 'Terminal Error',
                'verbose_name_plural': 'Terminal Errors',
                'db_table': 'bfagent_terminal_errors',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='TerminalErrorFixAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(help_text='Beschreibung was gemacht wurde')),
                ('files_changed', models.JSONField(default=list, help_text='Liste der geänderten Dateien')),
                ('used_ai_suggestion', models.BooleanField(default=False)),
                ('ai_step_followed', models.IntegerField(blank=True, help_text='Welcher KI-Schritt befolgt wurde', null=True)),
                ('result', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='success', max_length=20)),
                ('result_notes', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_method', models.CharField(blank=True, help_text="z.B. 'rerun', 'test', 'manual'", max_length=50, null=True)),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fix_attempts', to='bfagent.terminalerror')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_fix_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fix Attempt',
                'verbose_name_plural': 'Fix Attempts',
                'db_table': 'bfagent_terminal_fix_attempts',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='terminalerror',
            index=models.Index(fields=['status', 'severity'], name='bfagent_ter_status_7eb702_idx'),
        ),
        migrations.AddIndex(
            model_name='terminalerror',
            index=models.Index(fields=['error_type', 'source'], name='bfagent_ter_error_t_03cf4b_idx'),
        ),
        migrations.AddIndex(
            model_name='terminalerror',
            index=models.Index(fields=['first_seen'], name='bfagent_ter_first_s_b34ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='terminalerror',
            index=models.Index(fields=['last_seen'], name='bfagent_ter_last_se_60d157_idx'),
        ),
    ]
