# Generated by Django 5.2.6 on 2026-01-16 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0066_orchestration_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrchestrationCall',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, help_text='Session-ID für Gruppierung', max_length=100)),
                ('sequence', models.IntegerField(default=0, help_text='Reihenfolge innerhalb des Parents')),
                ('depth', models.IntegerField(default=0, help_text='Tiefe in der Hierarchie (0 = Root)')),
                ('call_type', models.CharField(choices=[('request', 'Request Received'), ('planning', 'Task Planning'), ('routing', 'Task Routing'), ('execution', 'Task Execution'), ('llm_call', 'LLM Call'), ('tool_call', 'Tool Call'), ('result', 'Result Returned')], db_index=True, max_length=20)),
                ('name', models.CharField(help_text="Name des Calls (z.B. 'generate_django_view')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Beschreibung/Input')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('result_summary', models.TextField(blank=True, help_text='Kurze Zusammenfassung des Ergebnisses')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('tokens_in', models.IntegerField(blank=True, null=True)),
                ('tokens_out', models.IntegerField(blank=True, null=True)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Zusätzliche Metadaten')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent-Call in der Hierarchie', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bfagent.orchestrationcall')),
            ],
            options={
                'verbose_name': 'Orchestration Call',
                'verbose_name_plural': 'Orchestration Calls',
                'ordering': ['session_id', 'depth', 'sequence'],
                'indexes': [models.Index(fields=['session_id', 'started_at'], name='bfagent_orc_session_54c9bc_idx'), models.Index(fields=['call_type', 'status'], name='bfagent_orc_call_ty_b3d82f_idx'), models.Index(fields=['parent', 'sequence'], name='bfagent_orc_parent__1a327c_idx')],
            },
        ),
    ]
