# Generated by Django 5.2.6 on 2026-01-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0067_add_orchestration_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmusagelog',
            name='context_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Zusätzliche Metadaten: file_path, task_type, etc.'),
        ),
        migrations.AddField(
            model_name='llmusagelog',
            name='prompt_text',
            field=models.TextField(blank=True, help_text='Der gesendete Prompt (gekürzt auf 2000 Zeichen)', null=True),
        ),
        migrations.AddField(
            model_name='llmusagelog',
            name='response_text',
            field=models.TextField(blank=True, help_text='Die LLM-Antwort (gekürzt auf 4000 Zeichen)', null=True),
        ),
    ]
