# Generated by Django 5.2.6 on 2026-01-16 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0068_add_llm_content_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmusagelog',
            name='orchestration_call',
            field=models.ForeignKey(blank=True, help_text='Zugehöriger Orchestration-Call', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_calls', to='bfagent.orchestrationcall'),
        ),
        migrations.AddField(
            model_name='llmusagelog',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, help_text='Session-ID für Gruppierung zusammengehöriger Calls', max_length=100, null=True),
        ),
    ]
