# Generated by Django 5.2.6 on 2026-01-22 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0070_add_screenshot_to_testrequirement'),
        ('writing_hub', '0035_book_series_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookprojects',
            name='series',
            field=models.ForeignKey(blank=True, help_text='Buchreihe/Universe, zu der dieses Projekt gehört', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='writing_hub.bookseries'),
        ),
        migrations.AddField(
            model_name='bookprojects',
            name='series_order',
            field=models.PositiveIntegerField(blank=True, help_text='Position in der Reihe (Band 1, 2, 3...)', null=True),
        ),
    ]
