# Generated by Django 6.0 on 2025-12-11 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(
                        help_text="Unique customer identifier (e.g., MEDTECH_DE)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(help_text="Customer display name", max_length=200),
                ),
                (
                    "dashboard_access",
                    models.BooleanField(default=True, help_text="Allow dashboard access"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medtrans_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Translation Customer",
                "verbose_name_plural": "Medical Translation Customers",
                "db_table": "medtrans_customers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Presentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "pptx_file",
                    models.FileField(
                        help_text="PowerPoint file to translate",
                        upload_to="medtrans/presentations/",
                    ),
                ),
                (
                    "source_language",
                    models.CharField(
                        choices=[
                            ("de", "German"),
                            ("en", "English"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                        ],
                        default="de",
                        max_length=10,
                    ),
                ),
                (
                    "target_language",
                    models.CharField(
                        choices=[
                            ("de", "German"),
                            ("en", "English"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("extracting", "Extracting Texts"),
                            ("translating", "Translating"),
                            ("reviewing", "In Review"),
                            ("completed", "Completed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "total_texts",
                    models.IntegerField(default=0, help_text="Total number of extracted texts"),
                ),
                (
                    "translated_texts",
                    models.IntegerField(default=0, help_text="Number of translated texts"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presentations",
                        to="medtrans.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presentation",
                "verbose_name_plural": "Presentations",
                "db_table": "medtrans_presentations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PresentationText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slide_number", models.IntegerField(help_text="Slide number in presentation")),
                (
                    "text_id",
                    models.CharField(
                        help_text="Unique text identifier (e.g., slide_1_text_3)", max_length=100
                    ),
                ),
                ("original_text", models.TextField(help_text="Original text from PowerPoint")),
                ("translated_text", models.TextField(blank=True, help_text="Translated text")),
                (
                    "translation_method",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("deepl", "DeepL"),
                            ("manual", "Manual"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "manually_edited",
                    models.BooleanField(default=False, help_text="Was manually edited"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "presentation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="texts",
                        to="medtrans.presentation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presentation Text",
                "verbose_name_plural": "Presentation Texts",
                "db_table": "medtrans_presentation_texts",
                "ordering": ["presentation", "slide_number", "text_id"],
                "indexes": [
                    models.Index(
                        fields=["presentation", "slide_number"],
                        name="medtrans_pr_present_a431bb_idx",
                    ),
                    models.Index(
                        fields=["presentation", "translation_method"],
                        name="medtrans_pr_present_296fd2_idx",
                    ),
                ],
                "unique_together": {("presentation", "text_id")},
            },
        ),
    ]
