# Generated by Django 5.2.10 on 2026-01-23 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("arrival_date", models.DateField()),
                ("departure_date", models.DateField()),
                (
                    "accommodation_type",
                    models.CharField(
                        choices=[
                            ("hotel", "Hotel"),
                            ("airbnb", "Airbnb/Ferienwohnung"),
                            ("hostel", "Hostel"),
                            ("camping", "Camping"),
                            ("friends", "Bei Freunden"),
                            ("resort", "Resort"),
                            ("cruise", "Kreuzfahrtschiff"),
                            ("other", "Sonstiges"),
                        ],
                        default="hotel",
                        max_length=20,
                    ),
                ),
                ("accommodation_name", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "base_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trip_stops",
                        to="locations.baselocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stopp",
                "verbose_name_plural": "Stopps",
                "ordering": ["order", "arrival_date"],
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "trip_type",
                    models.CharField(
                        choices=[
                            ("city", "Städtereise"),
                            ("beach", "Strandurlaub"),
                            ("wellness", "Wellness"),
                            ("backpacking", "Backpacking"),
                            ("business", "Geschäftsreise"),
                            ("family", "Familienurlaub"),
                            ("adventure", "Abenteuerreise"),
                            ("cruise", "Kreuzfahrt"),
                        ],
                        default="city",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("ready", "Bereit zur Generierung"),
                            ("generating", "Story wird generiert"),
                            ("completed", "Abgeschlossen"),
                            ("archived", "Archiviert"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("origin", models.CharField(help_text="Startort", max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("total_reading_minutes", models.PositiveIntegerField(default=0)),
                ("recommended_chapters", models.PositiveIntegerField(default=0)),
                ("recommended_words", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reise",
                "verbose_name_plural": "Reisen",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transport_type",
                    models.CharField(
                        choices=[
                            ("flight", "Flugzeug"),
                            ("train", "Zug"),
                            ("bus", "Bus"),
                            ("car_driver", "Auto (Fahrer)"),
                            ("car_passenger", "Auto (Beifahrer)"),
                            ("ferry", "Fähre"),
                            ("other", "Sonstiges"),
                        ],
                        default="flight",
                        max_length=20,
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        help_text="Gesamte Reisezeit in Minuten"
                    ),
                ),
                ("departure_datetime", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_stop",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = von Origin",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departures",
                        to="trips.stop",
                    ),
                ),
                (
                    "to_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrivals",
                        to="trips.stop",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transports",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transport",
                "verbose_name_plural": "Transporte",
                "ordering": ["departure_datetime"],
            },
        ),
        migrations.AddField(
            model_name="stop",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stops",
                to="trips.trip",
            ),
        ),
    ]
