# Generated by Django 5.2.10 on 2026-01-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stop",
            name="notes",
            field=models.TextField(blank=True, help_text="Notizen zum Aufenthalt"),
        ),
    ]
