# =============================================================================
# Hub Language Identity System — Django Integration Guide (ADR-052)
# =============================================================================

# ── 1. settings/base.py ──────────────────────────────────────────────────────

USE_I18N = True
USE_L10N = True
LANGUAGE_CODE = "de"  # Hub default — override per request via middleware

LANGUAGES = [
    ("de", "Deutsch"),
    ("en", "English"),
]

# Hub-specific locale directory (generated by voice_dna/pipeline.py)
# Place generated_po/{hub}/locale/ content here:
LOCALE_PATHS = [
    BASE_DIR / "locale",  # Contains de/LC_MESSAGES/django.po + en/LC_MESSAGES/django.po
]

MIDDLEWARE = [
    # ... other middleware ...
    "django.middleware.locale.LocaleMiddleware",  # Must be after SessionMiddleware
    # ...
]


# ── 2. In templates: use msgid keys ──────────────────────────────────────────
"""
{% load i18n %}

{# Primary CTA — hub-specific text from voice DNA #}
<button class="btn-primary pui-interactive pui-lift pui-focus-visible"
        hx-post="{% url 'tenders:create' %}"
        hx-target="#main-content">
    {% trans "cta.primary" %}
</button>

{# Status messages #}
<div class="htmx-indicator" id="page-loading">
    {% trans "status.loading" %}
</div>

{# Error messages — contextual, not generic #}
{% if form.errors %}
<div role="alert" class="border border-danger rounded p-4 text-sm">
    {% trans "error.validation" %}
</div>
{% endif %}

{# Confirmation dialog #}
<dialog id="confirm-delete">
    <p>{% trans "dialog.confirm_delete" %}</p>
    <button hx-delete="{{ object.get_delete_url }}"
            hx-confirm="">
        {% trans "cta.delete" %}
    </button>
    <button>{% trans "cta.cancel" %}</button>
</dialog>
"""


# ── 3. Django view context — optional programmatic access ────────────────────
"""
# apps/core/copy.py — Optional helper for accessing copy in views/services

from django.utils.translation import gettext as _

class HubCopy:
    '''Typed access to hub micro-copy for use in Python code (not templates).'''

    @staticmethod
    def cta_primary() -> str:
        return _("cta.primary")

    @staticmethod
    def toast_saved() -> str:
        return _("toast.saved")

    @staticmethod
    def error_generic() -> str:
        return _("error.generic")

    # ... etc.

# Usage in views.py (service layer calls HubCopy for toast messages):
from apps.core.copy import HubCopy

def tender_create(request):
    ...
    response["HX-Trigger"] = json.dumps({
        "showToast": {"level": "success", "message": HubCopy.toast_saved()}
    })
    return response
"""


# ── 4. Deployment: after running make generate-voice ─────────────────────────
"""
# Copy generated locale files into each hub:
cp -r generated_po/bieterpilot/locale/ bieterpilot/locale/

# Compile:
cd bieterpilot && python manage.py compilemessages

# Or use make:
make compile-messages
"""


# ── 5. Language switching (optional — for multi-language hubs) ────────────────
"""
# urls.py
from django.conf.urls.i18n import i18n_patterns

urlpatterns += i18n_patterns(
    path("", include("apps.core.urls")),
    prefix_default_language=False,  # /de/... and /... (not /en/...)
)

# Template language switcher:
{% load i18n %}
{% get_available_languages as LANGUAGES %}
{% get_current_language as LANGUAGE_CODE %}

<nav aria-label="{% trans 'nav.settings' %}" class="flex gap-2">
    {% for lang_code, lang_name in LANGUAGES %}
        {% language lang_code %}
        <a href="{{ request.path }}"
           class="text-sm {% if lang_code == LANGUAGE_CODE %}text-primary font-medium{% else %}text-muted{% endif %}
                  pui-interactive">
            {{ lang_code|upper }}
        </a>
        {% endlanguage %}
    {% endfor %}
</nav>
"""
