# Generated by Django 5.2.6 on 2025-09-29 15:30

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        # REMOVED: CreateModel 'Agents' (table 'agents' already exists)
        # REMOVED: CreateModel 'BookProjects' (table 'book_projects' already exists)
        # REMOVED: CreateModel 'BookTypes' (table 'book_types' already exists)
        # REMOVED: CreateModel 'Llms' (table 'llms' already exists)
        # REMOVED: CreateModel 'AgentExecutions' (table 'agent_executions' already exists)
        # REMOVED: CreateModel 'AgentArtifacts' (table 'agent_artifacts' already exists)
        # REMOVED: CreateModel 'Characters' (table 'characters' already exists)
        # REMOVED: CreateModel 'BookChapters' (table 'book_chapters' already exists)
        # The CreateModel operations have been removed because tables already exist

    ]
