# Generated by Django 5.2.6 on 2025-09-30 07:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0002_agent_artifacts"),
    ]

    operations = [
        # REMOVED: AlterField operations for Llms model
        # These fields already have the correct type in the database
        # Since CreateModel for Llms was removed from 0001, these operations would fail
    ]
