# Generated by Django 5.2.6 on 2025-09-30 12:17

from django.db import migrations

import apps.bfagent.utils.crud_config


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0003_alter_llms_api_endpoint_alter_llms_api_key_and_more"),
    ]

    operations = [
        # REMOVED: CreateModel 'Worlds' (table 'worlds' already exists)
        # The CreateModel operations have been removed because tables already exist

    ]
