# Generated by Django 5.2.6 on 2025-09-30 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0004_worlds"),
    ]

    operations = []
