# Generated by Django 5.2.6 on 2025-09-30 12:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0005_auto_20250930_1417"),
    ]

    operations = [
        # Empty migration - Worlds table already exists from 0004_worlds
    ]
