# Generated by Django 5.2.6 on 2025-09-30 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0006_auto_20250930_1417"),
    ]

    operations = [
        # REMOVED: RenameField operations for BookTypes model (3 operations)
        # REMOVED: AddField operations for BookTypes model (4 operations)
        # REMOVED: AlterField operations for BookProjects model (2 operations)
        # These operations would fail because CreateModel for BookTypes and BookProjects
        # were removed from 0001_initial.py (tables already existed)
        # The database already has the correct schema
    ]
