# Generated by Django 5.2.6 on 2025-09-30 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0007_fix_text_fields"),
    ]

    operations = [
        # REMOVED: AddField operations for BookChapters model (5 operations)
        # REMOVED: AddIndex operations for BookChapters model (3 operations)
        # These operations would fail because CreateModel for BookChapters
        # was removed from 0001_initial.py (table already existed)
        # The database already has the correct schema with all fields and indexes
    ]
