# Generated by Django 5.2.6 on 2025-09-30 16:55

from django.db import migrations

import apps.bfagent.utils.crud_config


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0008_enhance_bookchapters_phase1a"),
    ]

    operations = [
        # REMOVED: CreateModel 'PlotPoint' (table 'plot_points' already exists)
        # REMOVED: CreateModel 'StoryArc' (table 'story_arcs' already exists)
        # The CreateModel operations have been removed because tables already exist

    ]
