# Generated by Django 5.2.6 on 2025-10-01 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0009_add_story_arc_and_plot_points_phase1b"),
    ]

    operations = [
        # REMOVED: AddField operations for BookChapters model (7 operations)
        # These operations would fail because CreateModel for BookChapters
        # was removed from 0001_initial.py (table already existed)
        # The database already has the correct schema with all AI chapter fields
    ]
