# Generated by Django 5.2.6 on 2025-10-02 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0010_add_ai_chapter_fields"),
    ]

    operations = [
        # REMOVED: CreateModel 'FieldUsage' (table 'graphql_field_usage' already exists)
        # REMOVED: CreateModel 'GraphQLOperation' (table 'graphql_operations' already exists)
        # REMOVED: CreateModel 'QueryPerformanceLog' (table 'graphql_performance_logs' already exists)
        # The CreateModel operations have been removed because tables already exist

    ]
