# Generated by Django 5.2.6 on 2025-10-07 09:21
# Master Data Models for Dropdowns and Reference Data

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0013_add_master_data_models"),
    ]

    operations = [
        # REMOVED: CreateModel 'Genre' (table 'genres' already exists)
        # REMOVED: CreateModel 'TargetAudience' (table 'target_audiences' already exists)
        # REMOVED: CreateModel 'WritingStatus' (table 'writing_statuses' already exists)
        # The CreateModel operations have been removed because tables already exist

    ]
