# Generated by Django 5.2.6 on 2025-10-07 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0014_add_master_data_models"),
    ]

    operations = [
        # REMOVED: CreateModel 'WorkflowPhase' (table 'workflow_phases' already exists)
        # REMOVED: CreateModel 'WorkflowPhaseStep' (table 'workflow_phase_steps' already exists)
        # REMOVED: CreateModel 'WorkflowTemplate' (table 'workflow_templates' already exists)
        # REMOVED: CreateModel 'PhaseActionConfig' (table 'phase_action_configs' already exists)
        # REMOVED: CreateModel 'ProjectPhaseHistory' (table 'project_phase_history' already exists)
        # The CreateModel operations have been removed because tables already exist

    ]
