# Generated by Django 5.2.6 on 2025-10-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bfagent", "0015_add_workflow_engine_system"),
    ]

    operations = [
        # REMOVED: CreateModel 'PromptTemplate' (table 'prompt_templates' already exists)
        # The CreateModel operations have been removed because tables already exist

    ]
