# Generated by Django 5.2.6 on 2025-10-09 07:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0016_prompttemplate_agents_active_prompt"),
    ]

    operations = [
        # REMOVED: CreateModel 'PhaseAgentConfig' (table 'phase_agent_configs' already exists)
        # The entire CreateModel operation has been removed because the table already exists
    ]
