# Generated by Django 5.2.6 on 2025-10-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bfagent", "0018_drop_old_phase_action_configs"),
    ]

    operations = [
        # REMOVED: CreateModel 'AgentAction' (table 'agent_actions' already exists)
        # REMOVED: CreateModel 'EnrichmentResponse' (table 'enrichment_responses' already exists)
        # The CreateModel operations have been removed because tables already exist

    ]
