# Generated by Django 5.2.6 on 2025-10-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bfagent", "0020_create_phase_action_config_table"),
    ]

    operations = [
        # REMOVED: All operations for AgentType, EnrichmentResponse, and AgentAction
        # - 10 RemoveField operations for EnrichmentResponse
        # - 2 AddField operations for AgentAction
        # - 13 AddField operations for EnrichmentResponse
        # - 2 AlterField operations for EnrichmentResponse
        # - 3 AddIndex operations for EnrichmentResponse
        # These models were created in earlier migrations or already exist in the database
        # Attempting to modify fields on models not in migration state would cause KeyError
        # The database already has the correct schema with all fields and indexes
    ]
