# Generated by Django 5.2.6 on 2025-10-13 14:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bfagent", "0021_agenttype_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # REMOVED: CreateModel 'FieldDefinition' (table 'field_definitions' already exists)
        # REMOVED: CreateModel 'FieldGroup' (table 'field_groups' already exists)
        # REMOVED: CreateModel 'FieldTemplate' (table 'field_templates' already exists)
        # REMOVED: CreateModel 'FieldValueHistory' (table 'field_value_history' already exists)
        # REMOVED: CreateModel 'ProjectFieldValue' (table 'project_field_values' already exists)
        # REMOVED: CreateModel 'TemplateField' (table 'template_fields' already exists)
        # The CreateModel operations have been removed because tables already exist

    ]
