# Generated by Django 5.2.6 on 2025-10-13 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bfagent", "0022_agenttype_fielddefinition_fieldgroup_fieldtemplate_and_more"),
    ]

    operations = [
        # REMOVED: CreateModel 'BookTypePhase' (table 'book_type_phases' already exists)
        # The CreateModel operations have been removed because tables already exist

    ]
