# Generated by Django 5.2.6 on 2025-10-14 06:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0023_agenttype_booktypephase_and_more"),
    ]

    operations = [
        # REMOVED: CreateModel 'ActionTemplate' (table 'action_templates' already exists)
        # REMOVED: AgentType CreateModel (table already exists from previous migration)
        # REMOVED: RemoveIndex operations (indexes may not exist)
        # The CreateModel operations have been removed because tables already exist

    ]
