# Generated by Django 5.2.6 on 2025-10-15 11:20

from django.db import migrations

import apps.bfagent.utils.crud_config


class Migration(migrations.Migration):

    dependencies = [("bfagent", "0024_actiontemplate_agenttype_and_more")]

    operations = [
        # AUTO-REMOVED: Operations on models not in migration state
        # These models exist in database but were removed from 0001_initial.py
        # Affected models: agentaction, agentartifacts, agentexecutions, agents, bookchapters, bookprojects, booktypes, characters, enrichmentresponse, llms
    ]
