# Generated by Django 5.2.6 on 2025-10-16 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0029_add_llm_tracking_to_enrichment_response"),
    ]

    operations = [
        # AUTO-REMOVED: Operations on models not in migration state
        # These models exist in database but were removed from 0001_initial.py
        # Affected models: agentaction, agentartifacts, agentexecutions, agents, bookchapters, bookprojects, booktypes, characters, enrichmentresponse, llms

    ]
