# Generated by Django 5.2.6 on 2025-10-17 08:21

import apps.bfagent.utils.crud_config
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bfagent", "0033_initial")    ]

    operations = [
        # AUTO-REMOVED: Operations on models not in migration state
        # These models exist in database but were removed from 0001_initial.py
        # Affected models: agentaction, agentartifacts, agentexecutions, agents, bookchapters, bookprojects, booktypes, characters, enrichmentresponse, llms

    ]
