# Generated by Django 5.2.6 on 2025-10-27 18:10

from django.db import migrations


def set_unique_template_keys(apps, schema_editor):
    """Set unique template_key for each existing template using their ID"""
    PromptTemplate = apps.get_model("bfagent", "PromptTemplate")
    for template in PromptTemplate.objects.all():
        template.template_key = f"legacy_template_{template.id}"
        template.save(update_fields=['template_key'])


class Migration(migrations.Migration):

    dependencies = [
        ("bfagent", "0037_add_project_owner")    ]

    operations = [
        # AUTO-REMOVED: Operations on models not in migration state
        # These models exist in database but were removed from 0001_initial.py
        # Affected models: agentaction, agentartifacts, agentexecutions, agents, bookchapters, bookprojects, booktypes, characters, enrichmentresponse, llms

    ]
