# Generated by Django 5.2.6 on 2025-10-28 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0038_add_prompt_management_system_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompttemplate",
            name="preferred_llm",
            field=models.ForeignKey(
                blank=True,
                help_text="Preferred LLM for this template (optional, falls back to agent/system default)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preferred_templates",
                to="bfagent.llms",
            ),
        ),
    ]
