# Generated by Django 5.2.6 on 2025-10-28 11:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0039_add_preferred_llm_to_prompttemplate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Handler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "handler_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier (e.g., 'project_fields')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name (e.g., 'Project Fields Loader')",
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="What this handler does")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("input", "Input Handler"),
                            ("processing", "Processing Handler"),
                            ("output", "Output Handler"),
                        ],
                        db_index=True,
                        help_text="Handler type: input, processing, or output",
                        max_length=20,
                    ),
                ),
                (
                    "module_path",
                    models.CharField(
                        help_text="Python module path (e.g., 'apps.bfagent.services.handlers.input_handlers')",
                        max_length=255,
                    ),
                ),
                (
                    "class_name",
                    models.CharField(
                        help_text="Handler class name (e.g., 'ProjectFieldsHandler')",
                        max_length=100,
                    ),
                ),
                (
                    "config_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON Schema for validating handler configuration",
                    ),
                ),
                (
                    "input_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON Schema describing expected input structure",
                    ),
                ),
                (
                    "output_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON Schema describing output structure",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0", help_text="Semantic version (e.g., '1.2.3')", max_length=20
                    ),
                ),
                (
                    "is_deprecated",
                    models.BooleanField(default=False, help_text="Is this handler deprecated?"),
                ),
                (
                    "deprecation_reason",
                    models.TextField(blank=True, help_text="Why this handler is deprecated"),
                ),
                (
                    "avg_execution_time_ms",
                    models.IntegerField(
                        default=0, help_text="Average execution time in milliseconds"
                    ),
                ),
                (
                    "success_rate",
                    models.FloatField(default=100.0, help_text="Success rate percentage (0-100)"),
                ),
                (
                    "total_executions",
                    models.IntegerField(default=0, help_text="Total number of executions"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this handler available for use?"
                    ),
                ),
                (
                    "requires_llm",
                    models.BooleanField(
                        default=False, help_text="Does this handler require LLM API calls?"
                    ),
                ),
                (
                    "is_experimental",
                    models.BooleanField(
                        default=False, help_text="Is this handler in experimental/beta phase?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "documentation_url",
                    models.URLField(blank=True, help_text="Link to detailed documentation"),
                ),
                (
                    "example_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Example configuration for documentation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_handlers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "replacement_handler",
                    models.ForeignKey(
                        blank=True,
                        help_text="Recommended replacement if deprecated",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaces",
                        to="bfagent.handler",
                    ),
                ),
                (
                    "required_handlers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Handlers that must run before this one",
                        related_name="dependent_handlers",
                        to="bfagent.handler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Handler",
                "verbose_name_plural": "Handlers",
                "db_table": "handlers",
                "ordering": ["category", "handler_id"],
            },
        ),
        migrations.CreateModel(
            name="ActionHandler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Execution order within phase (0, 10, 20, ...)"
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("input", "Input Phase"),
                            ("processing", "Processing Phase"),
                            ("output", "Output Phase"),
                        ],
                        help_text="Execution phase: input, processing, or output",
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Handler-specific configuration (validated against handler.config_schema)",
                    ),
                ),
                (
                    "is_optional",
                    models.BooleanField(default=False, help_text="Can this handler be skipped?"),
                ),
                (
                    "condition",
                    models.JSONField(
                        blank=True,
                        help_text="Condition for running: {'field': 'has_outline', 'operator': '==', 'value': True}",
                        null=True,
                    ),
                ),
                (
                    "on_error",
                    models.CharField(
                        choices=[
                            ("stop", "Stop Execution"),
                            ("skip", "Skip Handler & Continue"),
                            ("retry", "Retry Handler"),
                            ("fallback", "Use Fallback Handler"),
                        ],
                        default="stop",
                        help_text="What to do if this handler fails",
                        max_length=20,
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=3, help_text="Number of retries if on_error='retry'"
                    ),
                ),
                (
                    "retry_delay_ms",
                    models.IntegerField(
                        default=1000, help_text="Delay between retries in milliseconds"
                    ),
                ),
                (
                    "description_override",
                    models.TextField(
                        blank=True,
                        help_text="Override handler description for this specific action context",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this handler active in this action?"
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="A/B test variant identifier (e.g., 'A', 'B', 'fast', 'quality')",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_handlers",
                        to="bfagent.agentaction",
                    ),
                ),
                (
                    "fallback_handler",
                    models.ForeignKey(
                        blank=True,
                        help_text="Handler to use if this one fails (requires on_error='fallback')",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fallback_for",
                        to="bfagent.handler",
                    ),
                ),
                (
                    "handler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="used_in_actions",
                        to="bfagent.handler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action Handler",
                "verbose_name_plural": "Action Handlers",
                "db_table": "action_handlers",
                "ordering": ["action", "phase", "order"],
            },
        ),
        migrations.CreateModel(
            name="HandlerExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("retrying", "Retrying"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(default=dict, help_text="Input context passed to handler"),
                ),
                (
                    "output_data",
                    models.JSONField(
                        blank=True, help_text="Output data returned by handler", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if execution failed", null=True
                    ),
                ),
                (
                    "error_traceback",
                    models.TextField(
                        blank=True, help_text="Full error traceback for debugging", null=True
                    ),
                ),
                (
                    "retry_attempt",
                    models.IntegerField(default=0, help_text="Current retry attempt number"),
                ),
                (
                    "execution_time_ms",
                    models.IntegerField(
                        blank=True, help_text="Execution time in milliseconds", null=True
                    ),
                ),
                (
                    "tokens_used",
                    models.IntegerField(
                        default=0, help_text="Total tokens consumed (if LLM handler)"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Execution cost in USD",
                        max_digits=10,
                    ),
                ),
                (
                    "execution_context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional execution context (user agent, IP, etc.)",
                    ),
                ),
                (
                    "action_handler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="bfagent.actionhandler",
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executed_handlers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "llm_used",
                    models.ForeignKey(
                        blank=True,
                        help_text="LLM used (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handler_executions",
                        to="bfagent.llms",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handler_executions",
                        to="bfagent.bookprojects",
                    ),
                ),
            ],
            options={
                "verbose_name": "Handler Execution",
                "verbose_name_plural": "Handler Executions",
                "db_table": "handler_executions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="handler",
            index=models.Index(
                fields=["category", "is_active"], name="handlers_categor_ecac88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="handler",
            index=models.Index(fields=["handler_id"], name="handlers_handler_1da8a8_idx"),
        ),
        migrations.AddIndex(
            model_name="handler",
            index=models.Index(fields=["-total_executions"], name="handlers_total_e_961c02_idx"),
        ),
        migrations.AddIndex(
            model_name="actionhandler",
            index=models.Index(
                fields=["action", "phase", "order"], name="action_hand_action__bd1785_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actionhandler",
            index=models.Index(fields=["handler"], name="action_hand_handler_35eba2_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="actionhandler",
            unique_together={("action", "handler", "phase", "variant")},
        ),
        migrations.AddIndex(
            model_name="handlerexecution",
            index=models.Index(
                fields=["action_handler", "-started_at"], name="handler_exe_action__158ac2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="handlerexecution",
            index=models.Index(
                fields=["status", "-started_at"], name="handler_exe_status_f900f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="handlerexecution",
            index=models.Index(
                fields=["project", "-started_at"], name="handler_exe_project_1a4635_idx"
            ),
        ),
    ]
