# Generated by Django 5.2.6 on 2025-10-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0041_add_user_to_bookprojects"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionhandler",
            name="traffic_weight",
            field=models.IntegerField(
                default=100,
                help_text="Traffic weight for variant selection (higher = more traffic). Default variant gets 100.",
            ),
        ),
    ]
