# Generated by Django 5.2.6 on 2025-10-30 17:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0043_world_building_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                blank=True,
                help_text="Type of location (e.g., 'Building', 'City', 'Forest', 'Room')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(
                help_text="Location name (e.g., 'Hugo's Library', 'The Dark Forest')",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="parent_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent location (e.g., 'Library' is in 'City Center')",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_locations",
                to="bfagent.location",
            ),
        ),
        migrations.AlterField(
            model_name="worldsetting",
            name="atmosphere",
            field=models.CharField(
                blank=True,
                help_text="Overall atmosphere/tone (e.g., 'Dark and gritty', 'Light and hopeful')",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="worldsetting",
            name="name",
            field=models.CharField(
                help_text="Name of the world/setting (e.g., 'Medieval Fantasy Kingdom', 'Modern Berlin')",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="worldsetting",
            name="technology_level",
            field=models.CharField(
                blank=True,
                help_text="Technology level (e.g., 'Medieval', 'Modern', 'Futuristic', 'Magic-based')",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="worldsetting",
            name="time_period",
            field=models.CharField(
                blank=True,
                help_text="When does the story take place? (e.g., '2024', 'Medieval Times', '2180')",
                max_length=200,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ComponentRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier (e.g., 'apps.bfagent.handlers.CharacterHandler')",
                        max_length=300,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Human-readable name", max_length=200
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("handler", "Handler"),
                            ("view", "View/URL"),
                            ("model", "Django Model"),
                            ("form", "Django Form"),
                            ("serializer", "DRF Serializer"),
                            ("api", "API Endpoint"),
                            ("graphql", "GraphQL Type"),
                            ("graphql_mutation", "GraphQL Mutation"),
                            ("graphql_query", "GraphQL Query"),
                            ("template", "Template"),
                            ("workflow", "Workflow"),
                            ("service", "Service Class"),
                            ("utility", "Utility Function"),
                            ("middleware", "Middleware"),
                            ("command", "Management Command"),
                        ],
                        db_index=True,
                        help_text="Type of component",
                        max_length=50,
                    ),
                ),
                (
                    "module_path",
                    models.CharField(
                        help_text="Python module path (e.g., 'apps.bfagent.domains.book_writing.handlers')",
                        max_length=500,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Relative file path from project root", max_length=500
                    ),
                ),
                (
                    "class_name",
                    models.CharField(
                        blank=True, help_text="Class name if applicable", max_length=200
                    ),
                ),
                (
                    "function_name",
                    models.CharField(
                        blank=True, help_text="Function name if applicable", max_length=200
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Domain (e.g., 'book', 'explosion', 'shared')",
                        max_length=100,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, help_text="Category within domain", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of what this component does"
                    ),
                ),
                ("docstring", models.TextField(blank=True, help_text="Full docstring from code")),
                (
                    "usage_examples",
                    models.JSONField(blank=True, default=list, help_text="List of usage examples"),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Searchable tags (e.g., ['character', 'generation', 'llm'])",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Type-specific metadata (schema varies by component_type)",
                    ),
                ),
                (
                    "depends_on",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of component identifiers this depends on",
                    ),
                ),
                (
                    "required_by",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of component identifiers that depend on this",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("deprecated", "Deprecated"),
                            ("beta", "Beta"),
                            ("experimental", "Experimental"),
                            ("disabled", "Disabled"),
                            ("planned", "Planned"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "version",
                    models.CharField(blank=True, help_text="Component version", max_length=50),
                ),
                (
                    "deprecated_reason",
                    models.TextField(blank=True, help_text="Why this was deprecated"),
                ),
                (
                    "replacement_identifier",
                    models.CharField(
                        blank=True, help_text="Identifier of replacement component", max_length=300
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of times used",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "success_count",
                    models.IntegerField(
                        default=0, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "failure_count",
                    models.IntegerField(
                        default=0, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "avg_execution_time_ms",
                    models.IntegerField(
                        default=0,
                        help_text="Average execution time in milliseconds",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, help_text="When this component was last used", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discovered_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this component was discovered/registered",
                    ),
                ),
            ],
            options={
                "verbose_name": "Component",
                "verbose_name_plural": "Component Registry",
                "db_table": "bfagent_component_registry",
                "ordering": ["component_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["component_type", "domain"], name="bfagent_com_compone_a01c39_idx"
                    ),
                    models.Index(
                        fields=["status", "component_type"], name="bfagent_com_status_35fe57_idx"
                    ),
                    models.Index(fields=["-usage_count"], name="bfagent_com_usage_c_ffd1b9_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComponentChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deprecated", "Deprecated"),
                            ("reactivated", "Reactivated"),
                            ("deleted", "Deleted"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        default=dict, help_text="Dict of changed fields: {field: {old: x, new: y}}"
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="bfagent.componentregistry",
                    ),
                ),
            ],
            options={
                "db_table": "bfagent_component_change_log",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ComponentUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("success", models.BooleanField(default=True)),
                (
                    "execution_time_ms",
                    models.IntegerField(
                        default=0, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional context about this usage"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if failed"),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="bfagent.componentregistry",
                    ),
                ),
            ],
            options={
                "db_table": "bfagent_component_usage_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["component", "-timestamp"], name="bfagent_com_compone_8f6335_idx"
                    ),
                    models.Index(fields=["-timestamp"], name="bfagent_com_timesta_35d4b9_idx"),
                ],
            },
        ),
    ]
