# Generated by Django 5.2.6 on 2025-10-30 17:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0044_component_registry"),
    ]

    operations = [
        migrations.CreateModel(
            name="MigrationRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "app_label",
                    models.CharField(db_index=True, help_text="Django app name", max_length=100),
                ),
                (
                    "migration_name",
                    models.CharField(
                        db_index=True,
                        help_text="Migration filename (e.g., 0001_initial)",
                        max_length=255,
                    ),
                ),
                ("migration_number", models.IntegerField(help_text="Extracted migration number")),
                (
                    "file_path",
                    models.CharField(help_text="Relative path to migration file", max_length=500),
                ),
                (
                    "file_hash",
                    models.CharField(
                        help_text="SHA256 hash of migration file content", max_length=64
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Auto-extracted description from migration"
                    ),
                ),
                (
                    "migration_type",
                    models.CharField(
                        choices=[
                            ("schema", "Schema Migration"),
                            ("data", "Data Migration"),
                            ("mixed", "Schema + Data"),
                            ("empty", "Empty Migration"),
                        ],
                        db_index=True,
                        default="schema",
                        max_length=20,
                    ),
                ),
                (
                    "complexity_score",
                    models.IntegerField(
                        default=0,
                        help_text="Complexity score 0-100",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_reversible",
                    models.BooleanField(
                        default=True, help_text="Can this migration be rolled back?"
                    ),
                ),
                (
                    "requires_downtime",
                    models.BooleanField(default=False, help_text="Requires downtime to apply?"),
                ),
                (
                    "models_created",
                    models.JSONField(blank=True, default=list, help_text="List of models created"),
                ),
                (
                    "models_deleted",
                    models.JSONField(blank=True, default=list, help_text="List of models deleted"),
                ),
                (
                    "fields_added",
                    models.JSONField(
                        blank=True, default=dict, help_text="Dict of fields added per model"
                    ),
                ),
                (
                    "fields_removed",
                    models.JSONField(
                        blank=True, default=dict, help_text="Dict of fields removed per model"
                    ),
                ),
                (
                    "fields_modified",
                    models.JSONField(
                        blank=True, default=dict, help_text="Dict of fields modified per model"
                    ),
                ),
                (
                    "depends_on",
                    models.JSONField(
                        blank=True, default=list, help_text="List of migration dependencies"
                    ),
                ),
                (
                    "estimated_affected_rows",
                    models.IntegerField(
                        default=0,
                        help_text="Estimated number of rows affected",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "estimated_duration_seconds",
                    models.IntegerField(
                        default=0,
                        help_text="Estimated duration in seconds",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "warnings",
                    models.JSONField(blank=True, default=list, help_text="List of warnings"),
                ),
                (
                    "rollback_risks",
                    models.JSONField(blank=True, default=list, help_text="List of rollback risks"),
                ),
                (
                    "is_applied",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Has this migration been applied?"
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True, help_text="When was this migration applied?", null=True
                    ),
                ),
                (
                    "discovered_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When was this migration discovered?",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "bfagent_migration_registry",
                "ordering": ["app_label", "migration_number"],
                "indexes": [
                    models.Index(
                        fields=["app_label", "migration_number"],
                        name="bfagent_mig_app_lab_49b9ce_idx",
                    ),
                    models.Index(fields=["applied_at"], name="bfagent_mig_applied_956deb_idx"),
                    models.Index(
                        fields=["is_applied", "app_label"], name="bfagent_mig_is_appl_7ca748_idx"
                    ),
                    models.Index(
                        fields=["complexity_score"], name="bfagent_mig_complex_8efe00_idx"
                    ),
                ],
                "unique_together": {("app_label", "migration_name")},
            },
        ),
        migrations.CreateModel(
            name="MigrationConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "conflict_type",
                    models.CharField(
                        choices=[
                            ("circular", "Circular Dependency"),
                            ("missing", "Missing Dependency"),
                            ("order", "Order Conflict"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "migration1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts_as_migration1",
                        to="bfagent.migrationregistry",
                    ),
                ),
                (
                    "migration2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts_as_migration2",
                        to="bfagent.migrationregistry",
                    ),
                ),
            ],
            options={
                "db_table": "bfagent_migration_conflict",
                "ordering": ["-detected_at"],
            },
        ),
    ]
