# Generated by Django 5.2.6 on 2025-10-30 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0045_migration_registry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="componentregistry",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, help_text="When development completed", null=True
            ),
        ),
        migrations.AddField(
            model_name="componentregistry",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary developer/owner",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_components",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="componentregistry",
            name="planned_at",
            field=models.DateTimeField(
                blank=True, help_text="When this component was planned", null=True
            ),
        ),
        migrations.AddField(
            model_name="componentregistry",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("critical", "🔥 Critical"),
                    ("high", "🔴 High"),
                    ("medium", "🟡 Medium"),
                    ("low", "🔵 Low"),
                    ("backlog", "📦 Backlog"),
                ],
                default="backlog",
                help_text="Priority level",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="componentregistry",
            name="proposed_at",
            field=models.DateTimeField(
                blank=True, help_text="When this component was proposed", null=True
            ),
        ),
        migrations.AddField(
            model_name="componentregistry",
            name="started_at",
            field=models.DateTimeField(blank=True, help_text="When development started", null=True),
        ),
        migrations.AlterField(
            model_name="componentregistry",
            name="status",
            field=models.CharField(
                choices=[
                    ("proposed", "💡 Proposed"),
                    ("planned", "📋 Planned"),
                    ("in_progress", "🚧 In Progress"),
                    ("in_review", "👀 In Review"),
                    ("testing", "🧪 Testing"),
                    ("active", "✅ Active"),
                    ("beta", "Beta"),
                    ("experimental", "Experimental"),
                    ("deprecated", "⚠️ Deprecated"),
                    ("disabled", "Disabled"),
                    ("rejected", "❌ Rejected"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
    ]
