# Generated by Django 5.2.6 on 2025-10-30 20:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0046_feature_planning_basics"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Document title (e.g., 'Architecture Overview')", max_length=200
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Relative path to file in repository (e.g., docs/HANDLER_SYSTEM.md)",
                        max_length=500,
                    ),
                ),
                (
                    "uploaded_file",
                    models.FileField(
                        blank=True,
                        help_text="Uploaded document file (optional if file_path is set)",
                        null=True,
                        upload_to="feature_docs/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["md", "pdf", "txt", "docx", "png", "jpg", "svg"]
                            )
                        ],
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("design", "Design Document"),
                            ("architecture", "Architecture Document"),
                            ("guide", "Implementation Guide"),
                            ("reference", "Reference Documentation"),
                            ("spec", "Technical Specification"),
                            ("notes", "Meeting Notes"),
                            ("diagram", "Diagram/Visualization"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Type of document",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of what this document contains"
                    ),
                ),
                (
                    "is_auto_discovered",
                    models.BooleanField(
                        default=False,
                        help_text="Was this document auto-discovered from docs/ folder?",
                    ),
                ),
                (
                    "discovered_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When was this document linked to the feature?"
                    ),
                ),
                ("file_size", models.IntegerField(default=0, help_text="File size in bytes")),
                (
                    "word_count",
                    models.IntegerField(
                        default=0, help_text="Approximate word count (for text documents)"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        blank=True, help_text="Last modification time of the file", null=True
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Display order (lower = first)"),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        help_text="Feature this document belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="bfagent.componentregistry",
                    ),
                ),
            ],
            options={
                "db_table": "bfagent_feature_document",
                "ordering": ["order", "-discovered_at"],
                "indexes": [
                    models.Index(
                        fields=["feature", "document_type"], name="bfagent_fea_feature_2131f3_idx"
                    ),
                    models.Index(
                        fields=["is_auto_discovered"], name="bfagent_fea_is_auto_6d6741_idx"
                    ),
                ],
                "unique_together": {("feature", "file_path")},
            },
        ),
        migrations.CreateModel(
            name="FeatureDocumentKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        db_index=True,
                        help_text="Keyword to search for in filenames and content",
                        max_length=100,
                    ),
                ),
                (
                    "keyword_type",
                    models.CharField(
                        choices=[
                            ("filename", "In Filename"),
                            ("content", "In Content"),
                            ("both", "In Both"),
                        ],
                        default="both",
                        help_text="Where to search for this keyword",
                        max_length=20,
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        default=1, help_text="Weight for relevance scoring (higher = more relevant)"
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        help_text="Feature to associate with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discovery_keywords",
                        to="bfagent.componentregistry",
                    ),
                ),
            ],
            options={
                "db_table": "bfagent_feature_document_keyword",
                "indexes": [
                    models.Index(
                        fields=["keyword", "keyword_type"], name="bfagent_fea_keyword_6e4aca_idx"
                    )
                ],
                "unique_together": {("feature", "keyword")},
            },
        ),
    ]
