# Generated by Django 5.2.6 on 2025-10-31 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0047_feature_documents"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContextSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique identifier for the schema (e.g., 'chapter_generation')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name for UI display", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of what this schema does"
                    ),
                ),
                (
                    "handler_type",
                    models.CharField(
                        blank=True,
                        help_text="Handler this schema is designed for (e.g., 'ChapterGenerateHandler')",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this schema is currently active"
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="System schemas are pre-loaded and cannot be deleted",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0",
                        help_text="Schema version for tracking changes",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Context Schema",
                "verbose_name_plural": "Context Schemas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContextEnrichmentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("handler_name", models.CharField(max_length=100)),
                ("params", models.JSONField(default=dict)),
                ("enriched_context", models.JSONField(default=dict)),
                (
                    "execution_time_ms",
                    models.FloatField(help_text="Execution time in milliseconds"),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="bfagent.contextschema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Context Enrichment Log",
                "verbose_name_plural": "Context Enrichment Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="bfagent_con_created_ba0748_idx"),
                    models.Index(
                        fields=["schema", "-created_at"], name="bfagent_con_schema__f2c90d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContextSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Descriptive name for this source", max_length=100),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("model", "Django Model (PK)"),
                            ("related_query", "Related Query (Filter)"),
                            ("computed", "Computed Value"),
                            ("aggregation", "Aggregation (Count/Sum/etc)"),
                            ("beat_sheet", "Beat Sheet Mapping"),
                            ("custom", "Custom Function"),
                        ],
                        help_text="Type of data source",
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Execution order (lower runs first)"),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        help_text="Django model name (e.g., 'BookProjects', 'Characters')",
                        max_length=100,
                    ),
                ),
                (
                    "filter_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Filter parameters for queries (supports {param} placeholders)",
                    ),
                ),
                (
                    "fields",
                    models.JSONField(
                        blank=True, default=list, help_text="Fields to extract from model instances"
                    ),
                ),
                (
                    "field_mappings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Map source fields to context keys (source_field: context_key)",
                    ),
                ),
                (
                    "aggregate_type",
                    models.CharField(
                        choices=[
                            ("first", "First Result"),
                            ("last", "Last Result"),
                            ("all", "All Results (QuerySet)"),
                            ("list", "List of Dicts"),
                            ("count", "Count"),
                            ("exists", "Boolean Exists"),
                        ],
                        default="first",
                        help_text="How to aggregate multiple results",
                        max_length=20,
                    ),
                ),
                (
                    "context_key",
                    models.CharField(
                        blank=True,
                        help_text="Key to use in context dict (if not merging fields)",
                        max_length=100,
                    ),
                ),
                (
                    "function_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of computation function (for computed type)",
                        max_length=100,
                    ),
                ),
                (
                    "function_params",
                    models.JSONField(
                        blank=True, default=dict, help_text="Parameters for computation function"
                    ),
                ),
                (
                    "order_by",
                    models.CharField(
                        blank=True,
                        help_text="Field to order results by (use '-field' for descending)",
                        max_length=100,
                    ),
                ),
                (
                    "default_value",
                    models.JSONField(
                        blank=True, help_text="Default value if source returns nothing", null=True
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, help_text="If True, enrichment fails if this source fails"
                    ),
                ),
                (
                    "fallback_value",
                    models.JSONField(
                        blank=True,
                        help_text="Fallback value if source fails (when not required)",
                        null=True,
                    ),
                ),
                (
                    "timeout_seconds",
                    models.IntegerField(
                        default=5, help_text="Maximum time to wait for this source (in seconds)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this source is active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="bfagent.contextschema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Context Source",
                "verbose_name_plural": "Context Sources",
                "ordering": ["schema", "order", "name"],
                "unique_together": {("schema", "order")},
            },
        ),
    ]
