# Generated by Django 5.2.6 on 2025-11-01 12:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0048_add_context_enrichment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("allow_comments", models.BooleanField(default=True)),
                ("allow_ratings", models.BooleanField(default=True)),
                ("comments_visible_to_others", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_comments", models.IntegerField(default=0)),
                ("unread_comments", models.IntegerField(default=0)),
                ("total_participants", models.IntegerField(default=0)),
                ("total_ratings", models.IntegerField(default=0)),
                ("average_rating", models.FloatField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_review_rounds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_rounds",
                        to="bfagent.bookprojects",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Round",
                "verbose_name_plural": "Review Rounds",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.TextField()),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("general", "General Comment"),
                            ("suggestion", "Suggestion"),
                            ("question", "Question"),
                            ("praise", "Praise"),
                            ("concern", "Concern"),
                            ("typo", "Typo/Grammar"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("addressed", "Addressed"),
                            ("resolved", "Resolved"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("author_reply", models.TextField(blank=True)),
                ("replied_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_edited", models.BooleanField(default=False)),
                ("helpful_count", models.IntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_comments",
                        to="bfagent.bookchapters",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review_round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="bfagent.reviewround",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "ordering": ["chapter__chapter_number", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("author", "Author"), ("reader", "Beta-Reader")],
                        default="reader",
                        max_length=10,
                    ),
                ),
                ("can_comment", models.BooleanField(default=True)),
                ("can_rate", models.BooleanField(default=True)),
                ("can_see_other_comments", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                ("comments_count", models.IntegerField(default=0)),
                ("ratings_count", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review_round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="bfagent.reviewround",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Participant",
                "verbose_name_plural": "Review Participants",
                "ordering": ["-joined_at"],
                "unique_together": {("review_round", "user")},
            },
        ),
        migrations.CreateModel(
            name="ChapterRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "overall_rating",
                    models.IntegerField(
                        help_text="Rate from 1 (poor) to 5 (excellent)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "feedback_text",
                    models.TextField(blank=True, help_text="Optional: Explain your rating"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_ratings",
                        to="bfagent.bookchapters",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapter_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review_round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapter_ratings",
                        to="bfagent.reviewround",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chapter Rating",
                "verbose_name_plural": "Chapter Ratings",
                "ordering": ["chapter__chapter_number"],
                "unique_together": {("review_round", "chapter", "reviewer")},
            },
        ),
    ]
