# Generated by Django 5.2.6 on 2025-11-01 13:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0049_review_system"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageStyleProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "style_id",
                    models.CharField(
                        help_text="Unique style identifier", max_length=100, unique=True
                    ),
                ),
                ("display_name", models.CharField(help_text="Human-readable name", max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the style", null=True
                    ),
                ),
                (
                    "art_style",
                    models.CharField(
                        choices=[
                            ("realistic", "Realistic Photography"),
                            ("watercolor", "Watercolor"),
                            ("digital_art", "Digital Art"),
                            ("vector", "Vector Art"),
                            ("technical", "Technical Drawing"),
                            ("illustration", "Illustration"),
                            ("photography", "Photography"),
                            ("sketch", "Sketch"),
                            ("oil_painting", "Oil Painting"),
                            ("anime", "Anime"),
                            ("comic", "Comic Book"),
                        ],
                        default="digital_art",
                        max_length=50,
                    ),
                ),
                (
                    "color_mood",
                    models.CharField(
                        help_text="Color palette description (e.g., 'pastel', 'vibrant')",
                        max_length=500,
                    ),
                ),
                ("base_prompt", models.TextField(help_text="Base prompt template for this style")),
                (
                    "negative_prompt",
                    models.TextField(
                        blank=True, help_text="Things to avoid in generation", null=True
                    ),
                ),
                (
                    "default_resolution",
                    models.CharField(
                        default="1024x1024",
                        help_text="Default image size (e.g., 1024x1024)",
                        max_length=20,
                    ),
                ),
                (
                    "default_quality",
                    models.CharField(
                        choices=[("standard", "Standard"), ("hd", "HD")],
                        default="standard",
                        help_text="Quality setting",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_provider",
                    models.CharField(
                        choices=[
                            ("dalle3", "DALL-E 3 (OpenAI)"),
                            ("stable_diffusion", "Stable Diffusion"),
                            ("midjourney", "Midjourney"),
                            ("leonardo", "Leonardo AI"),
                            ("adobe_firefly", "Adobe Firefly"),
                        ],
                        default="dalle3",
                        max_length=50,
                    ),
                ),
                (
                    "consistency_weight",
                    models.FloatField(
                        default=0.8,
                        help_text="How strict style consistency is (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "style_strength",
                    models.FloatField(
                        default=0.7,
                        help_text="How strong the style is applied (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "seed",
                    models.IntegerField(
                        blank=True, help_text="Fixed seed for reproducibility", null=True
                    ),
                ),
                (
                    "reference_images",
                    models.JSONField(
                        blank=True, default=list, help_text="URLs to reference images"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, help_text="Tags for categorization"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(default="1.0.0", max_length=20)),
                (
                    "usage_count",
                    models.IntegerField(default=0, help_text="How many times this style was used"),
                ),
                (
                    "total_cost_usd",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Total cost for images generated with this style",
                        max_digits=10,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Link to specific project",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="illustration_styles",
                        to="bfagent.bookprojects",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="illustration_styles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Image Style Profile",
                "verbose_name_plural": "Image Style Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImageGenerationBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        help_text="Unique batch identifier", max_length=100, unique=True
                    ),
                ),
                ("name", models.CharField(help_text="Batch name", max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("cover", "Book Cover"),
                            ("chapter_header", "Chapter Header"),
                            ("scene_illustration", "Scene Illustration"),
                            ("character_portrait", "Character Portrait"),
                            ("location", "Location Shot"),
                            ("diagram", "Diagram"),
                            ("infographic", "Infographic"),
                            ("technical_drawing", "Technical Drawing"),
                            ("chart", "Chart"),
                            ("icon", "Icon"),
                            ("full_page", "Full Page Illustration"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("dalle3", "DALL-E 3 (OpenAI)"),
                            ("stable_diffusion", "Stable Diffusion"),
                            ("midjourney", "Midjourney"),
                            ("leonardo", "Leonardo AI"),
                            ("adobe_firefly", "Adobe Firefly"),
                        ],
                        max_length=50,
                    ),
                ),
                ("total_images", models.IntegerField(help_text="Total images to generate")),
                (
                    "generated_count",
                    models.IntegerField(default=0, help_text="Successfully generated"),
                ),
                ("failed_count", models.IntegerField(default=0, help_text="Failed generations")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_cost_usd", models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_batches",
                        to="bfagent.bookprojects",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "style_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bfagent.imagestyleprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image Generation Batch",
                "verbose_name_plural": "Image Generation Batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image_id",
                    models.CharField(
                        help_text="Unique image identifier", max_length=100, unique=True
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("cover", "Book Cover"),
                            ("chapter_header", "Chapter Header"),
                            ("scene_illustration", "Scene Illustration"),
                            ("character_portrait", "Character Portrait"),
                            ("location", "Location Shot"),
                            ("diagram", "Diagram"),
                            ("infographic", "Infographic"),
                            ("technical_drawing", "Technical Drawing"),
                            ("chart", "Chart"),
                            ("icon", "Icon"),
                            ("full_page", "Full Page Illustration"),
                        ],
                        default="scene_illustration",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("generated", "Generated"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "provider_used",
                    models.CharField(
                        choices=[
                            ("dalle3", "DALL-E 3 (OpenAI)"),
                            ("stable_diffusion", "Stable Diffusion"),
                            ("midjourney", "Midjourney"),
                            ("leonardo", "Leonardo AI"),
                            ("adobe_firefly", "Adobe Firefly"),
                        ],
                        help_text="AI Provider used for generation",
                        max_length=50,
                    ),
                ),
                ("prompt_used", models.TextField(help_text="Actual prompt sent to AI")),
                (
                    "negative_prompt_used",
                    models.TextField(blank=True, help_text="Negative prompt used", null=True),
                ),
                ("image_url", models.URLField(help_text="URL to generated image", max_length=500)),
                (
                    "image_file",
                    models.ImageField(
                        blank=True,
                        help_text="Downloaded image file (optional)",
                        null=True,
                        upload_to="illustrations/%Y/%m/%d/",
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True, help_text="URL to thumbnail", max_length=500, null=True
                    ),
                ),
                (
                    "resolution",
                    models.CharField(help_text="Image resolution (e.g., 1024x1024)", max_length=20),
                ),
                ("quality", models.CharField(help_text="Quality setting used", max_length=20)),
                (
                    "seed",
                    models.IntegerField(
                        blank=True, help_text="Seed used for generation", null=True
                    ),
                ),
                (
                    "generation_time_seconds",
                    models.FloatField(blank=True, help_text="Time taken to generate", null=True),
                ),
                (
                    "cost_usd",
                    models.DecimalField(
                        decimal_places=4, default=0, help_text="Cost of this image", max_digits=10
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, help_text="Number of retries needed"),
                ),
                (
                    "content_context",
                    models.JSONField(blank=True, default=dict, help_text="Content context data"),
                ),
                (
                    "quality_score",
                    models.FloatField(
                        blank=True,
                        help_text="AI-assessed quality score (0.0-1.0)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "user_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="User rating (1-5 stars)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, help_text="Tags for categorization"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, help_text="Additional metadata"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if generation failed", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Link to specific chapter",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="illustrations",
                        to="bfagent.bookchapters",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this image belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_images",
                        to="bfagent.bookprojects",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "style_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_images",
                        to="bfagent.imagestyleprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Image",
                "verbose_name_plural": "Generated Images",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"], name="bfagent_gen_project_972aef_idx"
                    ),
                    models.Index(
                        fields=["image_type", "status"], name="bfagent_gen_image_t_c825fc_idx"
                    ),
                    models.Index(fields=["created_at"], name="bfagent_gen_created_d5bb0b_idx"),
                ],
            },
        ),
    ]
