# Generated by Django 5.2.6 on 2025-11-02 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0050_illustration_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedimage",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: Project this image belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_images",
                to="bfagent.bookprojects",
            ),
        ),
    ]
