# Generated by Django 5.2.6 on 2025-11-03 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0051_make_project_optional_in_generated_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "test_id",
                    models.CharField(
                        help_text="Unique test identifier (e.g., test_user_login)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("robot", "Robot Framework"),
                            ("pytest", "Pytest"),
                            ("playwright", "Playwright"),
                            ("manual", "Manual Test"),
                        ],
                        default="robot",
                        max_length=50,
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("unit", "Unit Test"),
                            ("integration", "Integration Test"),
                            ("ui", "UI Test"),
                            ("api", "API Test"),
                            ("e2e", "End-to-End Test"),
                            ("performance", "Performance Test"),
                            ("security", "Security Test"),
                        ],
                        default="integration",
                        max_length=50,
                    ),
                ),
                (
                    "test_code",
                    models.TextField(help_text="Generated or manually written test code"),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Relative path to test file in project",
                        max_length=500,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list, help_text="List of tags")),
                (
                    "priority",
                    models.IntegerField(default=3, help_text="Test priority (1=highest, 5=lowest)"),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(
                        default=30, help_text="Estimated execution time in seconds"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "is_auto_generated",
                    models.BooleanField(
                        default=False, help_text="Was this test auto-generated from requirements?"
                    ),
                ),
                (
                    "generation_metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Metadata about auto-generation process"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["priority", "name"],
                "indexes": [
                    models.Index(
                        fields=["framework", "test_type"], name="bfagent_tes_framewo_f853f8_idx"
                    ),
                    models.Index(fields=["status"], name="bfagent_tes_status_7807e7_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TestRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(help_text="Requirement name/title", max_length=200)),
                ("description", models.TextField(blank=True, help_text="Detailed description")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("feature", "Feature Requirement"),
                            ("bug_fix", "Bug Fix"),
                            ("enhancement", "Enhancement"),
                            ("refactor", "Refactoring"),
                            ("performance", "Performance"),
                            ("security", "Security"),
                        ],
                        default="feature",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical - Must Test"),
                            ("high", "High - Should Test"),
                            ("medium", "Medium - Nice to Test"),
                            ("low", "Low - Optional"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready for Testing"),
                            ("in_progress", "Testing in Progress"),
                            ("completed", "Testing Completed"),
                            ("blocked", "Blocked"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "acceptance_criteria",
                    models.JSONField(
                        default=list,
                        help_text='\n        List of acceptance criteria in Gherkin format.\n        Example: [{\n            "id": "ac_1",\n            "scenario": "User can add feedback",\n            "given": "User is logged in and has a chapter",\n            "when": "User clicks add comment button",\n            "then": "Comment form should appear",\n            "test_type": "ui",\n            "priority": "high"\n        }]\n        ',
                    ),
                ),
                (
                    "ui_requirements",
                    models.JSONField(
                        default=dict,
                        help_text='\n        UI-specific requirements. Example: {\n            "elements_to_test": ["buttons", "forms", "navigation"],\n            "responsive": true,\n            "accessibility": ["aria", "keyboard"],\n            "constraints": "Button must be visible within 2 seconds"\n        }\n        ',
                    ),
                ),
                (
                    "test_coverage_target",
                    models.IntegerField(default=80, help_text="Target test coverage percentage"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for filtering and categorization (list of strings)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_requirements_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestCoverageReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("total_criteria", models.IntegerField(default=0)),
                ("criteria_with_tests", models.IntegerField(default=0)),
                ("tests_passing", models.IntegerField(default=0)),
                ("tests_failing", models.IntegerField(default=0)),
                ("tests_pending", models.IntegerField(default=0)),
                ("coverage_percentage", models.FloatField(default=0.0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("last_test_run", models.DateTimeField(blank=True, null=True)),
                (
                    "requirement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverage_report",
                        to="bfagent.testrequirement",
                    ),
                ),
            ],
            options={
                "ordering": ["-coverage_percentage"],
            },
        ),
        migrations.CreateModel(
            name="RequirementTestLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "criterion_id",
                    models.CharField(
                        help_text="ID of specific acceptance criterion this test covers",
                        max_length=50,
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[("auto", "Auto-Generated"), ("manual", "Manually Linked")],
                        default="auto",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Test Pending"),
                            ("implemented", "Test Implemented"),
                            ("passing", "Test Passing"),
                            ("failing", "Test Failing"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "last_test_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("last_executed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirement_links",
                        to="bfagent.testcase",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_links",
                        to="bfagent.testrequirement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Exploratory"),
                            ("regression", "Regression Testing"),
                            ("smoke", "Smoke Testing"),
                            ("acceptance", "Acceptance Testing"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manual_sessions",
                        to="bfagent.testrequirement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="TestScreenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("page_url", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="test_screenshots/%Y/%m/%d/")),
                ("notes", models.TextField(blank=True)),
                ("is_bug_screenshot", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="bfagent.testsession",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("url", models.CharField(max_length=500)),
                ("method", models.CharField(max_length=10)),
                ("response_status", models.IntegerField(null=True)),
                ("response_time", models.DateTimeField(null=True)),
                ("request_data", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="bfagent.testsession",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TestBug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("page_url", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("wont_fix", "Won't Fix"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "screenshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bfagent.testscreenshot",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bugs",
                        to="bfagent.testsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-reported_at"],
            },
        ),
        migrations.CreateModel(
            name="TestExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration", models.FloatField(help_text="Execution time in seconds")),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                ("environment", models.CharField(default="development", max_length=50)),
                (
                    "git_commit",
                    models.CharField(
                        blank=True, help_text="Git commit hash when test was run", max_length=40
                    ),
                ),
                ("log_file_path", models.CharField(blank=True, max_length=500)),
                (
                    "screenshot_paths",
                    models.JSONField(
                        blank=True, default=list, help_text="List of screenshot file paths"
                    ),
                ),
                (
                    "execution_metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional execution context"
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="bfagent.testcase",
                    ),
                ),
            ],
            options={
                "ordering": ["-executed_at"],
                "indexes": [
                    models.Index(
                        fields=["test_case", "result"], name="bfagent_tes_test_ca_b2db02_idx"
                    ),
                    models.Index(fields=["executed_at"], name="bfagent_tes_execute_0cd84a_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="testrequirement",
            index=models.Index(fields=["status", "priority"], name="bfagent_tes_status_44c843_idx"),
        ),
        migrations.AddIndex(
            model_name="testrequirement",
            index=models.Index(fields=["category"], name="bfagent_tes_categor_266b32_idx"),
        ),
        migrations.AddIndex(
            model_name="testrequirement",
            index=models.Index(fields=["created_at"], name="bfagent_tes_created_6e9b05_idx"),
        ),
        migrations.AddIndex(
            model_name="requirementtestlink",
            index=models.Index(
                fields=["requirement", "status"], name="bfagent_req_require_9e50ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="requirementtestlink",
            index=models.Index(
                fields=["test_case", "last_test_result"], name="bfagent_req_test_ca_f222ed_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="requirementtestlink",
            unique_together={("requirement", "criterion_id")},
        ),
    ]
