# Generated by Django 5.2.6 on 2025-11-03 14:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bfagent", "0052_add_testing_models_sqlite_compatible"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BugFixPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "fix_type",
                    models.CharField(
                        help_text="Type of fix: create_chapter, fix_url, etc.", max_length=100
                    ),
                ),
                (
                    "fix_description",
                    models.TextField(help_text="Human-readable description of what will be done"),
                ),
                (
                    "fix_actions",
                    models.JSONField(default=dict, help_text="Detailed fix steps and parameters"),
                ),
                (
                    "handler_id",
                    models.CharField(
                        help_text="ID of handler that will execute this fix", max_length=200
                    ),
                ),
                (
                    "handler_code",
                    models.TextField(
                        blank=True, help_text="Generated handler code (if auto-generated)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("executing", "Executing"),
                            ("executed", "Executed"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "execution_result",
                    models.JSONField(blank=True, default=dict, help_text="Result of fix execution"),
                ),
                ("execution_log", models.TextField(blank=True, help_text="Detailed execution log")),
                (
                    "rollback_possible",
                    models.BooleanField(
                        default=False, help_text="Whether this fix can be rolled back"
                    ),
                ),
                (
                    "rollback_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Data needed for rollback"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_fix_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_fix_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fix_plans",
                        to="bfagent.testrequirement",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="bfagent_bug_status_7e5e87_idx"),
                    models.Index(
                        fields=["requirement", "status"], name="bfagent_bug_require_5a83e6_idx"
                    ),
                ],
            },
        ),
    ]
