# Generated by Django 5.2.6 on 2025-11-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bfagent", "0053_add_bugfix_plan_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="testrequirement",
            name="actual_behavior",
            field=models.TextField(blank=True, help_text="What actually happens (bug description)"),
        ),
        migrations.AddField(
            model_name="testrequirement",
            name="expected_behavior",
            field=models.TextField(blank=True, help_text="What should happen instead"),
        ),
        migrations.AddField(
            model_name="testrequirement",
            name="notes",
            field=models.TextField(blank=True, help_text="Additional notes and comments"),
        ),
        migrations.AddField(
            model_name="testrequirement",
            name="url",
            field=models.URLField(
                blank=True, help_text="URL where the bug was found", max_length=500, null=True
            ),
        ),
    ]
