# Generated by Django 5.2.6 on 2025-11-04 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bfagent", "0054_testrequirement_actual_behavior_and_more"),
    ]

    operations = []
