# Generated by Django 5.2.6 on 2025-11-06 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bfagent", "0055_add_bug_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainArt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Domain name (e.g., 'book_creation')", max_length=100, unique=True
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier (e.g., 'book-creation')", unique=True
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name (e.g., 'Bücher-Hub')", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="What this domain encompasses"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Bootstrap icon name (e.g., 'book', 'people')",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="primary",
                        help_text="Bootstrap color class (primary, success, info, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this domain available for use?"
                    ),
                ),
                (
                    "is_experimental",
                    models.BooleanField(
                        default=False, help_text="Is this domain in experimental phase?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Domain Art",
                "verbose_name_plural": "Domain Arts",
                "db_table": "domain_arts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DomainType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Type name (e.g., 'fiction', 'consultants')", max_length=100
                    ),
                ),
                ("slug", models.SlugField(help_text="URL-friendly identifier")),
                ("display_name", models.CharField(help_text="Human-readable name", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="What this type encompasses"),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, help_text="Type-specific configuration"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Is this type available for use?"),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, help_text="Display order within domain_art"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain_art",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_types",
                        to="bfagent.domainart",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain Type",
                "verbose_name_plural": "Domain Types",
                "db_table": "domain_types",
                "ordering": ["domain_art", "sort_order", "name"],
                "unique_together": {("domain_art", "slug")},
            },
        ),
        migrations.CreateModel(
            name="DomainPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, help_text="Execution order within domain_type"),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Phase-specific configuration for this domain",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this phase active for this domain type?"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True, help_text="Is this phase required or optional?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workflow_phase",
                    models.ForeignKey(
                        help_text="Reference to existing WorkflowPhase",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_phases",
                        to="bfagent.workflowphase",
                    ),
                ),
                (
                    "domain_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_phases",
                        to="bfagent.domaintype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain Phase",
                "verbose_name_plural": "Domain Phases",
                "db_table": "domain_phases",
                "ordering": ["domain_type", "sort_order"],
                "unique_together": {("domain_type", "workflow_phase")},
            },
        ),
    ]
