# Generated by Django 6.0 on 2025-12-11 12:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "domain_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique domain identifier (e.g., 'presentation_studio')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Human-readable domain name", max_length=100)),
                ("description", models.TextField(blank=True, help_text="Domain description")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("core", "Core"),
                            ("ai", "AI"),
                            ("medical", "Medical"),
                            ("presentation", "Presentation"),
                            ("content", "Content"),
                            ("admin", "Admin"),
                            ("integration", "Integration"),
                        ],
                        default="core",
                        help_text="Domain category",
                        max_length=20,
                    ),
                ),
                (
                    "version",
                    models.CharField(default="1.0.0", help_text="Domain version", max_length=20),
                ),
                (
                    "base_path",
                    models.CharField(
                        blank=True,
                        help_text="Base path to domain code (e.g., 'apps/presentation_studio')",
                        max_length=200,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether domain is active"),
                ),
                (
                    "dependencies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of domain_ids this domain depends on",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional domain metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Domain",
                "verbose_name_plural": "Domains",
                "db_table": "core_domain",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HandlerCategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text='Unique code (e.g., "input", "processing", "output")',
                        max_length=50,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Human-readable name (e.g., "Input Handler")',
                        max_length=200,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description of this category",
                        verbose_name="Description",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Icon class (e.g., "bi-arrow-down-circle" for input)',
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Display color (e.g., "primary", "success", "info")',
                        max_length=50,
                        verbose_name="Color",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Order for display in UI (lower = first)",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Category-specific configuration options",
                        verbose_name="Configuration",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this category is currently active",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="System categories cannot be deleted",
                        verbose_name="Is System Category",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
            ],
            options={
                "verbose_name": "Handler Category",
                "verbose_name_plural": "Handler Categories",
                "db_table": "handler_categories",
                "ordering": ["display_order", "name"],
                "permissions": [("manage_system_categories", "Can manage system categories")],
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"], name="hndlcat_active_order_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="URLPattern",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text='Unique identifier code (e.g., "expert_hub:customer_dashboard")',
                        max_length=100,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "namespace",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text='URL namespace (e.g., "expert_hub", "control_center")',
                        max_length=50,
                        verbose_name="Namespace",
                    ),
                ),
                (
                    "pattern_name",
                    models.CharField(
                        db_index=True,
                        help_text='URL pattern name (e.g., "customer_dashboard", "dashboard")',
                        max_length=100,
                        verbose_name="Pattern Name",
                    ),
                ),
                (
                    "app_label",
                    models.CharField(
                        db_index=True,
                        help_text='Django app this URL belongs to (e.g., "expert_hub", "control_center")',
                        max_length=100,
                        verbose_name="App Label",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable description of what this URL does",
                        verbose_name="Description",
                    ),
                ),
                (
                    "url_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Example URL path (e.g., "/expert-hub/customers/")',
                        max_length=500,
                        verbose_name="URL Path",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional configuration data",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this URL pattern is currently active",
                        verbose_name="Is Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
            ],
            options={
                "verbose_name": "URL Pattern",
                "verbose_name_plural": "URL Patterns",
                "db_table": "url_patterns",
                "ordering": ["namespace", "pattern_name"],
                "indexes": [
                    models.Index(fields=["app_label", "is_active"], name="urlpat_app_active_idx"),
                    models.Index(fields=["namespace", "is_active"], name="urlpat_ns_active_idx"),
                ],
                "unique_together": {("namespace", "pattern_name")},
            },
        ),
        migrations.CreateModel(
            name="Handler",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier (e.g., 'project_fields')",
                        max_length=100,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name (e.g., 'Project Fields Loader')",
                        max_length=200,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="What this handler does",
                        verbose_name="Description",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("input", "Input Handler"),
                            ("processing", "Processing Handler"),
                            ("output", "Output Handler"),
                        ],
                        db_index=True,
                        help_text="Handler type: input, processing, or output",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "module_path",
                    models.CharField(
                        help_text="Python module path (e.g., 'apps.bfagent.services.handlers.input_handlers')",
                        max_length=255,
                        verbose_name="Module Path",
                    ),
                ),
                (
                    "class_name",
                    models.CharField(
                        help_text="Handler class name (e.g., 'ProjectFieldsHandler')",
                        max_length=100,
                        verbose_name="Class Name",
                    ),
                ),
                (
                    "config_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON Schema for validating handler configuration",
                        verbose_name="Config Schema",
                    ),
                ),
                (
                    "input_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON Schema describing expected input structure",
                        verbose_name="Input Schema",
                    ),
                ),
                (
                    "output_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON Schema describing output structure",
                        verbose_name="Output Schema",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0",
                        help_text="Semantic version (e.g., '1.2.3')",
                        max_length=20,
                        verbose_name="Version",
                    ),
                ),
                (
                    "is_deprecated",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Is this handler deprecated?",
                        verbose_name="Is Deprecated",
                    ),
                ),
                (
                    "deprecation_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Why this handler is deprecated",
                        verbose_name="Deprecation Reason",
                    ),
                ),
                (
                    "avg_execution_time_ms",
                    models.IntegerField(
                        default=0,
                        help_text="Average execution time in milliseconds",
                        verbose_name="Avg Execution Time (ms)",
                    ),
                ),
                (
                    "success_rate",
                    models.FloatField(
                        default=100.0,
                        help_text="Success rate percentage (0-100)",
                        verbose_name="Success Rate",
                    ),
                ),
                (
                    "total_executions",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Total number of executions",
                        verbose_name="Total Executions",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Is this handler available for use?",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "requires_llm",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Does this handler require LLM API calls?",
                        verbose_name="Requires LLM",
                    ),
                ),
                (
                    "is_experimental",
                    models.BooleanField(
                        default=False,
                        help_text="Is this handler in experimental/beta phase?",
                        verbose_name="Is Experimental",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "documentation_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Link to detailed documentation",
                        verbose_name="Documentation URL",
                    ),
                ),
                (
                    "example_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Example configuration for documentation",
                        verbose_name="Example Config",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_handlers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "replacement_handler",
                    models.ForeignKey(
                        blank=True,
                        help_text="Recommended replacement if deprecated",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaces",
                        to="core.handler",
                        verbose_name="Replacement Handler",
                    ),
                ),
                (
                    "required_handlers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Handlers that must run before this one",
                        related_name="dependent_handlers",
                        to="core.handler",
                        verbose_name="Required Handlers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Handler",
                "verbose_name_plural": "Handlers",
                "db_table": "handlers",
                "ordering": ["category", "code"],
                "indexes": [
                    models.Index(fields=["category", "is_active"], name="hdlr_cat_active_idx"),
                    models.Index(fields=["code"], name="hdlr_code_idx"),
                    models.Index(fields=["-total_executions"], name="hdlr_executions_idx"),
                    models.Index(fields=["is_active", "is_deprecated"], name="hdlr_status_idx"),
                    models.Index(fields=["requires_llm", "is_active"], name="hdlr_llm_active_idx"),
                ],
            },
        ),
    ]
