# Generated by Django 5.2.6 on 2026-01-11 15:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfagent', '0051_bug_llm_assignment'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(blank=True, db_index=True, help_text='Human-readable ID: BUG-0001, FEAT-0042, TASK-0123', max_length=50, unique=True)),
                ('item_type', models.CharField(choices=[('bug', '🐛 Bug'), ('feature', '✨ Feature'), ('task', '📋 Task'), ('enhancement', '🔧 Enhancement'), ('refactor', '♻️ Refactor')], db_index=True, default='task', help_text='Art des Work Items', max_length=20)),
                ('title', models.CharField(help_text='Titel/Zusammenfassung', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Detaillierte Beschreibung')),
                ('status', models.CharField(choices=[('backlog', '📦 Backlog'), ('todo', '📝 To Do'), ('in_progress', '🚧 In Progress'), ('in_review', '👀 In Review'), ('testing', '🧪 Testing'), ('done', '✅ Done'), ('blocked', '🚫 Blocked'), ('cancelled', '❌ Cancelled')], db_index=True, default='backlog', max_length=20)),
                ('priority', models.CharField(choices=[('critical', '🔥 Critical'), ('high', '🔴 High'), ('medium', '🟡 Medium'), ('low', '🔵 Low')], db_index=True, default='medium', max_length=20)),
                ('complexity', models.CharField(choices=[('auto', '🤖 Auto-Detect'), ('low', '🟢 Low'), ('medium', '🟡 Medium'), ('high', '🔴 High')], default='auto', help_text='Komplexität (auto = automatische Erkennung)', max_length=20)),
                ('llm_tier', models.CharField(blank=True, choices=[('tier_1', '💚 Tier 1 (Günstig)'), ('tier_2', '💛 Tier 2 (Standard)'), ('tier_3', '🔴 Tier 3 (Premium)')], help_text='Empfohlener/zugewiesener LLM Tier', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags für Filterung (Liste von Strings)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Zusätzliche Metadaten (flexibles Schema)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('legacy_requirement_id', models.UUIDField(blank=True, db_index=True, help_text='ID des ursprünglichen TestRequirement (für Migration)', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_items', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_items', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(blank=True, help_text='Zugehörige Domain (writing_hub, control_center, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='bfagent.domainart')),
                ('llm_override', models.ForeignKey(blank=True, help_text='Manueller LLM Override', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_item_overrides', to='bfagent.llms')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent Work Item (z.B. Feature → Tasks)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.workitem')),
            ],
            options={
                'verbose_name': 'Work Item',
                'verbose_name_plural': 'Work Items',
                'db_table': 'work_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BugDetails',
            fields=[
                ('work_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bug_details', serialize=False, to='core.workitem')),
                ('url', models.URLField(blank=True, help_text='URL wo der Bug gefunden wurde', max_length=500)),
                ('actual_behavior', models.TextField(blank=True, help_text='Was passiert aktuell (Ist-Zustand)')),
                ('expected_behavior', models.TextField(blank=True, help_text='Was sollte passieren (Soll-Zustand)')),
                ('steps_to_reproduce', models.TextField(blank=True, help_text='Schritte zur Reproduktion')),
                ('acceptance_criteria', models.JSONField(blank=True, default=list, help_text='Acceptance Criteria im Gherkin Format')),
                ('environment', models.JSONField(blank=True, default=dict, help_text='Browser, OS, etc.')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='work_items/bugs/%Y/%m/')),
            ],
            options={
                'verbose_name': 'Bug Details',
                'verbose_name_plural': 'Bug Details',
                'db_table': 'work_item_bug_details',
            },
        ),
        migrations.CreateModel(
            name='FeatureDetails',
            fields=[
                ('work_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='feature_details', serialize=False, to='core.workitem')),
                ('user_story', models.TextField(blank=True, help_text='User Story: Als [Rolle] möchte ich [Funktion] damit [Nutzen]')),
                ('specification', models.TextField(blank=True, help_text='Technische Spezifikation')),
                ('module_path', models.CharField(blank=True, help_text='Python Module Path (z.B. apps.writing_hub.handlers)', max_length=500)),
                ('file_path', models.CharField(blank=True, help_text='Relativer Dateipfad', max_length=500)),
                ('acceptance_criteria', models.JSONField(blank=True, default=list, help_text='Acceptance Criteria')),
            ],
            options={
                'verbose_name': 'Feature Details',
                'verbose_name_plural': 'Feature Details',
                'db_table': 'work_item_feature_details',
            },
        ),
        migrations.CreateModel(
            name='TaskDetails',
            fields=[
                ('work_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='task_details', serialize=False, to='core.workitem')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Geschätzte Stunden', max_digits=5, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Tatsächliche Stunden', max_digits=5, null=True)),
                ('execution_log', models.TextField(blank=True, help_text='Ausführungs-Log')),
                ('checklist', models.JSONField(blank=True, default=list, help_text='Task Checklist: [{text: str, done: bool}]')),
            ],
            options={
                'verbose_name': 'Task Details',
                'verbose_name_plural': 'Task Details',
                'db_table': 'work_item_task_details',
            },
        ),
        migrations.CreateModel(
            name='WorkItemComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_type', models.CharField(choices=[('comment', '💬 Kommentar'), ('progress', '📈 Fortschritt'), ('blocker', '🚫 Blocker'), ('question', '❓ Frage'), ('solution', '💡 Lösung'), ('review', '👀 Review')], default='comment', max_length=20)),
                ('content', models.TextField()),
                ('is_from_cascade', models.BooleanField(default=False, help_text='True wenn von Cascade AI generiert')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='work_items/comments/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_item_comments', to=settings.AUTH_USER_MODEL)),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.workitem')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'work_item_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkItemLLMAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('initial_tier', models.CharField(choices=[('tier_1', '💚 Tier 1 (Günstig)'), ('tier_2', '💛 Tier 2 (Standard)'), ('tier_3', '🔴 Tier 3 (Premium)')], default='tier_1', help_text='Ursprünglich zugewiesener Tier', max_length=20)),
                ('current_tier', models.CharField(choices=[('tier_1', '💚 Tier 1 (Günstig)'), ('tier_2', '💛 Tier 2 (Standard)'), ('tier_3', '🔴 Tier 3 (Premium)')], default='tier_1', help_text='Aktueller Tier (nach Eskalationen)', max_length=20)),
                ('complexity_score', models.IntegerField(default=0, help_text='Berechneter Komplexitäts-Score (0-10)')),
                ('attempts', models.IntegerField(default=0)),
                ('escalation_count', models.IntegerField(default=0)),
                ('tokens_input', models.IntegerField(default=0)),
                ('tokens_output', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, help_text='Kosten in USD', max_digits=10)),
                ('status', models.CharField(choices=[('pending', '⏳ Pending'), ('in_progress', '🔄 In Progress'), ('resolved', '✅ Resolved'), ('escalated', '⬆️ Escalated'), ('failed', '❌ Failed')], default='pending', max_length=20)),
                ('resolution_confidence', models.FloatField(blank=True, help_text='Konfidenz der Lösung (0-1)', null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notizen zur Lösung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_history', models.JSONField(default=list, help_text='Historie aller Versuche')),
                ('llm_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_item_assignments', to='bfagent.llms')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_assignments', to='core.workitem')),
            ],
            options={
                'verbose_name': 'LLM Assignment',
                'verbose_name_plural': 'LLM Assignments',
                'db_table': 'work_item_llm_assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['item_type', 'status'], name='work_items_item_ty_06133f_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['domain', 'status'], name='work_items_domain__0e6812_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['assigned_to', 'status'], name='work_items_assigne_19236e_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['priority', 'status'], name='work_items_priorit_d8b6aa_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['created_at'], name='work_items_created_6a1494_idx'),
        ),
        migrations.AddIndex(
            model_name='workitemllmassignment',
            index=models.Index(fields=['status', 'current_tier'], name='work_item_l_status_d0e0c2_idx'),
        ),
        migrations.AddIndex(
            model_name='workitemllmassignment',
            index=models.Index(fields=['work_item', 'status'], name='work_item_l_work_it_3b1ef4_idx'),
        ),
    ]
