# Generated by Django 5.2.6 on 2025-12-17 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuardrailCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('display_order', models.IntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guardrail Category',
                'verbose_name_plural': 'Guardrail Categories',
                'db_table': 'ui_hub_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HTMXPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('pattern_type', models.CharField(choices=[('inline_edit', 'Inline Edit'), ('delete_row', 'Delete Row'), ('search_filter', 'Search/Filter'), ('modal_form', 'Modal Form'), ('pagination', 'Pagination'), ('infinite_scroll', 'Infinite Scroll'), ('lazy_load', 'Lazy Load')], db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('view_template', models.TextField(blank=True, help_text='Django view function template')),
                ('html_template', models.TextField(blank=True, help_text='HTML template with HTMX attributes')),
                ('partial_template', models.TextField(blank=True, help_text='HTMX partial template')),
                ('javascript', models.TextField(blank=True, help_text='Optional JavaScript code')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HTMX Pattern',
                'verbose_name_plural': 'HTMX Patterns',
                'db_table': 'ui_hub_htmx_patterns',
                'ordering': ['pattern_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ValidationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('target_path', models.CharField(max_length=500)),
                ('app_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('total_files', models.IntegerField(default=0)),
                ('violations_found', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('warnings_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Validation Session',
                'verbose_name_plural': 'Validation Sessions',
                'db_table': 'ui_hub_validation_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('template_type', models.CharField(choices=[('view', 'View Function'), ('template', 'HTML Template'), ('partial', 'HTMX Partial'), ('url', 'URL Pattern'), ('service', 'Service Function'), ('selector', 'Selector Function')], db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('content', models.TextField(help_text='Jinja2 template content')),
                ('variables_schema', models.JSONField(default=dict, help_text='JSON schema for required variables')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Code Template',
                'verbose_name_plural': 'Code Templates',
                'db_table': 'ui_hub_templates',
                'ordering': ['template_type', 'name'],
                'indexes': [models.Index(fields=['template_type', 'is_active'], name='ui_hub_temp_templat_8c7b11_idx')],
            },
        ),
        migrations.CreateModel(
            name='GuardrailRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField()),
                ('pattern', models.CharField(help_text='Regex pattern to validate against', max_length=500)),
                ('message', models.TextField(help_text='Error message when violated')),
                ('suggestion', models.TextField(blank=True, help_text='Suggested fix for the violation')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='warning', max_length=20)),
                ('is_builtin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='ui_hub.guardrailcategory')),
            ],
            options={
                'verbose_name': 'Guardrail Rule',
                'verbose_name_plural': 'Guardrail Rules',
                'db_table': 'ui_hub_rules',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RuleExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(help_text='Example code')),
                ('is_valid', models.BooleanField(help_text='True if this is a valid example, False if anti-pattern')),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='ui_hub.guardrailrule')),
            ],
            options={
                'verbose_name': 'Rule Example',
                'verbose_name_plural': 'Rule Examples',
                'db_table': 'ui_hub_rule_examples',
                'ordering': ['-is_valid', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RuleViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(db_index=True, max_length=500)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('code_snippet', models.TextField()),
                ('message', models.TextField()),
                ('app_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('severity', models.CharField(db_index=True, max_length=20)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='ui_hub.guardrailrule')),
            ],
            options={
                'verbose_name': 'Rule Violation',
                'verbose_name_plural': 'Rule Violations',
                'db_table': 'ui_hub_violations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='guardrailrule',
            index=models.Index(fields=['category', 'is_active'], name='ui_hub_rule_categor_756607_idx'),
        ),
        migrations.AddIndex(
            model_name='guardrailrule',
            index=models.Index(fields=['severity', 'is_active'], name='ui_hub_rule_severit_ce2b17_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleviolation',
            index=models.Index(fields=['file_path', 'is_resolved'], name='ui_hub_viol_file_pa_c9dc4a_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleviolation',
            index=models.Index(fields=['severity', 'is_resolved'], name='ui_hub_viol_severit_19c896_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleviolation',
            index=models.Index(fields=['created_at', 'is_resolved'], name='ui_hub_viol_created_8135b5_idx'),
        ),
    ]
