"""Plugin protocols for extensible hub identity system (Design #1)."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Protocol, runtime_checkable

if TYPE_CHECKING:
    from hub_identity.core.schema import HubDNA
    from hub_identity.core.scoring import ScoreNode


# ── Auditor Plugin ──────────────────────────────────────────────


@dataclass
class PatternMatch:
    """Single detected AI fingerprint pattern."""

    pattern_id: str
    category: str
    description: str
    weight: float
    matched_value: str = ""
    field_name: str = ""
    suggestion: str = ""


@runtime_checkable
class AuditorPlugin(Protocol):
    """
    Plugin that detects AI fingerprint patterns in a HubDNA.

    Register via entry point 'hub_identity.auditors'.
    """

    name: str
    version: str
    category: str  # "visual" or "linguistic"

    def detect(self, dna: HubDNA) -> list[PatternMatch]:
        """Return all matched patterns for this auditor."""
        ...

    def weight_multiplier(self) -> float:
        """Category weight multiplier for composite scoring."""
        ...


# ── Mutation Strategy Plugin ────────────────────────────────────


@runtime_checkable
class MutationStrategy(Protocol):
    """
    Single mutation strategy (Design #3: Strategy Pattern).

    Deterministic strategies have no LLM dependency.
    LLM strategies require iil-aifw.
    """

    name: str
    requires_llm: bool

    def should_apply(
        self, dna: HubDNA, score: ScoreNode,
    ) -> bool:
        """Whether this strategy should run given current score."""
        ...

    def apply(self, dna: HubDNA) -> HubDNA:
        """Apply mutation and return new DNA (immutable)."""
        ...


# ── Output Plugin ───────────────────────────────────────────────


@dataclass
class GeneratedFile:
    """A file generated by an output plugin."""

    path: Path
    content: str
    format: str  # "css", "po", "json", "tailwind"


@runtime_checkable
class OutputPlugin(Protocol):
    """
    Plugin that generates output files from HubDNA.

    Register via entry point 'hub_identity.outputs'.
    """

    name: str
    format: str

    def generate(
        self, dna: HubDNA, output_dir: Path,
    ) -> list[GeneratedFile]:
        """Generate output files for the given hub DNA."""
        ...
